/* ============================================================
   饥荒联机版百科 —— 生物图鉴 数据 (js/creatures.js)
   分类：boss（巨兽 / Boss）· hostile（敌对怪物）· neutral（中立生物）· passive（被动生物）
   分类依据「不主动攻击就不还手 / 完全无害」的实际行为，按官方维基词条首句措辞核对：
     被动 = 只会逃跑、不能战斗；中立 = 被攻击才反击；敌对 = 看见玩家就动手。

   数值全部按「Don't Starve Together（联机版）」核对
   （来源：官方维基各词条 /DST 页面的 Infobox，2026-09 校对）

   字段：
     hp      生命值（联机版数值；hpText 用于多阶段 / 区间）
     dmg     单次攻击伤害（只有 wik 明确区分时才写「对玩家 X」）
     atk     攻击间隔（秒）   range 攻击范围   speed 移动速度
     sanity  理智光环（每分钟）；正数是站着回理智
     saneFight 战斗时的理智光环
     where   出现条件与位置     drops 掉落物     note 打法 / 机制
   ============================================================ */

const MOB_CATS = {
  boss:    { cn: '巨兽 / Boss', color: '#e06a5a' },
  hostile: { cn: '敌对怪物',     color: '#b98f5c' },
  neutral: { cn: '中立生物',     color: '#6fb0d8' },
  passive: { cn: '被动生物',     color: '#7fc08a' }
};

const MOBS = [
  /* ==================== 巨兽 / Boss ==================== */
  { id: 'deerclops', cn: '独眼巨鹿（鹿角怪）', en: 'Deerclops', img: 'mob_deerclops.png', cat: 'boss',
    hp: 4000, dmg: '75（对玩家）/ 150（对生物）', atk: 4, range: 8, speed: 3, sanity: -100, saneFight: -400,
    where: '冬季（第 1 个冬天末开始）在玩家附近刷出并一路跟着某人，路过基地时会拆建筑和树',
    drops: ['大肉 ×8', '独眼巨鹿眼球', '独眼巨鹿手稿（雕像草图）'],
    note: '攻击带小范围 AOE 并附带冰冻。攻击间隔 4 秒，标准打法是「打二走一」；它走路慢，拉到空地再打。眼球可以做眼球伞、眼球炮塔，是冬天最实用的掉落。' },
  { id: 'bearger', cn: '熊獾', en: 'Bearger', img: 'mob_bearger.png', cat: 'boss',
    hp: 6000, dmg: '175（对玩家 87.5）', atk: 3, range: 5, speed: '3（平静）/ 6（激怒）', sanity: -100, saneFight: -400,
    where: '秋季在玩家附近出现（第 2 年秋天起），会被地上和容器里的食物吸引',
    drops: ['大肉 ×8', '厚毛皮（熊皮）', '毛簇（每 45 秒自动掉一次）', '熊獾手稿（雕像草图）'],
    note: '每 3 次攻击后释放范围强震（AOE），还会把玩家手里的武器震飞，并吃光箱子和地上的食物。怕火，着火时会慌乱。毛皮可以做熊皮背心。' },
  { id: 'moose', cn: '麋鹿鹅', en: 'Moose / Goose', img: 'mob_moose.png', cat: 'boss',
    hp: 6000, dmg: '150（对玩家 75）', atk: 3, range: 5.5, speed: '8 / 12（冲刺）',
    where: '春季在玩家附近出现，会在池塘边筑巢下蛋，巢边有麋鹿鹅幼崽',
    drops: ['大肉 ×6', '鸡腿 ×2', '羽绒 ×3-5', '麋鹿鹅手稿（雕像草图）'],
    note: '被攻击时会「鸣叫」，把玩家手里的武器震掉；会保护幼崽（打幼崽会让大鹅狂暴）。羽绒是做羽绒服、羽绒枕的材料。' },
  { id: 'dragonfly', cn: '龙蝇', en: 'Dragonfly', img: 'mob_dragonfly.png', cat: 'boss',
    hp: 27500, dmg: '挥击 150（对玩家 75）/ 火环 75×3（对玩家 37.5×3）', atk: '4（暴怒 3）', range: '4（暴怒 6）', speed: '6.5（暴怒 9.1）',
    where: '沙漠中的「龙蝇巢」固定生成（打巢边的岩浆虫会把它引过来），夏季也可能主动出现',
    drops: ['龙鳞 ×1', '鳞片熔炉蓝图', '岩浆虫卵 ×0-1', '大肉 ×6', '金块 ×4-8', '红 / 蓝宝石 ×2、紫 / 橙 / 黄 / 绿宝石 ×1-2', '龙蝇手稿（雕像草图）'],
    note: '攻击附带燃烧，近身会被点燃，要带防火装备或用冰块降温。血量极高，暴怒时伤害和攻速翻倍——杀光它身边的岩浆虫就会进入暴怒。单人建议堆回血料理 + 影刀 + 骨甲硬磨。' },
  { id: 'bee_queen', cn: '蜂王', en: 'Bee Queen', img: 'mob_bee_queen.png', cat: 'boss', alias: ['蜂王'],
    hp: 22500, dmg: '120（对玩家 60）', atk: 2, range: 4, speed: 5.6,
    where: '草原上唯一的「巨型蜂巢」——用锤子反复敲击就能把她召唤出来',
    drops: ['蜂蜜 ×3-4', '蜂窝 ×1-2', '螫针 ×1', '蜂王浆 ×6-7', '女王蜂帽', '打包带蓝图（稀有）', '蜂王手稿（雕像草图）'],
    note: '会不断召唤大蜂，血量降低后开始狂暴（叫喊强化大蜂），经过的地方留下减速的蜂蜜痕迹。戴养蜂帽可减伤。蜂王浆是彩虹糖豆的唯一材料。' },
  { id: 'klaus', cn: '克劳斯', en: 'Klaus', img: 'mob_klaus.png', cat: 'boss',
    hp: 10000, hpText: '10000（狂暴 27440）', dmg: '37.5（对玩家）/ 75（对生物）；狂暴 102.8 / 205.8', atk: '3（狂暴 2.14）', range: '3（狂暴 4.2）', speed: 2.75, sanity: -100,
    where: '对「赃物袋」使用鹿角召唤（赃物袋是冬季在野外随机出现的礼物袋）',
    drops: ['赃物袋内的随机宝物（宝石 / 稀有道具）', '麋鹿茸 ×1（开启赃物袋的钥匙）', '克劳斯手稿（雕像草图，冬季盛宴期间额外掉拐杖糖 ×2）'],
    note: '身旁总跟着红 / 蓝两只宝石鹿，会指挥它们铺火系和冰系法阵。他两下连击，打法是「骗出双连击再回身」。离开战斗后会每秒回 25 血；狂暴后伤害翻倍但受到的伤害降到 0.36 倍。' },
  { id: 'crab_king', cn: '帝王蟹', en: 'Crab King', img: 'mob_crab_king.png', cat: 'boss',
    hp: 12000, hpText: '12000（上限随嵌入宝石数量提高）', dmg: '本体不攻击（巨钳 40-90 / 加农炮塔 20-100）', atk: '巨钳 4',
    where: '海洋深处的「帝王蟹布景」（沉睡在一圈礁岩中央），给它嵌宝石即可唤醒',
    drops: ['镶嵌的全部宝石（可收回）', '大肉 ×5-6', '漂流瓶 ×2-4', '螃蟹跳板 ×8', '低 / 中 / 高音贝壳钟 ×3-5 / 2-4 / 1-3', '藤壶 ×2-4', '魔音三叉戟蓝图（稀有）', '帝王蟹手稿（雕像草图）', '裂开的珍珠 + 未启动的天体贡品（嵌入珍珠的珍珠时）'],
    note: '战斗能力取决于镶嵌的宝石颜色：红=血量与回血、蓝=冰冻、紫=间歇泉、黄=施法速度、绿=巨钳。嵌入「珍珠的珍珠」时额外掉落天体贡品。死亡后 20 天原地重生；本体不攻击，但巨钳与加农炮会持续破坏船只。' },
  { id: 'toadstool', cn: '毒菌蟾蜍', en: 'Toadstool', img: 'mob_toadstool.png', cat: 'boss', alias: ['毒菌蟾蜍', '悲惨的毒菌蟾蜍'],
    hp: 52500, hpText: '52500（苦难形态 99999）', dmg: '100 / 120 / 150 / 250（苦难 150 / 175 / 225 / 300）', atk: '3.5 / 3 / 2.5 / 2', range: 7, speed: '0.6 → 3.2（随阶段）',
    where: '洞穴的蘑菇林，对「毒菌蟾蜍菌盖」使用炸药或蘑菇皮召唤（苦难形态需献上特殊贡品）',
    drops: ['青蛙腿 ×1', '大肉 ×3.75', '红 / 绿 / 蓝蘑菇 各约 ×1.66', '蘑菇孢子（雨 / 旱 / 雾孢子）×2.5', '蘑菇皮 ×1', '蘑菇灯蓝图（另有蘑菇帽蓝图）', '毒菌蟾蜍手稿（雕像草图）'],
    note: '会喷吐孢子云、召唤爆炸蘑菇与发光孢子帽，血量越低攻击越猛。打它需要「火腿棒 / 亮茄粉碎者 + 骨甲 + 大量回血」，单人磨很久，建议多人分工。蘑菇皮可以做蘑菇灯、蘑菇帽。' },
  { id: 'fuelweaver', cn: '远古织影者', en: 'Ancient Fuelweaver', img: 'mob_fuelweaver.png', cat: 'boss', alias: ['远古织影者', '上古织影者'],
    hp: 16000, dmg: '100（直接攻击）/ 80（骨刺上挑）', atk: 3, range: 2.4, speed: 4.2, sanity: -400,
    where: '遗迹「中庭」：把「暗影心房」插入完整的怪异骨架（需要远古钥匙插在远古之门上）',
    drops: ['化石 ×8（必掉）', '暗影香炉', '骨盔', '骨甲', '噩梦燃料 ×4-6', '玫瑰 ×1', '远古织影者手稿（雕像草图）'],
    note: '会用骨笼困住玩家、召唤骨刺与骨墙上挑；第二阶段会吃掉织影回血（每只 +400）并给自己加护盾，同时召出无形之手控住玩家。离开战斗范围他会分解（留下化石 + 暗影心房）。击败后远古之门失稳，4 分钟遗迹重置。' },
  { id: 'celestial', cn: '天体英雄', en: 'Celestial Champion', img: 'mob_celestial.png', cat: 'boss',
    hp: 10000, hpText: '10000 / 13000 / 14000（三个形态）',
    dmg: '一阶：翻滚 166.66（对玩家 125）、范围 66.66（对玩家 50）；二阶：劈砍 / 旋转 133.33（对玩家 100）、尖刺 50（对玩家 37.5）；三阶：突刺 150（对玩家 112.5）、激光 120（对玩家 90）',
    atk: '7.5 / 6 / 5', range: '4.25 / 4.5', speed: '5 / 4.5 / 7.5', sanity: '+100（脱战）/ +400（战斗中）',
    where: '月岛：集齐三座月亮祭坛 → 组装月亮虹吸器 → 流星坠落后召唤',
    drops: ['月亮岩石 ×5-14', '月亮碎片 ×4-26', '灌注月亮碎片 ×6-12', '启迪之冠碎片 ×1', '天体英雄手稿（雕像草图）'],
    note: '全游戏难度最高的 Boss。三个阶段各有招式：翻滚冲刺、劈砍旋转、激光与月光玻璃尖刺，还会召唤虚影与「大虚影」。受伤到一定程度会进入防御姿态（减伤 80%）并召出虚影，要优先清虚影；下潜后会快速回血，别拖。推荐玻璃刀 / 影刀 + 骨甲 + 启迪之冠（免疫催眠）。' },
  { id: 'antlion', cn: '蚁狮', en: 'Antlion', img: 'mob_antlion.png', cat: 'boss',
    hp: 6000, dmg: '50 / 75 / 100（随阶段）', atk: 4, range: 15, sanity: -40,
    where: '夏季沙漠中的「蚁狮巢」（绿洲附近）；它不追人，但会引发沙尘暴与地面塌陷',
    drops: ['沙漠石 ×6-8', '大肉 ×4', '石头 ×2-4', '盗墓者玩具（随机）', '懒惰的沙漠人蓝图（稀有）', '蚁狮手稿（雕像草图）'],
    note: '不会移动也不会主动追人，但生气后会在玩家脚下开沙坑、引发沙尘暴。可以定期献祭（沙子 / 岩石 / 宝石 / 肉类 / 玩具）维持好感，换取安稳的夏天。' },
  { id: 'malbatross', cn: '邪天翁', en: 'Malbatross', img: 'mob_malbatross.png', cat: 'boss', alias: ['邪天翁'],
    hp: 5000, dmg: '150（对玩家 75）', atk: 4, range: 4.5, speed: 3,
    where: '海洋上随机出现（航行或海钓时容易被引过来），会一直跟着船',
    drops: ['大肉 ×7', '邪天翁喙 ×1', '邪天翁羽毛 ×3–5（战斗中受击 / 俯冲另掉；总量不足 24 时死亡掉落补足）', '蓝宝石 ×2–3', '黄宝石（5%）', '邪天翁手稿（雕像草图）'],
    note: '海上 Boss：受击时每次最多额外掉 4 根邪天翁羽毛（每根 5%）；击杀时掉 3–5 根，并按战斗中已掉落数量补足至总计 24 根。羽毛可做航海装备。' },
  { id: 'ancient_guardian', cn: '远古守护者', en: 'Ancient Guardian', img: 'mob_ancient_guardian.png', cat: 'boss',
    hp: 10000, hpText: '10000（二阶段 < 6000）', dmg: '100', atk: 2, range: 4.6, speed: '5 / 冲刺 17',
    where: '遗迹迷宫深处的「远古守护者」房间',
    drops: ['大肉 ×8', '守护者之角', '华丽大箱子', '远古守护者手稿（雕像草图）', '支柱脚手架蓝图（稀有）'],
    note: '会直线冲刺撞击（速度极快、能撞碎建筑），撞墙后会短暂眩晕——这就是输出窗口。第二阶段会召唤暗影触手。' },

  /* ==================== 中立生物 ==================== */
  { id: 'beefalo', cn: '皮弗娄牛', en: 'Beefalo', img: 'mob_beefalo.png', cat: 'neutral',
    hp: 1000, dmg: '34', atk: 4, range: 3, speed: '1.5 / 7（奔跑）',
    where: '草原上的牛群（可以用「牛铃」把牛牵回家）',
    drops: ['大肉 ×4', '牛毛 ×3', '牛角（33%）', '粪便（定期产出）'],
    note: '可以剃毛、喂食驯化成坐骑；春季发情时（屁股变红）会主动攻击玩家。喂「皮弗娄牛零食 / 蒸树枝」能快速回血。' },
  { id: 'koalefant', cn: '考拉象', en: 'Koalefant', img: 'mob_koalefant.png', cat: 'neutral',
    hp: 1000, dmg: '50', atk: 4, speed: '1.5 / 7',
    where: '野外跟着「可疑的泥土堆」一路追踪，挖到最后遇到（冬天会变成冬季考拉象）',
    drops: ['大肉 ×8', '考拉象鼻 / 冬象鼻', '粪便（定期产出）'],
    note: '掉落量极高（8 块大肉），象鼻别直接吃——做成烤象鼻或无花果酿象鼻收益更高。' },
  { id: 'pig', cn: '猪人', en: 'Pig', img: 'mob_pig.png', cat: 'neutral',
    hp: 250, dmg: '33', atk: 3, range: 3, speed: '3 / 5', sanity: '+25（结盟时）',
    where: '猪人房（猪人村）附近，以及猪王周围的村落',
    drops: ['大肉（75%）', '猪皮（25%）', '金腰带（1%）'],
    note: '给一块肉就能招募它帮忙砍树 / 战斗；喂 4 块怪物肉或月圆之夜会变成疯猪。它是前期最实用的「劳动力」。' },
  { id: 'pig_guard', cn: '猪人守卫', en: 'Guardian Pig', img: 'mob_pig_guard.png', cat: 'hostile',
    hp: 600, dmg: '33', atk: 1.5, range: 3, speed: '3 / 5',
    where: '猪人村 / 猪王附近巡逻（猪火炬旁）',
    drops: ['大肉（75%）', '猪皮（25%）'],
    note: '血量是普通猪人的两倍多，攻击间隔也更短。攻击猪人或猪王会立刻激怒它和附近所有猪人。' },
  { id: 'rabbit', cn: '兔子', en: 'Rabbit', img: 'mob_rabbit.png', cat: 'passive',
    hp: 25, dmg: '不攻击', speed: '5（逃跑）',
    where: '草地上的兔子洞（冬天变成白兔 / 雪兔；理智低于 40% 时会变成「胡须兔」）',
    drops: ['小肉', '胡须（胡须兔：怪物肉 40% / 噩梦燃料 40% / 胡子 20%）'],
    note: '用陷阱能稳定捕捉；抓来的兔子放久了会变黑（黑兔 → 黑肉）——其实是理智太低导致的幻象兔。' },
  { id: 'gobbler', cn: '火鸡', en: 'Gobbler', img: 'mob_gobbler.png', cat: 'passive',
    hp: 50, dmg: '不攻击', speed: '3 / 8',
    where: '靠近浆果丛时出现（会吃掉灌木上的浆果）',
    drops: ['鸡腿 ×2'],
    note: '把浆果或蘑菇扔在地上引诱后围堵即可。掉落鸡腿（火鸡正餐的材料）。' },
  { id: 'bee', cn: '蜜蜂', en: 'Bee', img: 'mob_bee.png', cat: 'neutral',
    hp: 100, dmg: '10', atk: 2, range: 0.6, speed: '4 / 6',
    where: '野外的蜂巢 / 蜂箱附近（给花授粉）',
    drops: ['蜂蜜（16.7%）', '蜂刺（83.3%）'],
    note: '采蜜会激怒整窝蜜蜂；也是养蜂箱产蜜的来源。被激怒的蜜蜂会一路追到基地。' },
  { id: 'crow', cn: '乌鸦', en: 'Crow', img: 'mob_crow.png', cat: 'passive',
    hp: 25, dmg: '不攻击',
    where: '地面上的种子 / 食物附近；常见于岩石地皮和玩家铺设的地皮',
    drops: ['小肉（50%）或漆黑羽毛（50%）'],
    note: '击杀或在背包中谋杀被捕获的乌鸦，会在小肉与漆黑羽毛之间随机掉落其一。漆黑羽毛也可从企鹅、秃鹫等来源获得。' },
  { id: 'redbird', cn: '红鸟', en: 'Redbird', img: 'mob_redbird.png', cat: 'passive',
    hp: 25, dmg: '不攻击',
    where: '春、夏季的地面种子 / 食物附近，草地地皮更常见',
    drops: ['小肉（50%）或深红羽毛（50%）'],
    note: '红鸟对应深红羽毛；击杀或谋杀时，小肉与羽毛为互斥掉落。' },
  { id: 'snowbird', cn: '雪雀', en: 'Snowbird', img: 'mob_snowbird.png', cat: 'passive',
    hp: 25, dmg: '不攻击',
    where: '冬季的地面种子 / 食物附近，草地地皮更常见',
    drops: ['小肉（50%）或天蓝羽毛（50%）'],
    note: '雪雀对应天蓝羽毛；击杀或谋杀时，小肉与羽毛为互斥掉落。' },

  { id: 'tallbird', cn: '高脚鸟', en: 'Tallbird', img: 'mob_tallbird.png', cat: 'hostile',
    hp: 800, dmg: '50', atk: 2, range: 3, speed: 7,
    where: '草原上的「高脚鸟巢」（巢里有一颗高脚鸟蛋）',
    drops: ['大肉 ×2'],
    note: '偷蛋会被无限追杀（能追很远）。高脚鸟蛋 1 颗 = 4 点蛋度，是苏格兰蛋和培根煎蛋的关键材料。' },
  { id: 'smallbird', cn: '小高鸟', en: 'Smallbird', img: 'mob_smallbird.png', cat: 'passive',
    hp: 600, hpText: '小高鸟 50 / 青年高鸟 600', dmg: '37.5（啄击 2）', atk: '2（啄击 4）', range: 3, speed: 6,
    where: '孵化高脚鸟蛋（小高鸟）并喂养长大（青年高鸟）',
    drops: ['小肉（小高鸟）', '大肉（青年高鸟）'],
    note: '会把玩家当妈跟着走，饿了会啄你要食物；长大后可以「勾引」到怪群中当坦克。' },
  { id: 'catcoon', cn: '浣熊猫', en: 'Catcoon', img: 'mob_catcoon.png', cat: 'neutral',
    hp: 150, dmg: '25', atk: 2, range: '3-4（扑击）', speed: 3,
    where: '桦树林中的浣熊猫巢（空树桩），会翻找容器和晾肉架',
    drops: ['小肉', '猫尾（33%）'],
    note: '会主动叼走食物、翻垃圾桶。给它「花朵 / 玩具」等小礼物可以刷好感，猫尾能做法杖。' },
  { id: 'glommer', cn: '格罗姆', en: 'Glommer', img: 'mob_glommer.png', cat: 'passive',
    hp: 100, dmg: '不攻击', sanity: '+6.25（结盟时）',
    where: '满月之夜在格罗姆雕像旁出现（只有一只）',
    drops: ['格罗姆之翼 ×1', '格罗姆黏液 ×2（平时每 2–4 天定期掉落 1 个）', '怪物肉 ×3'],
    note: '站在旁边会持续回理智。格罗姆黏液也会定期掉落，可作燃料、肥料并用于制作；击杀格罗姆会立即召来坎普斯。' },
  { id: 'walrus', cn: '海象（海象爸爸）', en: 'MacTusk', img: 'mob_walrus.png', cat: 'hostile',
    hp: 300, dmg: '33（吹箭远程）', atk: 3, speed: '2 / 4',
    where: '冬季的「海象营地」（带两只冰猎犬，只在冬天出现）',
    drops: ['大肉', '吹箭', '海象牙（50%）', '苏格兰帽（25%）'],
    note: '远程吹箭会减速，先解决冰猎犬再追他。海象牙是做唤星法杖类道具的材料，苏格兰帽是非常好的保暖装备。' },
  { id: 'moleworm', cn: '鼹鼠', en: 'Moleworm', img: 'mob_moleworm.png', cat: 'passive',
    hp: 30, dmg: '不攻击',
    where: '地下挖洞的鼹鼠（会钻出地面偷地上的矿物），挖开鼹鼠洞也能找到',
    drops: ['小肉 ×1', '它偷走的那些物品'],
    note: '用锤子 / 陷阱捕捉。0.5 肉度，也是鳄梨酱的指定材料；在基地周围要小心它偷矿物。' },
  { id: 'buzzard', cn: '秃鹫', en: 'Buzzard', img: 'mob_buzzard.png', cat: 'neutral',
    hp: 250, dmg: '15', atk: 2, range: 2, speed: '4 / 8',
    where: '沙漠的枯树 / 仙人掌顶部，会俯冲下来吃地上的肉',
    drops: ['大肉 ×1', '漆黑羽毛（33%）'],
    note: '击杀会掉大肉，并有 33% 概率掉漆黑羽毛；会盘旋俯冲，把肉放地上能引它下来。' },
  { id: 'rock_lobster', cn: '石龙虾', en: 'Rock Lobster', img: 'mob_rock_lobster.png', cat: 'neutral',
    hp: 3600, hpText: '2250-3600（随体型）', dmg: '56.25-90', speed: 2,
    where: '洞穴中的石虾群（躲在石头堆里）',
    drops: ['石头 ×2', '燧石 ×2', '大肉 ×1'],
    note: '血量高，但移动慢。它会缩进壳里（减伤 95%）并缓慢回血；可以「喂石头」招募它当保镖，是洞穴玩家的肉盾。（官方维基没有给出它的攻击间隔）' },
  { id: 'grass_gecko', cn: '草壁虎', en: 'Grass Gekko', img: 'mob_grass_gecko.png', cat: 'passive', alias: ['草壁虎'],
    hp: 150, dmg: '不攻击', speed: '1 / 10（逃跑）',
    where: '沙漠中稀有的草丛附近、月岛也有分布',
    drops: ['草 ×0-2', '叶肉'],
    note: '会吃草并吐出草，是稳定的草来源；受惊时会掉落更多草。' },

  /* ==================== 敌对怪物 ==================== */
  { id: 'hound', cn: '猎犬', en: 'Hound', img: 'mob_hound.png', cat: 'hostile',
    hp: 150, dmg: '20', atk: 2, range: 3, speed: '10（冲刺）', sanity: -40,
    where: '「猎犬袭击」：随天数增加频率和数量，从地图边缘朝着某位玩家冲进基地；也住在猎犬丘',
    drops: ['怪物肉', '犬牙（12.5%）'],
    note: '袭击是定时事件，建议在基地外修「犬牙陷阱阵」或拉到大理石地板 / 沼泽借触手解决。联机版的猎犬还能下水。' },
  { id: 'red_hound', cn: '火猎犬（红猎犬）', en: 'Fire Hound', img: 'mob_red_hound.png', cat: 'hostile',
    hp: 100, dmg: '30', atk: 2, range: 3, speed: '10（冲刺）', sanity: -40,
    where: '夏季的猎犬袭击（猎犬丘、座狼也会产出）',
    drops: ['怪物肉', '犬牙', '灰烬 ×3', '红宝石（20%）'],
    note: '死亡时会原地爆燃并留下 3 团火（火灾隐患），别在木建筑旁边打，最好拉到沙地或水边解决。能下水。' },
  { id: 'blue_hound', cn: '冰猎犬（蓝猎犬）', en: 'Ice Hound', img: 'mob_blue_hound.png', cat: 'hostile',
    hp: 100, dmg: '30', atk: 2, range: 3, speed: '10（冲刺）', sanity: -40,
    where: '冬季的猎犬袭击（猎犬丘、海象营地、座狼也会产出）',
    drops: ['怪物肉', '犬牙 ×2', '蓝宝石（20%）'],
    note: '死亡时会冰冻附近的生物和玩家，被打到会被减速连击，建议带保暖装备。能下水。' },
  { id: 'spider', cn: '蜘蛛', en: 'Spider', img: 'mob_spider.png', cat: 'hostile',
    hp: 100, dmg: '20', atk: 3, range: 3, speed: '3 / 5（奔跑）', sanity: -25,
    where: '蜘蛛巢（黄昏 / 夜晚出巢）与地上的蛛网地块；白天多在巢里睡觉',
    drops: ['怪物肉（50%）', '蛛丝（25%）', '蜘蛛腺体（25%）'],
    note: '群体仇恨：打一只会激怒附近最多 10 只。春季仇恨范围与时间 +33%。怪物肉的主要来源，别用武器硬刚一堆。' },
  { id: 'spider_warrior', cn: '蜘蛛战士', en: 'Spider Warrior', img: 'mob_spider_warrior.png', cat: 'hostile',
    hp: 400, dmg: '20', atk: '4-6', range: 6, speed: '4 / 5', sanity: -40,
    where: '二级 / 三级蜘蛛巢，以及蜘蛛女王身边',
    drops: ['怪物肉（50%）', '蛛丝（25%）', '蜘蛛腺体（25%）'],
    note: '会跳跃扑击（跳过来咬一口），血量是普通蜘蛛的 4 倍，正面硬刚很亏，用陷阱或拉怪更省。' },
  { id: 'spider_queen', cn: '蜘蛛女王', en: 'Spider Queen', img: 'mob_spider_queen.png', cat: 'hostile',
    hp: 2500, dmg: '80', atk: 3, range: 5, speed: 1.75, sanity: -400,
    where: '三级蜘蛛巢继续成长后会变成蜘蛛女王（巢存在很久时出现）',
    drops: ['怪物肉 ×4', '蛛丝 ×4', '蜘蛛卵', '蜘蛛帽'],
    note: '会不断产下蜘蛛、蜘蛛战士和护士蜘蛛。理智光环极强（−400/分），打之前先把理智和回血准备好；击败后她会变回普通蜘蛛巢。' },
  { id: 'cave_spider', cn: '洞穴蜘蛛', en: 'Cave Spider', img: 'mob_cave_spider.png', cat: 'hostile',
    hp: 225, dmg: '20', atk: 3, speed: 3, sanity: -25,
    where: '洞穴的蛛网岩（比地表蜘蛛更主动）',
    drops: ['怪物肉（50%）', '蛛丝（25%）', '蜘蛛腺体（25%）'],
    note: '会躲进壳里获得 75% 减伤，这时候打它很亏，等它探出头再打。地下探索记得带矿工帽 / 提灯。' },
  { id: 'spitter', cn: '喷射蜘蛛', en: 'Spitter', img: 'mob_spitter.png', cat: 'hostile', alias: ['喷射蜘蛛'],
    hp: 350, dmg: '20', atk: 6, range: 8, speed: '4 / 5', sanity: -40,
    where: '洞穴深处的蛛网岩',
    drops: ['怪物肉（50%）', '蛛丝（25%）', '蜘蛛腺体（25%）'],
    note: '远程吐网，被命中会减速（很难跑）。优先远距离点掉。' },
  { id: 'dangling', cn: '穴居悬蛛', en: 'Dangling Depth Dweller', img: 'mob_dangling.png', cat: 'hostile', alias: ['穴居悬蛛'],
    hp: 400, dmg: '20', atk: '4-6', range: 3, speed: 3, sanity: -25,
    where: '洞穴 / 遗迹天花板与华丽箱子附近（从上面吊下来突袭）',
    drops: ['怪物肉（50%）', '蛛丝（25%）', '蜘蛛腺体（25%）'],
    note: '会跳跃扑击，走位时容易被从头顶偷袭；夜里进洞穴要小心。' },
  { id: 'tentacle', cn: '触手', en: 'Tentacle', img: 'mob_tentacle.png', cat: 'hostile',
    hp: 500, dmg: '34', atk: 2, range: 4, sanity: -40,
    where: '沼泽、洞穴（位置固定，不会移动）',    drops: ['怪物肉 ×2', '触手尖刺（50%）', '触手皮（20%）'],
    note: '位置固定、攻击范围很大，打法是「打两下退一步」。也可以故意把猎犬 / 蜘蛛引到触手旁边借刀杀人。' },
  { id: 'leif', cn: '树精（活木守卫）', en: 'Treeguard', img: 'mob_leif.png', cat: 'neutral',
    hp: 3750, hpText: '2100 / 3000 / 3750（小 / 中 / 大）', dmg: '34.65 / 49.5 / 61.875（对生物 105 / 150 / 187.5）', atk: 3, range: '2.1 / 3 / 3.75', speed: '0.735 / 1.5 / 2.34', sanity: -40, saneFight: -100,
    where: '短时间内砍掉大量常青树后有概率出现（也会从被砍倒的树上蹦出来）',
    drops: ['活木材 ×6', '怪物肉 ×1'],
    note: '获得仇恨后很难摆脱。想安抚它就在它附近种几棵树（会停止追击）。活木是许多魔法道具的材料，所以也有人专门刷它。' },
  { id: 'killer_bee', cn: '杀人蜂', en: 'Killer Bee', img: 'mob_killer_bee.png', cat: 'hostile',
    hp: 100, dmg: '10', atk: 2, range: 0.6, speed: '4 / 6',
    where: '杀人蜂窝（野外 / 洞穴）附近，或普通蜂巢被破坏时',
    drops: ['蜂蜜（16.7%）', '蜂刺（83.3%）'],
    note: '比蜜蜂更凶、会主动追人，成群出现。采蜜前先穿养蜂帽或准备蜂房陷阱。' },
  { id: 'bee_grumpy', cn: '嗡嗡蜜蜂', en: 'Grumble Bee', img: 'mob_bee_grumpy.png', cat: 'hostile', alias: ['大蜂'],
    hp: 180, dmg: '15', atk: 2, range: 1.5, speed: '4.2 / 11.2',
    where: '蜂王战斗期间被召唤（也会从养蜂笔记里跑出来）',
    drops: ['蜂刺'],
    note: '比普通蜜蜂更快更凶，被蜂王「叫喊」强化后攻速会大幅提升，是蜂王战的主要压力来源。' },
  { id: 'mosquito', cn: '蚊子', en: 'Mosquito', img: 'mob_mosquito.png', cat: 'hostile',
    hp: 100, dmg: '3（自爆伤害 34）', atk: 2, range: 4, speed: '8 / 12',
    where: '池塘、沼泽、鱼人村附近（夜晚更多）',
    drops: ['蚊子血袋（50%）'],
    note: '普通叮咬只有 3 点伤害，但吸饱血后会膨胀并爆炸（34 伤害 + 血袋）。被一群围攻很烦。' },
  { id: 'frog', cn: '青蛙', en: 'Frog', img: 'mob_frog.png', cat: 'hostile',
    hp: 100, dmg: '10', atk: 1, range: 3, speed: '4 / 8',
    where: '池塘边、沼泽；下雨天会跳得到处都是',
    drops: ['青蛙腿'],
    note: '攻击会把玩家背包里的一件物品打掉在地上；被打会召唤附近同伴（群体仇恨）。蛙腿是蛙腿三明治的材料。' },
  { id: 'merm', cn: '鱼人', en: 'Merm', img: 'mob_merm.png', cat: 'hostile',
    hp: 500, hpText: '500（鱼人王加成 560）', dmg: '30（鱼人王加成 40）', atk: 3, speed: '3 / 8',
    where: '沼泽的鱼人房 / 鱼人村（与猪人是世仇）',
    drops: ['鱼（淡水鱼）', '青蛙腿'],
    note: '会主动攻击猪人，可以利用「猪人 vs 鱼人」让它们互相消耗。鱼人王（King of the Merms）活着时会强化全村鱼人。' },
  { id: 'werepig', cn: '疯猪', en: 'Werepig', img: 'mob_werepig.png', cat: 'hostile',
    hp: 525, dmg: '40', atk: 2, range: 3, speed: '3 / 7', sanity: -100,
    where: '月圆之夜猪人变身、猪人吃下 4 块怪物肉；挖开「可疑的月石」也会冒出一只',
    drops: ['猪皮', '大肉 ×2'],
    note: '变身时会掉出身上带的东西、并吃掉地上的食物。血量比猪人高一倍多，前期别单挑。' },
  { id: 'krampus', cn: '坎普斯', en: 'Krampus', img: 'mob_krampus.png', cat: 'hostile',
    hp: 300, dmg: '50', atk: 1.2, range: 3, speed: '7（逃跑）',
    where: '「淘气值」满时出现（连续击杀太多无害生物，比如兔子、鸟、猪人）；也会从克劳斯的赃物袋里钻出来',
    drops: ['怪物肉', '木炭 ×2', '坎普斯背包（1%）', '被它偷走的物品'],
    note: '会偷走你背包和箱子里的东西（打死后全部掉落）。想刷坎普斯背包就故意「作恶」，但代价是会一直被追。' },
  { id: 'batilisk', cn: '洞穴蝙蝠', en: 'Batilisk', img: 'mob_batilisk.png', cat: 'hostile',
    hp: 50, dmg: '20', atk: 1, range: 1.5, speed: 6,
    where: '洞穴（从洞穴入口 / 蝙蝠洞飞出来，白天又钻回去）；洞穴地表夜晚也有',
    drops: ['蝙蝠粪（15%）', '蝙蝠翅膀（25%）', '怪物肉（10%）'],
    note: '血量低但数量多、飞得快；蝙蝠翅膀可以烤着吃（烤过 +8 血）。酸雨期间掉落变好（蝙蝠粪 30% / 翅膀 50% / 怪物肉 20% / 硝石 20%）。' },
  { id: 'crawling_horror', cn: '爬行梦魇', en: 'Crawling Horror', img: 'mob_crawling_horror.png', cat: 'hostile',
    hp: 300, dmg: '20', atk: 2.5, range: 3, sanity: -100,
    where: '理智值很低时从影子里爬出来（远古雕像 / 梦魇裂隙附近也会）',
    drops: ['噩梦燃料 ×1-2'],
    note: '理智越低出现得越多；被攻击时会瞬移。把它们打掉可以刷噩梦燃料，理智恢复后（吃烤绿蘑菇、站在格罗姆旁）它们会退回去。' },
  { id: 'terrorbeak', cn: '尖牙梦魇', en: 'Terrorbeak', img: 'mob_terrorbeak.png', cat: 'hostile',
    hp: 400, dmg: '50', atk: 1.5, range: 3, speed: '7（冲刺）', sanity: -100,
    where: '理智值极低时出现（比爬行梦魇更危险），海上会变成「恐怖之爪」',
    drops: ['噩梦燃料 ×1-2'],
    note: '移动快、伤害高，被攻击时会瞬移，理智低时最好先退到安全区恢复理智再考虑打。' },
  { id: 'ghost', cn: '幽灵', en: 'Ghost', img: 'mob_ghost.png', cat: 'hostile',
    hp: 200, dmg: '15', atk: 1.2, range: 1.5, speed: '2（漂移）', sanity: -40,
    where: '墓地附近与夜晚出现；玩家死后也会在原地留下一个幽灵',
    drops: [],
    note: '能穿过障碍物追人，攻击是范围伤害。回理智或绕开墓地就能减少遭遇（温蒂不受它扣理智影响）。' },
  { id: 'warg', cn: '座狼', en: 'Varg', img: 'mob_warg.png', cat: 'hostile',
    hp: 1800, dmg: '50', atk: 3, range: 5, speed: '5.5（冲刺）', sanity: -100, saneFight: -400,
    where: '追踪「可疑的泥土堆」（与考拉象共用追踪机制，挖到最后有小概率遇到）',
    drops: ['犬牙 ×1-3', '怪物肉 ×4-6'],
    note: '会不断召唤火 / 冰猎犬帮它打你，打之前先清狗或准备犬牙陷阱。' },
  { id: 'ewecus', cn: '毛怪', en: 'Ewecus', img: 'mob_ewecus.png', cat: 'hostile',
    hp: 800, dmg: '60（黏液吐击 5）',
    where: '追踪「可疑的泥土堆」时出现的稀有生物',
    drops: ['大肉 ×4', '钢丝绵 ×2-3', '痰液 ×1-2', '粪便（定期产出）'],
    note: '会吐出黏痰把玩家粘住（不能移动 / 攻击），需要队友帮忙或提前带「蜘蛛腺体」。钢丝绵是稀有材料。（官方维基没有给出它的攻击间隔）' },
  { id: 'slurper', cn: '啜食者', en: 'Slurper', img: 'mob_slurper.png', cat: 'hostile',
    hp: 200, dmg: '30', atk: 5, range: 8, speed: 9, sanity: -25,
    where: '洞穴（平时缩成一团假装石头，醒着时还会发光）',
    drops: ['荧光果 ×2', '啜食者皮（50%）'],
    note: '会跳到玩家头上「吸走」你的饥饿值并持续攻击，戴上矿工帽 / 头盔可以防止它上头。' },
  { id: 'knight', cn: '发条骑士', en: 'Clockwork Knight', img: 'mob_knight.png', cat: 'hostile',
    hp: 900, dmg: '40', atk: 2, range: 3, speed: 5,
    where: '遗迹（发条生物）与棋盘地形；也可以用雕像修复出来',
    drops: ['发条 ×2'],
    note: '破损版（发条骑士 / 主教 / 战车）会额外掉落噩梦燃料 60% 和铥矿碎片 50%。发条可以给 WX-78 升级。' },
  { id: 'bishop', cn: '发条主教', en: 'Clockwork Bishop', img: 'mob_bishop.png', cat: 'hostile',
    hp: 900, dmg: '40（远程电球）', atk: 4, range: 6, speed: 5,
    where: '遗迹与棋盘地形；也可以用雕像修复出来',
    drops: ['发条 ×2', '紫宝石 ×1'],
    note: '远程放电攻击，会保持距离放风筝，需要斜向走位躲开弹道。' },
  { id: 'rook', cn: '发条战车', en: 'Clockwork Rook', img: 'mob_rook.png', cat: 'hostile',
    hp: 900, dmg: '45（冲锋 90，只对生物）', atk: 2, speed: '5 / 冲刺 16',
    where: '遗迹与棋盘地形；也可以用雕像修复出来',
    drops: ['发条 ×2'],
    note: '会直线冲锋并撞碎建筑，撞到东西后会眩晕——这是最好的输出时机；也可以在它冲锋时侧移躲开。' },
  { id: 'lureplant', cn: '食人花', en: 'Lureplant', img: 'mob_lureplant.png', cat: 'hostile',
    hp: 300, dmg: '本体不攻击（眼球草 20）', atk: '眼球草 1',
    where: '沼泽、洞穴等潮湿区域；砍掉后掉落「肉球」，种下去就长出新的食人花',
    drops: ['肉球（Fleshy Bulb）'],
    note: '会长出眼球草，把附近的东西（包括你的掉落物）吃掉。叶肉主要来自眼球草；注意它会吞掉你的战利品。' },
  { id: 'slurtle', cn: '蜗龟', en: 'Slurtle', img: 'mob_slurtle.png', cat: 'neutral',
    hp: 1200, hpText: '蜗龟 1200 / 蜗牛龟 200', dmg: '25', atk: 4, range: 2.5, speed: 3,
    where: '洞穴的「蜗龟丘」（蜗龟 90% / 蜗牛龟 10%）',
    drops: ['蜗牛黏液 ×2', '蜗牛：破碎壳 ×2（90%），另有甲壳头盔（10%）', '蜗牛龟：甲壳头盔（25%）或 蜗牛壳铠甲（75%）'],
    note: '会缩进壳里反弹伤害，这时别硬打，等它伸出来再打。蜗牛黏液能种「蜗牛黏液灯」。' },

  /* ==================== 巨兽 / Boss（新增） ==================== */
  { id: 'eye_of_terror', cn: '恐惧之眼', en: 'Eye of Terror', img: 'mob_eye_of_terror.png', cat: 'boss',
    hp: 5000, dmg: '62.5（对玩家）/ 125（对生物）', speed: '4.5（走）/ 15 → 18.75（冲刺，随阶段）', sanity: -100,
    where: '「以眼还眼」事件：给「恐惧之眼养成缸（Terrarium）」灌入材料后激活，它会在夜晚现身并锁定一名玩家',
    drops: ['大肉 ×2-4', '乳白蛋白 ×3-5', '眼罩', '恐惧之眼手稿（雕像草图）'],
    note: '分两个阶段，二阶段冲刺更快，还会召唤「可疑窥视者」帮忙。天亮就逃，下一晚带着剩余血量回来。养成缸里先投 1 个噩梦燃料，刷出来的就是「恐惧双子」。' },
  { id: 'twins_of_terror', cn: '恐惧双子（视网膜 / 散光）', en: 'Twins of Terror', img: 'mob_twins_of_terror.png', cat: 'boss',
    hpText: '各 10000（合计 20000）', dmg: '125（对玩家）/ 250（对生物）', sanity: -100,
    where: '和恐惧之眼同一套召唤流程：养成缸里先投 1 个噩梦燃料，激活后刷出的就是这两只',
    drops: ['视网膜（Retinazor）：黄宝石 + 齿轮 ×3-5 + 焦电线 ×1-2 + 电子元件 ×2-3 + 噩梦燃料 ×2-4', '散光（Spazmatism）：绿宝石 + 同上一整套材料', '恐惧之盾 ×1（两只都击杀后）', '恐惧双子手稿（雕像草图）'],
    note: '必须在连续的几个夜晚分别打完——没打死的会带着剩余血量在下一晚回来，所以不能隔天重打。二阶段冲刺速度 22 / 25，非常难躲，靠冰冻 / 催眠控制住再输出最稳。' },
  { id: 'frostjaw', cn: '霜牙', en: 'Frostjaw', img: 'mob_frostjaw.png', cat: 'boss',
    hp: 8000, dmg: '37.5（对玩家）/ 75（对生物）', atk: 3, range: '8（远程）/ 4.5（近战）', speed: '2.3 / 8（钻地时 6）',
    where: '海洋的「冰面（Ice Sheet）」区域：在冰钓洞上钓鱼时会把它钓上来（钓鱼动静大了它也自己冒头）',
    drops: ['不通过击杀获得：打不动它，它会投降变成交易 NPC', '霜牙手稿（雕像草图，首次用重型海鱼交易时获得）'],
    note: '会钻到冰面下再从别处冒出来偷袭，远程吐息和近战两种攻击距离不同。它是少数「一边打一边换位置」的 Boss，站桩输出很容易被绕背。' },
  { id: 'great_depths_worm', cn: '巨大洞穴蠕虫', en: 'Great Depths Worm', img: 'mob_great_depths_worm.png', cat: 'boss', alias: ['巨大洞穴蠕虫'],
    hp: 5000, dmg: '32（冲击波，对玩家）/ 30（荆棘，对玩家）/ 560（吞噬，但不会直接杀死）', sanity: -400,
    where: '洞穴的「洞穴蠕虫袭击」事件：蠕虫潮出现时，它取代普通深渊蠕虫登场',
    drops: ['大肉 ×3-5', '发光浆果 ×1', '巨大洞穴蠕虫手稿（雕像草图）'],
    note: '攻击全靠「从地里冒出来」的范围冲击波，站得太密会被连着打。它的吞噬伤害高到 560，但设计上不会直接杀死玩家（会吐出来）。' },
  { id: 'nightmare_werepig', cn: '梦魇疯猪', en: 'Nightmare Werepig', img: 'mob_nightmare_werepig.png', cat: 'boss',
    hp: 10000, dmg: '12.5（零阶段）/ 75（冲撞）/ 112.5（重砸）', atk: '4-6', range: 6, speed: '2.7 / 9', sanity: -100,
    where: '洞穴的泥泞地形（像监狱一样的区域）；用「梦魇燃料」把他放出来就开打',
    drops: ['纯噩梦 ×4-5', '噩梦燃料 ×1', '梦魇疯猪手稿（雕像草图）', '恐惧石装备蓝图（头盔 / 护甲 / 墙）', '（砸掉所有碎裂石柱后）恐惧石柱脚手架蓝图'],
    note: '打之前会有一小段「被囚禁」状态，放出来才正式开战。零阶段反伤很低但会持续掉理智，二三阶段伤害陡增。掉落里的恐惧石护甲是后期很强的一套装备。' },
  { id: 'scrappy_werepig', cn: '拾荒疯猪', en: 'Scrappy Werepig', img: 'mob_scrappy_werepig.png', cat: 'boss', alias: ['拾荒疯猪'],
    hp: 10000, dmg: '112.5 / 150（激光）/ 100（护甲撞击）', atk: '3-4', range: '3 / 5（激光）/ 8（护甲）', sanity: -400,
    where: '击败梦魇疯猪 10 天后，在同一片区域出现',
    drops: ['废料 ×4', '地平线扩张器', '自动机械臂', '废料头盔（若打死时它还有护甲）', '拾荒疯猪手稿'],
    note: '三套攻击方式对应三种距离：贴脸是武器、中距离是激光、远距离是护甲撞击。它会捡地上的废料给自己装护甲，护甲状态下减伤明显——先破甲再打。' },
  { id: 'crystal_deerclops', cn: '晶体独眼巨鹿', en: 'Crystal Deerclops', img: 'mob_crystal_deerclops.png', cat: 'boss', alias: ['晶体独眼巨鹿', '水晶巨鹿'],
    hp: 6000, dmg: '75（对玩家）/ 150（对生物）', atk: '3 / 4（狂暴）', range: '5（近战）/ 6-14（水晶远程）',
    where: '「从彼岸（From Beyond）」剧情：瓦格斯塔夫任务线中，普通鹿角怪的尸体被水晶化的形态',
    drops: ['腐烂物 ×3-4', '冰块 ×1-2', '纯粹辉煌 ×1-2', '晶体独眼巨鹿手稿（雕像草图）', '星火方舟（空）（已击败天体后继者时改为成核液）'],
    note: '比普通鹿角怪多了一手远程水晶投射（6-14 距离），所以「打一走一」的节奏要拉得更长。属于剧情变种，不是每年冬天都会来的那只。' },
  { id: 'armored_bearger', cn: '装甲熊獾', en: 'Armored Bearger', img: 'mob_armored_bearger.png', cat: 'boss',
    hp: 8000, dmg: '87（对玩家）/ 175（对生物）', atk: 3, range: 6,
    where: '「从彼岸」剧情线里的熊獾变种，被暗影生物附身后的形态',
    drops: ['腐烂物 ×3-4', '纯粹辉煌 ×1-2', '装甲熊獾手稿（雕像草图）', '星火方舟（空）（已击败天体后继者时改为成核液）'],
    note: '比普通熊獾多了护甲减伤，正面硬拼很亏。它依旧会拆建筑、翻箱子找吃的，别在基地旁边打。' },
  { id: 'possessed_varg', cn: '被附身座狼', en: 'Possessed Varg', img: 'mob_possessed_varg.png', cat: 'boss', alias: ['附身座狼'],
    hp: 3000, dmg: '50（撕咬）/ 20（冷焰）',
    where: '「从彼岸」剧情线：座狼的尸体被附身后的形态',
    drops: ['腐烂物 ×2-3', '纯粹辉煌 ×1-2', '月亮碎片 ×3-6', '被附身座狼手稿（雕像草图）', '星火方舟（空）（已击败天体后继者时改为成核液）'],
    note: '血量不高（3000）但会喷冷焰，附带冰冻减速，被冻住之后很难拉开距离。三个「从彼岸」变种（晶体独眼巨鹿 / 装甲熊獾 / 被附身座狼）都要打完才能推进剧情。' },
  { id: 'shadow_pieces', cn: '暗影棋子（主教 / 骑士 / 战车）', en: 'Shadow Pieces', img: 'mob_shadow_pieces.png', cat: 'boss', alias: ['暗影骑士', '暗影主教', '暗影战车'],
    hpText: '按等级 900 / 2700 / 8100', dmg: '40 / 90 / 150', atk: '3 / 2.5 / 2', sanity: -100,
    where: '在棋盘地形把「暗影之心」放上发条生物的棋盘雕像，夜里会把它们激活成暗影棋子（等级 1→2→3 依次出现）',
    drops: ['Lv1：噩梦燃料 ×1-2', 'Lv2：噩梦燃料 ×3-5', 'Lv3：噩梦燃料 ×4-6 + 暗影护甲 + 暗影剑 + 暗影中庭'],
    note: '三级形态的棋子才掉暗影中庭——那是通往远古织影者的门票，所以想打最终 Boss 就得老老实实升到 Lv3。等级越高血量和伤害翻倍增长，建议装备成型再来。' },
  { id: 'fruit_fly', cn: '果蝇', en: 'Fruit Fly', img: 'mob_fruit_fly.png', cat: 'hostile',
    hp: 100, dmg: 5, atk: 2, range: 1, speed: 8, sanity: -10,
    where: '果蝇王召唤（每次最多 4 只）；采摘腐烂的农场作物也有 5% 概率刷出，收获腐烂的巨型作物会一次出 2 只',
    drops: ['种子（10%）'],
    note: '会在农田里种杂草、把作物惹毛，但不主动还手。果蝇王被击杀后它们会一起转成敌对。' },
  { id: 'lord_fruit_flies', cn: '果蝇王', en: 'Lord of the Fruit Flies', img: 'mob_lord_fruit_flies.png', cat: 'boss', alias: ['果蝇王'],
    hp: 1500, dmg: 25, atk: 2, range: 2, speed: 8, sanity: -25,
    where: '农田旁：作物腐烂 / 田地里害虫太多时会刷出来，主动清理田地',
    drops: ['友好果蝇果实', '叶肉', '植物种子（种子）×4-8'],
    note: '血量只有 1500，是很好对付的小 Boss。打败后会掉「友好果蝇果实」，种下能养出帮你照料农田的友好果蝇——所以它是农场流必须打的。' },
  { id: 'reanimated_skeleton', cn: '复活的骨架', en: 'Reanimated Skeleton', img: 'mob_reanimated_skeleton.png', cat: 'boss', alias: ['复活的骨架'],
    hp: 4000, speed: '2.4', sanity: -400,
    where: '用「暗影中庭」在骸骨上召唤；分森林 / 洞穴 / 远古三种形态，取决于召唤地点',
    drops: ['暗影中庭（在远古中庭形态下）', '化石 ×8'],
    note: '它是打远古织影者的前置：在远古中庭召唤并击败「远古形态」的复活的骨架，才会出现通往远古织影者的入口。血量不高但范围攻击很密。' },

  /* ==================== 敌对怪物（新增） ==================== */
  { id: 'shattered_spider', cn: '破碎蜘蛛', en: 'Shattered Spider', img: 'mob_shattered_spider.png', cat: 'hostile',
    hp: 250, dmg: '25（撕咬）/ 10（尖刺）', atk: 3, range: 7, speed: '3.75 / 6.25', sanity: -40,
    where: '月岛与岩石海滩的「破碎蜘蛛洞」里成群刷出（洞穴里的变种也来自蜘蛛巢）',
    drops: ['怪物肉 50%', '蜘蛛腺体 25%', '蛛丝 25%'],
    note: '比普通蜘蛛胖一圈，会远程吐尖刺，攻击距离 7 比普通蜘蛛远得多，硬冲容易被连着扎。在月岛打它要有被围的准备。' },
  { id: 'sea_strider', cn: '海步者', en: 'Sea Strider', img: 'mob_sea_strider.png', cat: 'hostile',
    hp: 200, dmg: 20, atk: 3, range: 2, speed: '陆地 3 / 海上 1.5（冲刺 10）',
    where: '「淹没（Waterlogged）」生物群系的树丛附近；陆地和浅水都能走',
    drops: ['怪物肉 50%', '蛛丝 25%', '蜘蛛腺体 25%'],
    note: '像蜘蛛一样会追人，但它在陆地和水里速度差很多——把它引到陆地上打会轻松很多。' },
  { id: 'horror_hound', cn: '恐怖猎犬', en: 'Horror Hound', img: 'mob_horror_hound.png', cat: 'hostile',
    hp: 100, dmg: 25, atk: 2.5, range: 3, speed: '10', sanity: -40,
    where: '月岛上普通猎犬死亡时 50% 概率变异而成（只在月岛区域）',
    drops: ['怪物肉', '犬牙 ×2'],
    note: '血量只有 100 但攻击间隔短、跑得快，成群出现时比普通猎犬难缠。在月岛刷猎犬波时要留意它们会临场变异。' },
  { id: 'briar_wolf', cn: '荆棘狼', en: 'Briar Wolf', img: 'mob_briar_wolf.png', cat: 'hostile',
    hp: 50, dmg: 10, atk: 2,
    where: '影缝（Shadow Rift）开启后，从地图上的「荆棘（briar）」里钻出来',
    drops: ['各种面具与服装（玩偶 / 铁匠 / 国王 / 王后 / 愚者 / 树 / 镜子…，见掉落表）'],
    note: '血量极低（50）但数量多，成群扑上来。掉落的是「戏剧」主题的面具与服饰，属于收集向掉落。' },
  { id: 'varglet', cn: '小座狼', en: 'Varglet', img: 'mob_varglet.png', cat: 'hostile',
    hp: 600, dmg: 40, atk: 2, range: 4, speed: '10',
    where: '生存 25 天之后的猎犬潮里，会混着小座狼一起进攻',
    drops: ['怪物肉 ×3-4', '犬牙 ×1-2'],
    note: '它会一边冲一边继续召唤猎犬，所以拖得越久场上猎犬越多。优先集火它，别先清小怪。' },
  { id: 'misshapen_bird', cn: '奇形鸟', en: 'Misshapen Bird', img: 'mob_misshapen_bird.png', cat: 'hostile', alias: ['奇形鸟'],
    hp: 10, dmg: 20, atk: 6, range: 2, speed: '4', sanity: -25,
    where: '「暴风之眼（Eye of the Storm）」事件期间，在海面 / 岸边的鸟群里出现',
    drops: ['无掉落'],
    note: '血量只有 10，一刀就死，但会远程吐东西砸人，攻击间隔 6 秒。属于事件期的小骚扰怪。' },
  { id: 'rockjaw', cn: '岩石大白鲨', en: 'Rockjaw', img: 'mob_rockjaw.png', cat: 'hostile', alias: ['岩石大白鲨'],
    hp: 1000, dmg: '20 ×4（范围撕咬）', range: 4, speed: '1 / 7',
    where: '破碎海域（Rough）与中等海域（Swell）每次鱼群出现时，都有机会刷出一条来撞船',
    drops: ['鱼（大鱼肉）×4'],
    note: '它主要的目标是船：会反复撞击船体。船上没有武器位，通常靠海钓竿或直接跳船硬碰。' },
  { id: 'depths_worm', cn: '深渊蠕虫', en: 'Depths Worm', img: 'mob_depths_worm.png', cat: 'hostile',
    hp: 900, dmg: 75, atk: 4, range: 3, sanity: -25,
    where: '洞穴的「荒野」地形埋伏，也会随周期性的洞穴蠕虫袭击成队冲出来',
    drops: ['怪物肉 ×4', '发光浆果 ×1'],
    note: '平时伪装成地面上的小土包，走过去才会冒出来咬人。攻击间隔 4 秒、伤害 75，硬吃两口就很危险。发光浆果就是它掉的食物。' },
  { id: 'gestalt', cn: '格斯特（月魂）', en: 'Gestalt', img: 'mob_gestalt.png', cat: 'hostile',
    hpText: '无法被攻击', dmg: 10, range: 2.5, speed: '1.5', sanity: '+40',
    where: '月岛、月亮洞穴，以及天体类 Boss 召唤出来时',
    drops: ['无（不可击杀）'],
    note: '它不能被攻击，靠近只会对你造成少量伤害；身上会持续回理智（+40/分）。当「启发值」过高时，它会让你睡着——所以在月岛待久了会莫名其妙倒下。' },
  { id: 'fused_shadeling', cn: '熔合暗影', en: 'Fused Shadeling', img: 'mob_fused_shadeling.png', cat: 'hostile', alias: ['熔合暗影'],
    hp: 1250, dmg: 40, atk: 2.5, range: 2, speed: '4', sanity: -40,
    where: '影缝开启时从影缝里刷出',
    drops: ['纯粹恐惧 ×2-4'],
    note: '影缝阶段的主力怪，血量 1250、伤害 40（还带 10 点位面伤害），几只一起上很吃亏。它是「纯粹恐惧」的稳定来源；死后会留下一个会追人的「绝望螨」，几秒后自爆，记得先跑开。' },
  { id: 'lurking_nightmare', cn: '潜伏梦魇', en: 'Lurking Nightmare', img: 'mob_lurking_nightmare.png', cat: 'hostile',
    hp: 850, dmg: 50, atk: 1.5, range: 3.5, speed: '5（影缝期 6）', sanity: -100,
    where: '噩梦期从噩梦裂隙中现身；影缝开启后出现得更频繁',
    drops: ['噩梦燃料 ×2-4', '（影缝期额外）纯噩梦 ×2-3'],
    note: '攻击间隔只有 1.5 秒，是暗影系里节奏最快的之一，很难靠走位躲。理智低于阈值时它会成群出现。' },
  { id: 'terrorclaw', cn: '恐惧之爪', en: 'Terrorclaw', img: 'mob_terrorclaw.png', cat: 'hostile',
    hp: 400, dmg: 50, atk: 3, range: 4.1, speed: '2', sanity: -100,
    where: '理智过低时，在海上（以及部分地表）代替尖牙梦魇 / 爬行梦魇出现',
    drops: ['噩梦燃料 ×1-2'],
    note: '它是尖牙梦魇的「海上版」，攻击距离 4.1 比看起来远，近战武器够不到它的时候要贴上去。' },
  { id: 'dread_mite', cn: '绝望螨', en: 'Dread Mite', img: 'mob_dread_mite.png', cat: 'hostile',
    hp: null, hpText: '无法击杀', dmg: '50 + 20 位面（爆炸）', speed: 12,
    where: '熔合暗影死亡后，它掉在地上的尾巴会变成绝望螨追着你跑',
    drops: ['（无掉落；自爆后还会分裂出 3 个立刻引爆的小球）'],
    note: '追你 4 秒后自爆，爆炸范围不大但伤害很高，而且会再炸出 3 个小球。要么跑远，要么提前用范围攻击清掉尾巴。' },
  { id: 'parasitic_shadeling', cn: '寄生暗影', en: 'Parasitic Shadeling', img: 'mob_parasitic_shadeling.png', cat: 'hostile',
    hp: 100, atk: null, speed: '6', sanity: -40,
    where: '与梦魇疯猪的战斗开始后，会刷出 3 只来骚扰他',
    drops: ['噩梦燃料 ×1'],
    note: '血量只有 100，但它会缠着梦魇疯猪吸食，间接延长战斗。清掉它们能让整场战斗快不少。' },
  { id: 'mimicreep', cn: '拟态蠕虫', en: 'Mimicreep', img: 'mob_mimicreep.png', cat: 'hostile', alias: ['拟态藤'],
    hp: 100, speed: '6', sanity: -10,
    where: '影缝开启期间，洞穴里的夜晚出现在地上，伪装成一件掉落物',
    drops: ['噩梦燃料 ×1'],
    note: '会伪装成地上的物品，你去捡就咬你一口。看到「会自己动的掉落物」直接打。' },
  { id: 'shadow_merm', cn: '暗影鱼人', en: 'Shadow Merm', img: 'mob_shadow_merm.png', cat: 'hostile',
    hp: 500, dmg: '30（鱼人王在场时 40）',
    where: '只有沃特点出「暗影鱼人」相关技能后，忠诚的鱼人死亡时才会留下暗影鱼人',
    drops: ['噩梦燃料 ×1'],
    note: '属于沃特的角色专属内容：她的鱼人死掉后会变成暗影鱼人继续帮打一会儿。' },
  { id: 'loyal_merm_guard', cn: '忠诚鱼人守卫', en: 'Loyal Merm Guard', img: 'mob_loyal_merm_guard.png', cat: 'hostile',
    hp: 200, hpText: '200（鱼人王在场时 660）', dmg: '20（鱼人王在场时 50）', atk: 3, speed: '3 / 8',
    where: '沃特的「鱼人堡垒」里刷出，前提是鱼人王还活着',
    drops: ['鱼（淡水鱼）', '青蛙腿'],
    note: '鱼人王在场时血量和伤害都翻三倍，所以打鱼人村之前最好先确认有没有王。敌对玩家阵营，对沃特以外的角色一律开打。' },
  { id: 'mutated_merm', cn: '变异鱼人', en: 'Mutated Merm', img: 'mob_mutated_merm.png', cat: 'hostile',
    hp: 540, dmg: '30（鱼人王在场 40）/ 40（尖刺）',
    where: '由沃特的技能、或尸体变异条件产生；「水晶冠拟声鸟」也会催生',
    drops: ['鱼 ×1', '蛙腿 ×1', '触手皮 25%'],
    note: '变异后血量翻倍还多，且会带尖刺攻击。属于后期鱼人阵营的强化版。' },
  { id: 'powder_monkey', cn: '火药猴', en: 'Powder Monkey', img: 'mob_powder_monkey.png', cat: 'hostile',
    hp: 200, dmg: '20（赤手；拿到武器后更高）', speed: '7',
    where: '月港（猴岛）的码头上，从猴子小屋里刷出；也会成群出现抢东西',
    drops: ['小肉', '诅咒饰品'],
    note: '月港的主要麻烦制造者：会偷东西、会开炮台打你，还会把船上的物品抢走。想上岛搜刮先清码头。' },
  { id: 'damaged_clockwork', cn: '破损发条生物（骑士 / 主教 / 战车）', en: 'Damaged Clockwork', img: 'mob_damaged_clockwork.png', cat: 'hostile',
    hp: 900, dmg: '40（主教为电击伤害；战车冲撞 90）', atk: '2（主教 4）', speed: '5',
    where: '远古遗迹（军事区 / 圣地 / 迷宫一带）成片分布，身上沾着噩梦燃料',
    drops: ['齿轮 ×1', '噩梦燃料 60%', '铥矿碎片 50%'],
    note: '基础数值和普通发条生物一样，但掉噩梦燃料和铥矿碎片——在遗迹里是「顺手刷材料」的好目标。' },
  { id: 'gilded_knight', cn: '镀金骑士', en: 'Gilded Knight', img: 'mob_gilded_knight.png', cat: 'hostile',
    hp: 900, dmg: 40, speed: '5',
    where: '春节期间：玩家同时戴上「公主面具 + 公主服装」时，每 3 天会出现一只；靠近假人模特也会触发',
    drops: ['齿轮 ×2', '幸运马蹄铁 10%', '冲锋骑枪 ×25%', '（最后一只额外）镀金骑士头盔 + 镀金骑士胸甲'],
    note: '活动限定敌人，掉落的「镀金骑士头盔 / 胸甲」是春节活动套装。它和普通发条骑士打法一样，只是外观与掉落不同。' },
  { id: 'wavey_jones', cn: '波浪琼斯', en: 'Wavey Jones', img: 'mob_wavey_jones.png', cat: 'hostile',
    sanity: -40,
    where: '海上理智过低时，代替陆地上的「夜之手」出现在船上 / 海面',
    drops: ['无（它会拆船而不是打人）'],
    note: '它不直接攻击你，而是搞破坏：把桅杆和锚收起来、拆掉船的补丁、把火扑灭。理智低的时候出海会被它整得很惨。' },
  { id: 'permafrost_pengull', cn: '永冻企鹅', en: 'Permafrost Pengull', img: 'mob_permafrost_pengull.png', cat: 'hostile',
    hp: 100, dmg: 20, atk: 3, speed: '0.75',
    where: '月岛上的冬天：普通企鹅群在月岛区域会变成敌对的永冻企鹅',
    drops: ['怪物肉 25%', '冰块 50%'],
    note: '和普通企鹅不同，它们见人就打。冬天在月岛要格外小心成群的永冻企鹅。' },
  { id: 'nurse_spider', cn: '护士蜘蛛', en: 'Nurse Spider', img: 'mob_nurse_spider.png', cat: 'hostile',
    hp: 400, dmg: 10, atk: 3,
    where: '蜘蛛巢升级到 3 级后，与蜘蛛战士一起刷出',
    drops: ['怪物肉 50%', '蛛丝 25%', '蜘蛛腺体 25%'],
    note: '它的作用是给其他蜘蛛回血，伤害只有 10。打蜘蛛巢时优先集火它，不然其他蜘蛛会越打越难死。' },

  /* ==================== 中立生物（新增） ==================== */
  { id: 'wee_mactusk', cn: '小海象', en: 'Wee MacTusk', img: 'mob_wee_mactusk.png', cat: 'neutral',
    hp: 100, speed: '3 / 5',
    where: '和爸爸一起从海象营地刷出（冬天）；白天活动，黄昏回冰屋',
    drops: ['无掉落'],
    note: '它自己不造成任何伤害，只会指挥两只冰猎犬、并在一旁跑来跑去，你靠近它就逃。官方把它归为「攻击性生物」，但按实际行为更像中立——真正会拿吹箭打你的是它爸（海象）。' },
  { id: 'teenbird', cn: '青年高鸟', en: 'Teenbird', img: 'mob_teenbird.png', cat: 'neutral',
    hp: 600, dmg: '37.5（啄击 2）', atk: '2（啄击 4）', range: 3, speed: '6',
    where: '由玩家喂养长大的「小高鸟」经过 18 天成长而来',
    drops: ['大肉 ×2'],
    note: '小时候（小高鸟）会跟着你，长成青年高鸟后就开始自己捕食小鸟，也不再跟着你了。你攻击它才会反击。' },
  { id: 'bunnyman', cn: '兔人', en: 'Bunnyman', img: 'mob_bunnyman.png', cat: 'neutral',
    hp: 200, dmg: 40, atk: 2, range: 3, speed: '3 / 6', sanity: +25,
    where: '洞穴的兔人屋（Rabbit Hutch）附近，蘑菇树林地形最常见',
    drops: ['胡萝卜 37.5%', '大肉 37.5%', '兔毛球 25%'],
    note: '和猪人一样会主动攻击怪物（蜘蛛、猎犬等），是洞穴里很好用的保镖；但如果你身上带着肉，它们会翻脸打你。站在旁边回理智 +25/分。' },
  { id: 'splumonkey', cn: '弹跳猴（洞穴猴）', en: 'Splumonkey', img: 'mob_splumonkey.png', cat: 'neutral',
    hp: 125, dmg: 20, atk: 2, range: 3, speed: '7',
    where: '远古遗迹的村庄地形，成群的弹跳猴',
    drops: ['小肉', '洞穴香蕉', '（噩梦期变为暗影猴）胡须 + 小肉 + 洞穴香蕉 + 噩梦燃料 50%', '被它偷走的东西'],
    note: '会抢走你放在地上的物品，打死它就能把东西拿回来。遗迹进入噩梦期时它们会变成暗影猴并主动攻击，这是遗迹里最烦人的一段。' },
  { id: 'volt_goat', cn: '伏特羊', en: 'Volt Goat', img: 'mob_volt_goat.png', cat: 'neutral',
    hp: 700, dmg: '25（带电时也是电击伤害）', atk: 2, range: 3, speed: '4 / 8',
    where: '绿洲沙漠（Oasis Desert）专属，成群活动',
    drops: ['大肉 ×2', '伏特羊角 25%', '（带电时）电牛奶 ×1'],
    note: '本身会躲着玩家跑，但领地意识很强，被打就反击。它会吸引闪电把自己充能带电——带电状态下被打死会掉电牛奶，是做冰淇淋的材料。' },
  { id: 'pengull', cn: '企鹅', en: 'Pengull', img: 'mob_pengull.png', cat: 'neutral',
    hp: 150, dmg: 33, atk: 3, range: 2.5, speed: '0.75',
    where: '冬季从海里跳上岸，成群约 7 只，越到冬末群体越大',
    drops: ['漆黑羽毛（20%）', '大肉（50%）或小肉（10%）', '（有藏蛋时）鸟蛋'],
    note: '企鹅只以 20% 概率掉漆黑羽毛；羽毛并非必掉。它们会在岸边筑巢下蛋，冬天可趁离巢时捡蛋。' },
  { id: 'cookie_cutter', cn: '饼干切割机', en: 'Cookie Cutter', img: 'mob_cookie_cutter.png', cat: 'neutral', alias: ['饼干切割机'],
    hp: 100, dmg: 20, atk: 2.5, range: 3, speed: '2',
    where: '海洋里围绕「盐岩层」活动，成小组出现',
    drops: ['怪物肉 ×1', '饼干壳（50% 掉 1 个，额外 25% 再掉 1 个）'],
    note: '在盐岩层附近活动，会主动靠近船只并试图钻出漏水孔；对玩家通常保持中立，遭攻击时才反击。击杀可获得饼干切割机壳。' },
  { id: 'skittersquid', cn: '鱿鱼', en: 'Skittersquid', img: 'mob_skittersquid.png', cat: 'neutral',
    hp: 170, dmg: 6.67, atk: 4, range: 2, speed: '4 / 6（游动 4）',
    where: '海洋里跟随鱼群出现，玩家钩到鱼时也常被吸引过来',
    drops: ['怪物肉', '灯泡 100%'],
    note: '伤害很低（6.67），但会成群围上来骚扰钓鱼。它 100% 掉灯泡，算是个顺手的照明材料来源。' },
  { id: 'saladmander', cn: '沙拉曼达', en: 'Saladmander', img: 'mob_saladmander.png', cat: 'neutral',
    hp: 900, atk: 2, range: 2, speed: '0.5 / 2',
    where: '月岛的月浴场地形',
    drops: ['叶肉（普通）', '火龙果（成熟状态）'],
    note: '移动极慢、血量很高，平时不会主动打人。成熟状态的沙拉曼达被打死后掉火龙果——月岛上拿火龙果最方便的方式。' },
  { id: 'gnarwail', cn: '一角鲸', en: 'Gnarwail', img: 'mob_gnarwail.png', cat: 'neutral', alias: ['一角鲸'],
    hp: 1000, dmg: 50, speed: '1.875 / 5（俯冲 10）',
    where: '破碎海域与中等海域，每次鱼群在附近出现时有机会刷出',
    drops: ['鱼 ×4', '一角鲸角'],
    note: '平时浮在水面不动，被攻击才会还手，伤害 50 不低。它的角是很值钱的材料，但打之前先想好怎么对付它的俯冲。' },
  { id: 'king_of_merms', cn: '鱼人王', en: 'King of the Merms', img: 'mob_king_of_merms.png', cat: 'neutral',
    hp: 1000, hpText: '1000',
    where: '沃特角色内容：让鱼人在「皇家挂毯」上累积 50 点，就会诞生鱼人王',
    drops: ['鱼（淡水鱼）', '青蛙腿', '海带叶 ×4'],
    note: '他不会主动攻击，是鱼人阵营的「国王」：在场时所有鱼人守卫血量与伤害 ×3，还提供交易。对沃特而言是最重要的 npc。' },

  { id: 'butterfly', cn: '蝴蝶', en: 'Butterfly', img: 'mob_butterfly.png', cat: 'passive',
    hp: 1, dmg: '—', speed: '5',
    where: '草原地形常见，从花朵（包括邪恶花）里刷出；冬天与洞穴里不会有',
    drops: ['蝴蝶翅膀 98%', '黄油 2%'],
    note: '用捕虫网抓可以变成物品，种花、喂蜜蜂箱都用得上。打死它会掉蝴蝶翅膀（做蝴蝶松饼）——但捕虫网抓不算「杀生」，用武器打会累计罪恶值。它在花上停留的几秒是最好的下刀时机。' },
  { id: 'moon_moth', cn: '月蛾', en: 'Moon Moth', img: 'mob_moon_moth.png', cat: 'passive', alias: ['月蛾'],
    hp: 1,
    where: '月岛的月森林，砍月树时会飞出来',
    drops: ['月蛾翅膀'],
    note: '完全无害，被击杀后掉月蛾翅膀（下锅能做蝴蝶松饼，和蝴蝶翅膀等价）。砍月树时顺手收几只就行。' },
  { id: 'lightbug', cn: '球状光虫', en: 'Bulbous Lightbug', img: 'mob_lightbug.png', cat: 'passive', alias: ['灯泡虫'], 
    hp: 25,
    where: '月亮洞窟中带有球状光虫巢穴特征的荧光花附近',
    drops: ['击杀掉落荧光果 ×1', '捕虫网捕获：获得球状光虫物品 ×1'],
    note: '自然生成的球状光虫被击杀会掉 1 个荧光果；用捕虫网捕获则获得球状光虫物品，并可随身携带照明。沃姆伍德技能召唤的光虫是另一种情况：消失或被击杀时转回荧光果。' },
  { id: 'pipspook', cn: '啜泣幽魂', en: 'Pipspook', img: 'mob_pipspook.png', cat: 'passive',
    sanity: -40, speed: '2 / 6',
    where: '墓地（墓碑）附近，每天 5% 概率刷出，附近已有同类则不再刷',
    drops: ['哀悼花'],
    note: '温蒂以外的角色靠近会掉理智（温蒂不受影响）。帮它找回遗失的玩具能拿到「哀悼花」，是温蒂做阿比盖尔升级的材料。' },
  { id: 'no_eyed_deer', cn: '无眼鹿', en: 'No-Eyed Deer', img: 'mob_no_eyed_deer.png', cat: 'passive',
    hp: 700, dmg: 25, atk: 2, speed: '2.5 / 8',
    where: '秋季开始时在落叶林附近刷出，是季节性的被动生物',
    drops: ['大肉 ×1-2', '碎骨 ×1-2（只在有角个体上）', '撞树掉落的鹿角（A / B / C 三种中随机一种）'],
    note: '平时不会攻击，但玩家打它才会反击。有角个体撞树会撞下「鹿角」，那是做「透明角」相关道具的材料。' },
  { id: 'dust_moth', cn: '尘蛾', en: 'Dust Moth', img: 'mob_dust_moth.png', cat: 'passive',
    hp: 200,
    where: '远古档案馆（月亮洞穴深处）',
    drops: ['小肉 ×1'],
    note: '喂它「琥珀糖」后，它会把附近的整理洞变成可开采的铥矿碎片——这是不靠打 Boss 也能稳定拿铥矿的路线。' },
  { id: 'canary', cn: '金丝雀', en: 'Canary', img: 'mob_canary.png', cat: 'passive',
    hp: 25,
    where: '在「友好的稻草人」附近代替乌鸦出现；也可在地下鸟笼中暴露于蘑菇孢子而中毒',
    drops: ['普通金丝雀：小肉或藏红花羽毛（9%）', '中毒金丝雀在地表放生：藏红花羽毛 ×5–6', '中毒金丝雀在洞穴放生爆炸：藏红花羽毛 ×1–2'],
    note: '普通金丝雀被击杀或谋杀时，有 9% 概率掉藏红花羽毛；将其放入洞穴鸟笼中中毒后带回地表放生，可稳定获得 5–6 根羽毛。中毒金丝雀在洞穴放生会爆炸并掉 1–2 根；谋杀中毒金丝雀则只掉腐烂物。' },
  { id: 'puffin', cn: '海鹦鹉', en: 'Puffin', img: 'mob_puffin.png', cat: 'passive', alias: ['海鹦鹉'],
    hp: 25,
    where: '海洋上出现，通常在海面游动或靠近船只',
    drops: ['小肉（50%）或漆黑羽毛（50%）'],
    note: '海鹦鹉的普通羽毛掉落为漆黑羽毛；掉落是二选一，并非同时获得小肉和羽毛。' },
  { id: 'bright_beaked_bird', cn: '亮喙鸟', en: 'Bright-Beaked Bird', img: 'mob_bright_beaked_bird.png', cat: 'passive',
    hp: 10, dmg: 20, sanity: -25,
    where: '月雹期间或之后由死鸟 / 普通鸟发生月亮变异；裂隙阶段会影响出现形态',
    drops: ['被谋杀或击杀：腐烂物 ×1', '啄除月雹覆盖物：月亮碎片或灌注月亮碎片 ×1–3'],
    note: '亮喙鸟是月亮变异鸟，不是普通鸟种。被捕获后谋杀掉腐烂物；也会啄除物体上的月雹覆盖，掉落月亮碎片或灌注月亮碎片。' },
  { id: 'moonblind_crow', cn: '月盲乌鸦', en: 'Moonblind Crow', img: 'mob_moonblind_crow.png', cat: 'passive', alias: ['月盲乌鸦'],
    hp: 10, dmg: 20, atk: 6,
    where: '月暴期间与奇形鸟群一同出现；也可用月亮实验使鸟发生变异',
    drops: ['被谋杀：腐烂物 ×1', '鸟笼中喂食：可能产腐烂物或腐烂蛋'],
    note: '月盲乌鸦是敌对的月亮变异鸟，可用捕鸟陷阱捕获；在背包中谋杀会掉 1 个腐烂物。鸟笼内喂食时也有不同于普通鸟的产物。' },
  { id: 'wobster', cn: '龙虾', en: 'Wobster', img: 'mob_wobster.png', cat: 'passive',
    hp: 25,
    where: '海洋底层与岩石海滩附近，用龙虾笼 / 海钓竿捕捉',
    drops: ['龙虾（活体，可烤成「美味龙虾」或放进锅里）'],
    note: '别和「石龙虾」搞混——石龙虾是洞穴里的矿石生物（2250 血、会打人），龙虾只是海鲜。活龙虾不能直接吃，要先烤熟或下锅。' },

  /* ---- 海洋鱼类（Return of Them，18 种）----
     统一说明：都是被动生物，只能钓 / 海捞 / 用三叉戟震出来；宰杀后按种类掉小鱼块或生鱼。
     放在「鱼箱（Tin Fishin' Bin）」里不会腐烂；放在背包里 1 天就会腐烂。 */
  { id: 'fish_runty_guppy', cn: '小孔雀鱼', en: 'Runty Guppy', img: 'mob_fish_runty_guppy.png', cat: 'passive', alias: ['小孔雀鱼'],
    hp: 1, hpText: '1（无害）', dmg: '—',
    where: '海岸海域与中等海域，不常见（uncommon）',
    drops: ['宰杀 → 小鱼块 ×1', '下锅算 0.5 肉度 + 0.5 鱼度', '食用 12.5 饥饿 / 1 生命 / 0 理智，保质 1 天'],
    note: '钓鱼时它会先挣扎几下，然后慢慢游过来——是最好上钩的一种。' },
  { id: 'fish_needlenosed', cn: '针鼻喷墨鱼', en: 'Needlenosed Squirt', img: 'mob_fish_needlenosed.png', cat: 'passive', alias: ['针鼻喷墨鱼'],
    hp: 1, hpText: '1（无害）', dmg: '—',
    where: '海岸海域，常见（common）',
    drops: ['宰杀 → 小鱼块 ×1', '下锅算 0.5 肉度 + 0.5 鱼度', '食用 12.5 饥饿 / 1 生命 / 0 理智，保质 1 天'],
    note: '咬钩后窜得很快，会连续短冲，手要稳。' },
  { id: 'fish_bitty_baitfish', cn: '小饵鱼', en: 'Bitty Baitfish', img: 'mob_fish_bitty_baitfish.png', cat: 'passive',
    hp: 1, hpText: '1（无害）', dmg: '—',
    where: '海岸、中等与破碎海域，稀有（rare）',
    drops: ['宰杀 → 小鱼块 ×1', '下锅算 0.5 肉度 + 0.5 鱼度', '食用 12.5 饥饿 / 1 生命 / 0 理智，保质 1 天'],
    note: '只吃水里的肉类诱饵。移动方式是长距离冲刺，耐力消耗低。' },
  { id: 'fish_smolt_fry', cn: '三文鱼苗', en: 'Smolt Fry', img: 'mob_fish_smolt_fry.png', cat: 'passive', alias: ['三文鱼苗'],
    hp: 1, hpText: '1（无害）', dmg: '—',
    where: '海岸海域，非常常见（very common）',
    drops: ['宰杀 → 小鱼块 ×1', '下锅算 0.5 肉度 + 0.5 鱼度', '食用 12.5 饥饿 / 1 生命 / 0 理智，保质 1 天'],
    note: '全游戏最容易钓到的一种，新手练手鱼。' },
  { id: 'fish_popperfish', cn: '爆米花鱼', en: 'Popperfish', img: 'mob_fish_popperfish.png', cat: 'passive', alias: ['爆米花鱼'],
    hp: 3, hpText: '3（无害）', dmg: '—',
    where: '海岸海域，常见（common）',
    drops: ['宰杀 / 烤 → 爆米花', '下锅算 1 爆米花', '食用 12.5 饥饿 / 3 生命 / 0 理智，保质 1 天'],
    note: '唯一会直接给你「爆米花」的鱼——省了一次火烤。' },
  { id: 'fish_fallounder', cn: '落叶比目鱼', en: 'Fallounder', img: 'mob_fish_fallounder.png', cat: 'passive', alias: ['落叶比目鱼'],
    hp: 1, hpText: '1（无害）', dmg: '—',
    where: '中等海域与「淹没」水域，只在秋季出现（common）',
    drops: ['宰杀 → 叶肉 ×1', '下锅算 0.5 肉度 + 0.5 鱼度', '食用 12.5 饥饿 / 0 生命 / 0 理智，保质 1 天'],
    note: '四季鱼之一：过了秋天就钓不到了。它掉叶肉，是少数不靠月岛就能拿叶肉的途径。' },
  { id: 'fish_bloomfin_tuna', cn: '花朵金枪鱼', en: 'Bloomfin Tuna', img: 'mob_fish_bloomfin_tuna.png', cat: 'passive', alias: ['花朵金枪鱼'],
    hp: 1, hpText: '1（无害）', dmg: '—',
    where: '海岸海域与「淹没」水域，只在春季出现（common）',
    drops: ['宰杀 → 叶肉 ×1', '下锅算 0.5 肉度 + 0.5 鱼度', '食用 12.5 饥饿 / 0 生命 / 0 理智，保质 1 天'],
    note: '四季鱼之一：春季限定。每年春天想囤叶肉就靠它和落叶比目鱼。' },
  { id: 'fish_scorching_sunfish', cn: '炽热太阳鱼', en: 'Scorching Sunfish', img: 'mob_fish_scorching_sunfish.png', cat: 'passive', alias: ['炽热太阳鱼'],
    hp: 1, hpText: '1（无害）', dmg: '—',
    where: '中等海域，只在夏季出现（uncommon）',
    drops: ['宰杀 → 熟小鱼块（已经烤好的）', '下锅算 0.5 肉度 + 0.5 鱼度', '食用 12.5 饥饿 / 1 生命 / 0 理智，保质 1 天'],
    note: '四季鱼之一：夏季限定。它是唯一「钓上来就是熟的」的鱼（掉熟小鱼块）。' },
  { id: 'fish_spittlefish', cn: '口水鱼', en: 'Spittlefish', img: 'mob_fish_spittlefish.png', cat: 'passive', alias: ['口水鱼'],
    hp: 1, hpText: '1（无害）', dmg: '—',
    where: '只出现在海草（Sea Weed）附近；海草喷出花粉云、附近又没有别的鱼时，会冒出一条',
    drops: ['宰杀 → 小鱼块 ×1', '下锅算 0.5 肉度 + 0.5 鱼度', '食用 12.5 饥饿 / 1 生命 / 0 理智，保质 1 天'],
    note: '会探测附近的火并喷水把火扑灭——想在海草附近生火要留意它。吃水里漂浮的蔬菜。' },
  { id: 'fish_mudfish', cn: '泥鱼', en: 'Mudfish', img: 'mob_fish_mudfish.png', cat: 'passive',
    hp: 8, hpText: '8（无害）', dmg: '—',
    where: '中等海域（海岸也有但少见），常见',
    drops: ['宰杀 → 生鱼 ×1', '下锅算 1 肉度 + 1 鱼度', '食用 25 饥饿 / 8 生命 / 0 理智，保质 1 天'],
    note: '中等体型的鱼，直接掉「生鱼」而不是小鱼块——性价比比小型鱼高。' },
  { id: 'fish_deep_bass', cn: '斑鱼', en: 'Deep Bass', img: 'mob_fish_deep_bass.png', cat: 'passive', alias: ['斑鱼'],
    hp: 8, hpText: '8（无害）', dmg: '—',
    where: '中等海域（破碎海域少见），常见',
    drops: ['宰杀 → 生鱼 ×1', '下锅算 1 肉度 + 1 鱼度', '食用 25 饥饿 / 8 生命 / 0 理智，保质 1 天'],
    note: '中等体型。岩石大白鲨的掉落里也偶尔能开出一条。' },
  { id: 'fish_dandy_lionfish', cn: '浮夸狮子鱼', en: 'Dandy Lionfish', img: 'mob_fish_dandy_lionfish.png', cat: 'passive', alias: ['浮夸狮子鱼'],
    hp: 8, hpText: '8（无害）', dmg: '—',
    where: '危险海域（Hazardous Ocean，破碎海域少见），非常常见',
    drops: ['宰杀 → 生鱼 ×1', '下锅算 1 肉度 + 1 鱼度', '食用 25 饥饿 / 8 生命 / 0 理智，保质 1 天'],
    note: '危险海域里数量最多的一种，去危险海域捞鱼基本一钓就是它。' },
  { id: 'fish_black_catfish', cn: '黑鲶鱼', en: 'Black Catfish', img: 'mob_fish_black_catfish.png', cat: 'passive',
    hp: 8, hpText: '8（无害）', dmg: '—',
    where: '破碎海域（中等海域少见），常见',
    drops: ['宰杀 → 生鱼 ×1', '下锅算 1 肉度 + 1 鱼度', '食用 25 饥饿 / 8 生命 / 0 理智，保质 1 天'],
    note: '破碎海域的常见中型鱼。' },
  { id: 'fish_corn_cod', cn: '玉米鳕鱼', en: 'Corn Cod', img: 'mob_fish_corn_cod.png', cat: 'passive', alias: ['玉米鳕鱼'],
    hp: 3, hpText: '3（无害）', dmg: '—',
    where: '中等海域（破碎海域少见），常见',
    drops: ['宰杀 → 玉米 ×1', '烤过 → 爆米花', '下锅算 1 玉米', '食用 25 饥饿 / 3 生命 / 0 理智，保质 1 天'],
    note: '会直接掉玉米——不用种农场就能拿到玉米的途径之一。' },
  { id: 'fish_dappled_koi', cn: '花锦鲤', en: 'Dappled Koi', img: 'mob_fish_dappled_koi.png', cat: 'passive', alias: ['花锦鲤'],
    hp: 8, hpText: '8（无害）', dmg: '—',
    where: '新年活动专属的中型鱼，在海岸 / 中等海域不常见',
    drops: ['宰杀 → 生鱼 ×1', '下锅算 1 肉度 + 1 鱼度', '食用 25 饥饿 / 8 生命 / 0 理智，保质 1 天'],
    note: '只在春节活动期间出现，属于节日限定鱼。' },
  { id: 'fish_golden_koi', cn: '金锦鲤', en: 'Golden Koi', img: 'mob_fish_golden_koi.png', cat: 'passive', alias: ['黄金锦鲤'],
    hp: 8, hpText: '8（无害）', dmg: '—',
    where: '新年活动专属的中型鱼，在海岸 / 中等海域不常见',
    drops: ['宰杀 → 生鱼 ×1', '下锅算 1 肉度 + 1 鱼度', '食用 25 饥饿 / 8 生命 / 0 理智，保质 1 天'],
    note: '和花锦鲤同属春节活动限定，颜色更亮，属于收集向。' },
  { id: 'fish_ice_bream', cn: '冰鲷鱼', en: 'Ice Bream', img: 'mob_fish_ice_bream.png', cat: 'passive', alias: ['冰鲷鱼'],
    hp: 8, hpText: '8（无害）', dmg: '—',
    where: '中等海域，只在冬季出现（uncommon）',
    drops: ['宰杀 → 生鱼 ×1', '下锅算 1 肉度 + 1 鱼度 + 1 冰度', '食用 25 饥饿 / 8 生命 / 0 理智，保质 1 天'],
    note: '四季鱼之一：冬季限定。它是唯一带「冰度」的鱼，下锅能顶冰块用。' },
  { id: 'fish_sweetish', cn: '甜味鱼', en: 'Sweetish Fish', img: 'mob_fish_sweetish.png', cat: 'passive', alias: ['甜味鱼'],
    hp: 8, hpText: '8（无害）', dmg: '—',
    where: '海洋里（「淹没」更新加入的中型鱼）',
    drops: ['宰杀 → 生鱼 ×1', '下锅算 1 肉度 + 1 鱼度', '食用 25 饥饿 / 8 生命 / 0 理智，保质 1 天'],
    note: '它吃浆果类食物，所以用浆果做饵更好钓。' },

  /* ==================== 补充：低理智 / 月后（裂隙）内容 ==================== */
  { id: 'beardling', cn: '胡须兔', en: 'Beardling', img: 'mob_beardling.png', cat: 'passive',
    hp: 25, hpText: '25（不会攻击）', dmg: '—', sanity: -40,
    where: '理智低于 40% 时，你眼里的兔子会全部变成胡须兔（背包、箱子里的也算）；被麦斯威尔的暗影陷阱打中也会强制变身一天',
    drops: ['胡须 40% / 怪物肉 40% / 噩梦燃料 20%'],
    note: '它不掉小肉，但掉落机制反而更香：非威尔逊角色想要胡子、缺噩梦燃料，猎胡须兔是最安全的路子。代价是靠近就 -40 理智/分。' },
  { id: 'beardlord', cn: '胡须领主（低理智兔人）', en: 'Beardlord', img: 'mob_beardlord.png', cat: 'neutral',
    hp: 200, dmg: 40, atk: 2, range: 3, sanity: -40,
    where: '理智低于 40% 时，洞穴里的兔人会以胡须领主的样子出现在你眼里；被暗影陷阱打中同样会被强制变身',
    drops: ['被低理智玩家击杀：胡须 ×2 + 怪物肉 ×1', '正常击杀：兔毛球 / 大肉 / 胡萝卜三选一'],
    note: '本质还是中立生物：喂胡萝卜照样能收买它当打手，但它的 -40 疯狂光环不会消失。想拿胡子就靠它——比抓地表兔子稳定得多，注意别在它面前捡肉。' },
  { id: 'crystal_buzzard', cn: '水晶冠秃鹫', en: 'Crystal-Crested Buzzard', img: 'mob_crystal_buzzard.png', cat: 'hostile',
    hp: 300, dmg: '25（啄）/ 15（火焰，每段）', atk: 1.5, range: '2（啄）/ 10（吐息）',
    where: '月后（裂隙开启后）的沙漠与荒地：被「入侵虚影」附身的秃鹫，成群跟着玩家飞',
    drops: ['腐坏食物 ×1', '月亮碎片 50%'],
    note: '月后版的秃鹫：会俯冲啄人，还会喷火并点燃附近的东西，成群出现时比普通秃鹫烦得多。掉月亮碎片，顺路清一清不亏。' },
  { id: 'saladmander_ripe', cn: '熟透的沙拉曼达', en: 'Saladmander Ripe', img: 'mob_saladmander_ripe.png', cat: 'neutral',
    hp: 900, dmg: 50, atk: 2, range: 2, speed: '0.5（跑 2）',
    where: '月亮岛的温泉区——沙拉曼达在热源旁（营火、浴球、热石头）会被「催熟」，变成通体橙红的熟透形态',
    drops: ['火龙果 ×1'],
    note: '红温版才是真麻烦：多段喷火会点燃身边 3.5 范围内的一切，附带 25 点无视护甲的火伤，6 秒一次。它血厚、伤害高但走得慢、不会群攻，用「打 2-3 下走 1 下」的节奏风筝；打死掉火龙果，比普通版的叶肉值钱。' },
  { id: 'wrathful_rabbit_king', cn: '暴戾兔王', en: 'Wrathful Rabbit King', img: 'mob_wrathful_rabbit_king.png', cat: 'hostile', alias: ['暴戾兔王'],
    hp: 2000, dmg: 75, sanity: -40,
    where: '① 攻击仁兔王，或带着肉类靠近它；② 杀兔子 / 兔人的隐藏「调皮值」攒到 20-30（兔 +1、兔人 +3）',
    drops: ['怪物肉 ×1', '胡须 ×2', '兔王短棍 ×1'],
    note: '会跺地召来 3 名皇家兔执行者，还有一记把人击飞的踢击。躲开那脚之后它会头栽地翻倒，那几秒是白给输出窗口；上船就钻地消失（会结束整场遭遇）。' },
  { id: 'royal_rabbit_enforcer', cn: '皇家兔执行者', en: 'Royal Rabbit Enforcer', img: 'mob_royal_rabbit_enforcer.png', cat: 'hostile',
    hp: 400, dmg: 40, atk: 3, range: 3,
    where: '暴戾兔王开战时会召唤 3 名；之后每 60 秒若不足 3 名会补员',
    drops: ['大肉系掉落（19% ×4 档）', '兔毛球 / 胡萝卜 等'],
    note: '兔王的小弟，血 400、伤害 40，数量一多很容易被围攻。优先清小弟再打王，或者干脆速杀王——王死了它们就好对付了。' },
  { id: 'shadow_hand', cn: '暗影之手（夜之手）', en: 'Night Hand', img: 'mob_shadow_hand.png', cat: 'hostile',
    hp: null, hpText: '无法击杀', dmg: '不造成伤害（扑灭火堆）',
    where: '夜里离火源太远时从黑暗中伸出，最多同时出现 3 只；伴随八音盒的诡异音乐',
    drops: ['无'],
    note: '它们的目的是掐灭你的火：手会一点点伸向火堆，碰到就灭掉。打不掉、只能躲——看到手从屏幕边缘伸进来，赶紧添燃料或换个地方。' },
  { id: 'big_tentacle', cn: '大触手（触虫）', en: 'Big Tentacle', img: 'mob_big_tentacle.png', cat: 'hostile',
    hp: 750, hpText: '本体 750（不攻击）；小触手 20', dmg: '本体不攻击 / 小触手 5', atk: '小触手 3', range: '小触手 3',
    where: '地下通往地表的触手根部（Tentapillar）；也会出现在洞穴的触手走廊',
    drops: ['石头 ×1', '触手尖刺（50%）', '触手皮（40%）', '沼泽地皮（25%）'],
    note: '打它会从周围冒出好几只「小触手（Baby Tentacle）」一起打你；反过来，只要不打根部，小触手清完就没了。要触手皮可以把它当稳定来源。' },
  { id: 'shadow_tentacle', cn: '暗影触手', en: 'Shadow Tentacle', img: 'mob_shadow_tentacle.png', cat: 'hostile',
    hp: 500, dmg: 34, atk: 2, range: 2,
    where: '用「铥矿棒」攻击命中时随机召出；远古守护者第二阶段也会放',
    drops: ['无'],
    note: '属于召唤物，打完自己消失。铥矿棒打人时冒暗影触手是它最有价值的地方——相当于白送额外输出来源。' },
  { id: 'poison_birchnut', cn: '毒桦栗树', en: 'Poison Birchnut Tree', img: 'mob_poison_birchnut.png', cat: 'hostile',
    hp: 12, hpText: '砍 18 下倒下', dmg: 30, atk: 1.5, range: 2,
    where: '秋季的桦树林：砍桦栗树时有概率「活过来」动手，周围还会刷出桦栗精',
    drops: ['桦栗果 ×3', '活木 ×1-2', '噩梦燃料 20%'],
    note: '它不动，但会用树枝抽人；麻烦的是同时冒出来的「桦栗精（Birchnutter）」会追着你咬。先清小怪再砍树，或者干脆换棵树砍。' },
  { id: 'gem_deer', cn: '宝石鹿', en: 'Gem Deer', img: 'mob_gem_deer.png', cat: 'hostile',
    hp: 1500, dmg: 50, atk: 2, range: 3,
    where: '克劳斯（Klaus）身边的红 / 蓝宝石鹿；克劳斯召唤时会把它变成强化形态',
    drops: ['大肉 ×2', '对应颜色宝石 ×1'],
    note: '血量 1500、伤害 50，比普通无眼鹿危险得多，而且会跟着克劳斯一起围攻。打克劳斯时优先处理或不理它——它掉宝石，是宝石的稳定来源之一。' },
  { id: 'lavae', cn: '熔岩虫', en: 'Lavae', img: 'mob_lavae.png', cat: 'hostile',
    hp: 500, dmg: '50（火焰伤害）', atk: 4, range: 6,
    where: '龙蝇的岩浆池孵化；龙蝇被击败后也可能残留',
    drops: ['常规：火 ×3', '被冻住打死：石头 ×1-5'],
    note: '火焰伤害无法靠护甲硬扛，靠近会被点着。用冰冻法杖定住再打，死掉掉石头；不冻死就只掉火（没什么用）。' },
  { id: 'ancient_sentrypede', cn: '远古哨兵蜈蚣', en: 'Ancient Sentrypede', img: 'mob_ancient_sentrypede.png', cat: 'hostile',
    hp: 1200, dmg: '40（啃咬）/ 20（范围冲击）', atk: 5, range: 2,
    where: '远古档案馆：蜈蚣壳吸收「安全脉冲」后活化，会一路爬过来打人',
    drops: ['哨兵蜈蚣壳（用于制作相关物品）'],
    note: '血 1200 且有不小的攻击范围，属于「别在档案馆里乱拉动作」的原因。想安静翻档案就先清掉它。' },
  { id: 'lustrous_weevil', cn: '光泽象虫', en: 'Lustrous Weevil', img: 'mob_lustrous_weevil.png', cat: 'hostile',
    hp: 1000, dmg: 40, atk: 2, range: 3,
    where: '圣所钥匙房：用爪子吊在天花板上，拉动拉杆会让它掉下来砸人',
    drops: ['（无固定掉落）'],
    note: '它砸下来那一下就是 40 伤害，之后会站起来打人。拉杆前先想好走位，或者干脆先把它处理掉。' },
  { id: 'naked_mole_bat', cn: '裸鼹蝠', en: 'Naked Mole Bat', img: 'mob_naked_mole_bat.png', cat: 'hostile', alias: ['裸鼹蝠'],
    hp: 150, dmg: 30, atk: 2, range: 2,
    where: '月岩洞穴（Lunar Grotto）上方光柱附近，玩家靠近光柱就会刷出来',
    drops: ['怪物肉 66% / 裸露的鼻孔 33%', '蝙蝠粪 15%'],
    note: '速度不快的空中怪，掉「裸鼻孔」是月后内容里的小材料。血少，几刀就能清。' },
  { id: 'suspicious_peeper', cn: '可疑窥视者', en: 'Suspicious Peeper', img: 'mob_suspicious_peeper.png', cat: 'hostile',
    hp: 200, dmg: 20, atk: 3, range: 2,
    where: '恐惧之眼 / 恐惧双子吐出的「恐惧之蛋」孵出来；蛋会自己滚向玩家',
    drops: ['（无固定掉落）'],
    note: 'Boss 战里的小麻烦：蛋滚过来孵化后就咬人，血少但数量多。优先踢碎蛋能省不少事。' },
  { id: 'prime_mate', cn: '海盗大副', en: 'Prime Mate', img: 'mob_prime_mate.png', cat: 'hostile',
    hp: 350, dmg: 60, atk: 1, range: 2,
    where: '月港附近的「海盗袭击」事件：海盗船上担任指挥的大副',
    drops: ['海盗相关战利品（藏宝图碎片 / 金币袋等）'],
    note: '攻击间隔只有 1 秒、单次 60 伤害，挨起来非常痛。好在会跟着船一起行动，把船打沉或者远远绕开都行。' },
  { id: 'crab_knight', cn: '蟹骑士', en: 'Crab Knight', img: 'mob_crab_knight.png', cat: 'hostile',
    hp: 1000, dmg: 80, atk: '4-6', range: 4.5, speed: '4 / 5', sanity: -40,
    where: '只在帝王蟹的战场上出现：帝王蟹血量低于 4200 时，每次召唤蟹卫会额外带出 1 只',
    drops: ['肉 ×1-3（平均 1.75）', '石头 ×1-3（平均 2）', '燧石 ×1-2（平均 1.5）'],
    note: '和蟹卫共享仇恨，选好目标后会旋转冲撞造成 80 点伤害；血量与催眠抗性随帝王蟹嵌入的紫宝石数变化。它站在浮动平台上，平台碎掉会直接跳海消失（这样就不掉东西）。' },
  { id: 'grazer', cn: '牧者', en: 'Grazer', img: 'mob_grazer.png', cat: 'hostile', alias: ['牧者'],
    hp: 2400, dmg: 50, atk: 4, range: 1.5,
    where: '月缝（Lunar Rift）旁边成群出现，一次 1-6 只',
    drops: ['（无固定掉落）'],
    note: '月缝事件里的肉盾型怪：血 2400，成群冲过来。别硬刚，把月缝先关掉或者绕开它。' },
  { id: 'deadly_brightshade', cn: '致命亮茄', en: 'Deadly Brightshade', img: 'mob_deadly_brightshade.png', cat: 'hostile', alias: ['致命亮茄'],
    hp: 1000, dmg: 100, atk: 2, range: 1,
    where: '月缝开启后，被「入侵虚影」感染的植物会变成它——也就是说，你基地旁边的草丛、浆果丛都可能站起来打人',
    drops: ['亮壳 ×2', '叶肉 ×2'],
    note: '月后最恶心的敌人之一：伤害 100、还会远程掷刺。用亮沙武器（域面武器）打才快；它掉「亮壳」，是月后装备线的核心材料。' },
  { id: 'ink_blight', cn: '墨影（暗影裂隙五怪）', en: 'Ink Blight', img: 'mob_ink_blight.png', cat: 'hostile', alias: ['墨荒', '刮擦', '躁动', '尖叫', '狞笑'],
    hp: 800, hpText: 'Shriek 800 / Rasp 1200 / Jitters 1000 / Rictus 800 / Icker 600',
    dmg: 'Shriek 25 / Rasp 20 / Jitters 35 / Rictus 35(咬)+15(扑) / Icker 20',
    atk: 4, range: 'Shriek 8 / Rasp 6 / Jitters 8 / Rictus 4 / Icker 6',
    where: '影缝（Shadow Rift）激活后：靠近长着「恐惧石露头」的噩梦裂隙就会出现，洞穴狭窄处还会成群刷「Icker」',
    drops: ['噩梦燃料（4-6）', '恐惧石 / 纯净恐惧 等影缝材料'],
    note: '五只都带「域面实体保护」，普通武器伤害大减，得用域面伤害武器。出场分两组：Shriek + Rasp + Jitters 三只轮流攻击（杀一只后剩下的攻击更频繁）；或者三只隐形 Rictus 依次现身。它们的真名只有对应暗影亲和技能的角色能看出来。' },
  { id: 'mega_blight', cn: '巨型墨影（涟漪）', en: 'Mega Blight', img: 'mob_mega_blight.png', cat: 'passive',
    hp: 2000, hpText: '2000（每节）', dmg: '75（对玩家）/ 150（对生物）',
    where: '影缝激活后出现在喷气孔地形（Fumarole）的泥地上',
    drops: ['恐惧石 ×1-3', '纯净恐惧 ×2-3', '噩梦燃料 ×2-5（每节）'],
    note: '平时不主动攻击，但你要是动手，它会一节一节站起来还手（每节独立算血与伤害）。想要恐惧石可以拿它当素材点。' },
  { id: 'ornery_chest', cn: '暴躁箱子', en: 'Ornery Chest', img: 'mob_ornery_chest.png', cat: 'hostile',
    hp: 950, dmg: 30, atk: 3, range: 4,
    where: '远古遗迹里伪装成「华丽箱子」，外观和掉落表都一模一样',
    drops: ['铥矿系材料 ×3-6', '齿轮 ×0-2', '它「吃掉」的东西（当前背包里的战利品）'],
    note: '开箱前先看清：真华丽箱子不会被玩家攻击锁定，暴躁箱子会。属于遗迹里的经典陷阱，吃过一次就记住了。' },
  { id: 'crab_guard', cn: '蟹卫', en: 'Crab Guard', img: 'mob_crab_guard.png', cat: 'hostile', alias: ['蟹卫'],
    hp: 200, hpText: '200（每颗紫宝石 +40）', dmg: 30, atk: 2, range: 2,
    where: '帝王蟹开战后召唤：蟹王造出浮冰后不断放出来的小螃蟹',
    drops: ['肉 ×1（另 25% 追加）', '石头 / 燧石'],
    note: '单个不痛，但帝王蟹会一直补员；嵌入紫宝石的蟹王召唤的守卫血量更高。打帝王蟹时先把浮冰拆掉能少很多麻烦。' },
  { id: 'terramite', cn: '土螈', en: 'Terramite', img: 'mob_terramite.png', cat: 'hostile',
    hp: 280, dmg: 50, atk: 2, range: 2,
    where: '「开明 W.A.R.B.O.T.」Boss 战：沃格斯塔夫把封装好的格式塔/牧者投进去造出来的小兵',
    drops: ['石头 ×1-2', '燧石 / 硝石 等'],
    note: 'Boss 战里的小怪，血少但伤害 50，别被围住。它们有「未激活 / 损坏」等状态。' },
  { id: 'warbler', cn: '鸣禽', en: 'Warbler', img: 'mob_warbler.png', cat: 'hostile',
    hp: null, hpText: '血量偏低（小型单位）', dmg: '45（电击伤害）',
    where: '同样是「开明 W.A.R.B.O.T.」Boss 战里被制造出来的小兵',
    drops: ['齿轮 / 电线 等机械材料'],
    note: '会放电，电击伤害无法用普通护甲完全抵消。Boss 战里优先清掉它们再输出本体。' },
  { id: 'geothermite', cn: '地热螨', en: 'Geothermite', img: 'mob_geothermite.png', cat: 'hostile',
    hp: 400, dmg: 25, atk: 4, range: 3,
    where: '喷气孔地形（Fumarole）自然生成；影缝激活后会变成带域面的强化版',
    drops: ['怪物肉 50% 或 热腺 50%', '石头（50%，隐藏状态 100%）'],
    note: '会钻进地里躲着，出来就咬人。「热腺」是喷气孔地形的重要材料，缺的话只能来这刷。' },
  { id: 'gilded_depths_worm', cn: '鎏金深渊蠕虫', en: 'Gilded Depths Worm', img: 'mob_gilded_depths_worm.png', cat: 'hostile',
    hp: 600, dmg: 75, atk: 4, range: 3,
    where: '「深渊蠕虫之年」活动：世界里存在深渊蠕虫神龛时，从可疑的土堆 / 蠕虫洞里冒出来',
    drops: ['怪物肉 ×2', '原木 ×2', '荧光果 ×0-1', '金块 ×3'],
    note: '活动版的深渊蠕虫，金色外观很好认，掉金块。它会从地里冲出并撞人，伤害 75 比普通蠕虫高。' },
  { id: 'clay_hound', cn: '黏土猎犬', en: 'Clay Hound', img: 'mob_clay_hound.png', cat: 'hostile',
    hp: 150, dmg: 20, atk: 2, range: 3,
    where: '「座狼神龛」激活后，从可疑土堆里连着黏土座狼一起冒出，一次 6 只 ×2 批',
    drops: ['红包（20%）', '猎犬牙（10%）'],
    note: '数值和普通猎犬几乎一样（稍微慢一点），血 150 一刀一刀清就行。它会掉「红包」。' },
  { id: 'clay_varg', cn: '黏土座狼', en: 'Clay Varg', img: 'mob_clay_varg.png', cat: 'hostile',
    hp: 1800, dmg: 50, atk: 3, range: 5,
    where: '座狼神龛激活后从可疑土堆冒出的「雕像」，玩家靠近就会醒来，身边跟着 12 只黏土猎犬',
    drops: ['红包 ×4-6', '猎犬牙 ×1-3'],
    note: '1800 血 + 12 只猎犬的组合很硬。建议先把猎犬拉散清掉，再处理本体；掉落的红包是牛王节活动的重要货币。' },
  { id: 'gingerbread_varg', cn: '姜饼座狼', en: 'Gingerbread Varg', img: 'mob_gingerbread_varg.png', cat: 'hostile',
    hp: 1800, dmg: 50, atk: 3, range: 5,
    where: '冬季盛宴：跟着「姜饼猪」留下的碎屑走，有 20% 概率引出姜饼座狼',
    drops: ['饼干碎屑 ×2-4', '节日欢愉 ×5-7', '猎犬牙 ×1-3'],
    note: '和普通座狼同数值，但掉的全是节日材料（节日欢乐可以换装扮）。冬季盛宴期间刷它比刷座狼划算。' },
  { id: 'bright_eyed_frog', cn: '明眼青蛙', en: 'Bright-Eyed Frog', img: 'mob_bright_eyed_frog.png', cat: 'hostile', alias: ['明眼青蛙'],
    hp: 150, dmg: 10, atk: 1, range: 4,
    where: '月后内容：青蛙被月能影响的强化版，出现在月岩洞穴与相关地形',
    drops: ['青蛙腿 ×1-2'],
    note: '和普通青蛙一样会舔掉你手里的东西，但伤害和血量都更高，还有域面保护（普通武器打不太动）。用域面武器或干脆绕开。' },
  { id: 'stagehand', cn: '舞台工（布景师）', en: 'Stagehand', img: 'mob_stagehand.png', cat: 'neutral',
    hp: 2924, dmg: 80, atk: 4, range: 3,
    where: '世界里自然生成：一圈玫瑰花围着一块「地面」，靠近会看到底下有东西在动',
    drops: ['（无固定掉落）'],
    note: '血厚到离谱（2924）、伤害 80，正常情况下没人会去惹它。它的价值是提示——这里有玫瑰，也是舞台剧玩法的相关要素。' },
  { id: 'anenemy', cn: '海葵怪', en: 'Anenemy', img: 'mob_anenemy.png', cat: 'neutral',
    hp: null, hpText: '不可击杀（打不死的植物）', dmg: 60,
    where: '月亮岛的礁石滩与月岛群礁；踩上去就会被夹住并拽住你',
    drops: ['（可以整株挖走带回基地当陷阱）'],
    note: '伤害 60 且会把你原地困住，是月亮岛最阴的陷阱。好消息是它能挖走——不少玩家会移植到自家门口当「自动门卫」。' },
  { id: 'grass_gator', cn: '草鳄', en: 'Grass Gator', img: 'mob_grass_gator.png', cat: 'neutral',
    hp: 1000, dmg: 50, atk: 4, range: 3,
    where: '「淹没（Waterlogged）」地形；平时伪装成一片草丛，靠近才会现身',
    drops: ['叶肉 ×7', '割下的草 ×2', '树枝 ×2'],
    note: '伪装成草皮，收割时突然咬你一口。血 1000、伤害 50，别在没护甲的情况下乱采草。' },
  { id: 'marotter', cn: '水獭掠夺者', en: 'Marotter', img: 'mob_marotter.png', cat: 'neutral', alias: ['海獭'],
    hp: 350, dmg: 35, atk: 4, range: 4,
    where: '海洋中的「海獭窝」附近，白天活动，成对出没并围着窝转',
    drops: ['小肉 ×1', '大肉 ×1', '瓶中信 5%'],
    note: '顺手就能打的水陆两栖小怪，掉瓶中信（可以挖沉底宝箱）。不主动招惹它们的话，它们也不会理你。' },
  { id: 'sea_weed', cn: '海草', en: 'Sea Weed', img: 'mob_sea_weed.png', cat: 'neutral',
    hp: 500, dmg: '68', atk: '5（黄色 2.5）', range: 18,
    where: '「汹涌海域（Rough Ocean）」成群出现，一次 8-15 株；有粉 / 黄 / 白等颜色变体',
    drops: ['种壳 ×2-3（黄色品种 3-5）', '海芽插穗 ×1'],
    note: '看着像海带，其实是会抽人的怪，伤害高达 68。要采海带请认准颜色和动作，别一头撞进海草堆。' },
  { id: 'mush_gnome', cn: '蘑菇地精', en: 'Mush Gnome', img: 'mob_mush_gnome.png', cat: 'neutral', alias: ['蘑菇地精'],
    hp: 600, dmg: '不主动攻击', atk: 8,
    where: '月岩洞穴；平时站在那儿发呆，玩家靠近也不会打你',
    drops: ['活木 ×1-2', '月亮孢子 ×3-5', '月亮蘑菇 ×2'],
    note: '本质是「会走路的月蘑菇」，打了才还手（攻击间隔 8 秒，很慢）。缺月亮孢子的时候它是稳定来源。' },
  { id: 'greater_gestalt', cn: '大虚影', en: 'Greater Gestalt', img: 'mob_greater_gestalt.png', cat: 'neutral', alias: ['大虚影', '月魂'],
    hp: null, hpText: '无法攻击 / 无法击杀', dmg: '—（提供「启迪」而非伤害）',
    where: '月亮岛、月岩洞穴与月缝附近飘浮；靠近会给你叠加「启迪（Enlightenment）」',
    drops: ['（无法击杀；可用相位封装器收走）'],
    note: '启迪对月后玩法是双刃剑：它让你能使用月能武器与部分月后机制，但启迪值满了会变成「启迪惩罚」开始掉血。不要长时间贴在它们旁边。' },
  { id: 'inimical_gestalt', cn: '敌意虚影', en: 'Inimical Gestalt', img: 'mob_inimical_gestalt.png', cat: 'neutral', alias: ['敌意虚影'],
    hp: null, hpText: '无法击杀', dmg: 10, sanity: -10,
    where: '月缝（Lunar Rift）附近；月缝越大出现越多',
    drops: ['（无法击杀）'],
    note: '会主动飘过来撞你并掉理智，打不掉，只能躲或者把月缝关掉。它同时也是「入侵虚影」的固定来源之一。' },
  { id: 'incursive_gestalt', cn: '入侵虚影', en: 'Incursive Gestalt', img: 'mob_incursive_gestalt.png', cat: 'neutral', alias: ['入侵虚影'],
    hp: null, hpText: '无法击杀', dmg: '—',
    where: '月缝激活期间飘浮，会「感染」附近的植物',
    drops: ['（无法击杀；可用相位封装器收走）'],
    note: '被它附身的植物会变成「致命亮茄」，秃鹫会变成「水晶冠秃鹫」。看到它在你的农田上飘，赶紧先把月缝关掉。' },
  { id: 'houndius_shootius', cn: '眼球镭射塔', en: 'Houndius Shootius', img: 'Houndius_Shootius.png', cat: 'neutral',
    hp: 1000, dmg: 65, atk: 3, range: 12,
    where: '玩家自制：远古分类制作，需要 1 个守护者号角 + 1 个独眼巨鹿眼球 + 5 个铥矿，只能在远古伪科学站旁制作',
    drops: ['（放置后可回收）'],
    note: '全游戏最强的固定防御：12 格射程、单发 65 伤害，围一圈墙就能自动清猎犬、刷兔人。缺点是需要远古材料，属于中后期配置。' },
  { id: 'elite_pig', cn: '精英猪', en: 'Elite Pig', img: 'mob_elite_pig.png', cat: 'neutral',
    hp: null, hpText: '比赛单位（不参与战斗）', dmg: '—',
    where: '「猪王之年」活动：给猪王金腰带开启摔跤比赛后，它会召唤 4 只精英猪和你抢金块',
    drops: ['（比赛奖励：抢到 60% 以上金块，每人 10 金块 + 猪肉干）'],
    note: '不会攻击你，但抢金块比你快。用懒人护符提高捡取效率、用排箫把它们催眠（猪人观众会喊你作弊，但奖励照给）。' },
  { id: 'mosling', cn: '小麋鹿鹅', en: 'Mosling', img: 'mob_mosling.png', cat: 'neutral',
    hp: 525, dmg: 50, atk: 3, range: 2, speed: 5,
    where: '春季在麋鹿鹅巢中孵化；幼崽会围绕巢穴活动并跟随同巢群体',
    drops: ['大肉 ×1', '鸡腿 ×1', '羽绒 ×2–3（概率掉落）'],
    note: '通常会回避玩家。父母仍在时，攻击小高鸟会引来麋鹿鹅保护；麋鹿鹅被击败后，小高鸟会变得敌对，以旋风冲撞攻击。联机版生命值为 525。' },
  { id: 'fireflies', cn: '萤火虫', en: 'Fireflies', img: 'mob_fireflies.png', cat: 'passive',
    hp: null, hpText: '不能攻击', dmg: '—',
    where: '夜里出现在森林 / 草原，洞穴里（蘑菇树森林）全天都有',
    drops: ['萤火虫（用捕虫网抓，用来做矿工帽、灯）'],
    note: '夜里最好用的免费光源材料。顺手抓几只，矿工帽就不愁了；也能放进「南瓜灯」之类装饰里。' },
  { id: 'mandrake', cn: '曼德拉草', en: 'Mandrake', img: 'mob_mandrake.png', cat: 'passive',
    hp: 20, dmg: '—（白天会跟着你跑）',
    where: '草原与洞穴，一个世界平均只刷 2-5 株，还会连着出现',
    drops: ['曼德拉草（可烹饪 / 做曼德拉草汤 / 复活药）'],
    note: '白天拔出来它会尖叫着跟你跑，黄昏 / 夜里拔则不会。曼德拉草汤是回血神菜（+100 生命），而做复活肖像更要拿它当材料——所以拔之前想清楚要留来做什么。' },
  { id: 'fortuitous_rabbit', cn: '幸运兔', en: 'Fortuitous Rabbit', img: 'mob_fortuitous_rabbit.png', cat: 'passive',
    hp: null, hpText: '抓住即变兔王', dmg: '—',
    where: '兔子洞冒出来的兔子里有 1% 概率是它（地震掉落的兔子是 10%），速度不比玩家快',
    drops: ['（抓住 → 变成仁兔王）'],
    note: '不能用陷阱抓，只能追上去手动抓。看到发光的兔子赶紧追——抓住就等于白送一个兔王（和它的贸易兔舍制作栏）。' },
  { id: 'carrat', cn: '胡萝卜鼠', en: 'Carrat', img: 'mob_carrat.png', cat: 'passive',
    hp: 25, dmg: '—',
    where: '「胡萝卜鼠之年」活动期间的地下 / 农场地带；活动里还能举办赛鼠比赛',
    drops: ['胡萝卜（33%）'],
    note: '毛茸茸的小家伙，抓起来能参加赛鼠；平时也是好看的小宠物。活动结束后会消失。' },
  { id: 'lunar_wobster', cn: '月光龙虾', en: 'Lunar Wobster', img: 'mob_lunar_wobster.png', cat: 'passive', alias: ['月光龙虾'],
    hp: 25, dmg: '—',
    where: '月亮岛的「月玻璃堆」附近，黄昏与夜晚钻出来',
    drops: ['月光龙虾（食材）', '月亮碎片'],
    note: '月后版本的龙虾，能钓 / 抓起当食材；也会掉月亮碎片，顺手捡。' },
  { id: 'crustashine', cn: '闪光甲壳', en: 'Crustashine', img: 'mob_crustashine.png', cat: 'passive',
    hp: 25, dmg: '—',
    where: '月港（猴岛）上到处爬，也会从「异常传送门」里喷出来',
    drops: ['大肉 / 破碎贝壳等贝壳类掉落物（三选一）'],
    note: '会发光的小螃蟹，是月港随手可捡的食物来源；击杀时可能掉落破碎贝壳。' },
  { id: 'resting_horror', cn: '安眠梦魇', en: 'Resting Horror', img: 'mob_resting_horror.png', cat: 'passive',
    hp: 1, dmg: '—',
    where: '远古遗迹里某把「遗物椅」上坐着的一团暗影；被攻击就会碎掉',
    drops: ['噩梦燃料 ×1', '稀有蓝图：仿制遗物椅（学它才能做珍稀椅子和寄居蟹的椅子任务）'],
    note: '血只有 1，但价值极高——「仿制遗物椅」的蓝图就在它身上，寄居蟹老奶奶的第一个任务（做木椅）必须用到它。看到遗迹椅子就顺手打掉。' },
  { id: 'void_masque', cn: '虚空面具', en: 'Void Masque', img: 'mob_void_masque.png', cat: 'passive',
    hp: null, hpText: '与被附身的生物同血量', dmg: '与被附身的生物同伤害',
    where: '暗影阵营相关内容：会像「啜食者」一样跳到你头上，但是戴在头部装备栏',
    drops: ['纯粹恐惧', '贤者面具 / 马屁精面具 / 蠢人面具（30%）'],
    note: '装备它会改变机制（视野与部分行为都会变得「暗影化」）。属于主线后期的玩法道具，普通玩家谨慎尝试。' },
  { id: 'shadow_puppet', cn: '暗影傀儡（战斗型）', en: 'Shadow Duelist', img: 'mob_shadow_puppet.png', cat: 'passive',
    hp: 75, hpText: '75（存在 2 分钟）', dmg: 20, atk: 1.8, range: null, speed: 6,
    where: '麦斯威尔用暗影法典召唤的战斗型暗影仆从；每次召唤消耗最大理智的 15%',
    drops: ['无（限时召唤物）'],
    note: '会攻击召唤范围内的敌人，基础伤害 20；可受麦斯威尔装备加成提高伤害，并有冲刺攻击。通常持续 2 分钟；非战斗状态下可能更快消失。战斗型与采集型暗影仆从不同，采集型负责砍树、挖矿、采集及拾取物品。' },
  { id: 'mr_skitts', cn: '骷髅先生', en: 'Mr. Skitts', img: 'mob_mr_skitts.png', cat: 'passive',
    hp: null, hpText: '无法攻击 / 无法被攻击', dmg: '—',
    where: '理智低于 82.5% 时随时可能出现在你身边，一条小蛇状的暗影',
    drops: ['（无）'],
    note: '纯吓人的：不会攻击你，你靠近它就溜走。属于低理智的「氛围提示」——看到它说明你该吃点回理智的东西了。' },
  { id: 'shadow_watcher', cn: '暗影窥视者', en: 'Shadow Watcher', img: 'mob_shadow_watcher.png', cat: 'passive',
    hp: null, hpText: '无法攻击 / 无法被攻击', dmg: '—',
    where: '理智低于 65% 的夜里，出现在光源旁边（包括充能的避雷针）',
    drops: ['（无）'],
    note: '细长的影子，站在光边看你，你一靠近就消失。同样是无害的低理智提示。' },
  { id: 'shadow_eyes', cn: '暗影之眼', en: 'Shadow Eyes', img: 'mob_shadow_eyes.png', cat: 'passive',
    hp: null, hpText: '无法攻击 / 无法被攻击', dmg: '—',
    where: '完全黑暗中、理智低于 80% 时，黑暗里会亮起一双双眼睛',
    drops: ['（无）'],
    note: '理智越低出现越多。它们不造成任何伤害，但意味着你离「黑夜怪」很近了——赶紧点火把。' },
  { id: 'woven_shadow', cn: '编织暗影', en: 'Woven Shadow', img: 'mob_woven_shadow.png', cat: 'passive',
    hp: 1, dmg: '—',
    where: '远古织影者（Ancient Fuelweaver）从远古地板里召唤出来的手 / 骷髅',
    drops: ['（无）'],
    note: '血只有 1，但会挡路、抓人。Boss 战里优先清这些「手」，否则会被拖住。' },
  { id: 'kitcoon', cn: '小浣猫', en: 'Kitcoon', img: 'mob_kitcoon.png', cat: 'passive', alias: ['猫仔', '提库恩'],
    hp: null, hpText: '无法攻击', dmg: '—',
    where: '仲夏嘉年华：按地形有不同花色的猫仔（森林 / 草原 / 沼泽 / 岩地…）',
    drops: ['（嘉年华代币相关）'],
    note: '嘉年华的吉祥物，各花色的位置对应不同地形。属于活动收集要素，不需要打它。' },
  { id: 'crow_kid', cn: '小乌鸦', en: 'Crow Kid', img: 'mob_crow_kid.png', cat: 'passive',
    hp: null, hpText: '无法击杀', dmg: '—',
    where: '仲夏嘉年华：种下嘉年华树后出现的观众，会在装饰之间乱逛',
    drops: ['（无）'],
    note: '嘉年华的围观群众——装饰越多它们越活跃。纯装饰性 NPC 之一。' },
  { id: 'gingerbread_pig', cn: '姜饼猪', en: 'Gingerbread Pig', img: 'mob_gingerbread_pig.png', cat: 'passive',
    hp: 100, dmg: '—',
    where: '冬季盛宴：世界里会留下「饼干碎屑」的痕迹，跟着走就能找到',
    drops: ['死掉：饼干碎屑 ×3 + 节日欢愉 ×1', '跟随中：周期性掉饼干碎屑'],
    note: '跟着它的碎屑走，有 20% 概率引出「姜饼座狼」。想要节日材料就顺着痕迹追。' },

  /* ==================== 补充：月后 / 主线巨兽 ==================== */
  { id: 'warbot', cn: 'W.A.R.B.O.T.（战争机器）', en: 'W.A.R.B.O.T. / Undisclosed Construct', img: 'mob_warbot.png', cat: 'boss',
    hp: 22500, dmg: '多段（冲锋 / 激光 / 召唤，见战斗阶段）', atk: 3, range: 8, sanity: -400, saneFight: -400,
    where: '隐士岛的沃格斯塔夫任务线终点：用「基质外推器」铺满整座隐士岛 → 「未公开构造体」现身 → 再投喂封装好的格式塔',
    drops: ['齿轮 ×0-1', '电子零件 ×0-1', '废料 ×1-2', 'W.A.R.B.O.T. 手稿（雕像草图）'],
    note: '血量 22500，是全游戏最厚的之一。它会召唤土螈与鸣禽当小兵，打完第一形态还会变成「开明 W.A.R.B.O.T.」再战一场——击败它才会引出最终 Boss「天体后继者」。这是月后主线最硬的一关，建议 4 人队 + 域面武器。' },
  { id: 'celestial_scion', cn: '天体后继者', en: 'Celestial Scion', img: 'mob_celestial_scion.png', cat: 'boss',
    hp: 16000, dmg: '191.25（对玩家）/ 255（对生物）', atk: '多段', speed: 2.9, sanity: -400, saneFight: -400,
    where: '击败「开明 W.A.R.B.O.T.」后由它召唤而出——目前游戏里月后主线的最终 Boss',
    drops: ['天体宝石 ×5', '纯粹辉煌 ×5-7', '焦电线 ×2-3', '齿轮 ×1-2', '天体后继者手稿（雕像草图）'],
    note: '带「域面实体保护」，普通武器伤害打大折扣，必须用月能 / 暗影域面武器。它的多段攻击伤害高达 191，护甲与走位都得到位。打完这条线基本就是新纪元结局了。' },
  { id: 'celestial_revenant', cn: '天体亡魂', en: 'Celestial Revenant', img: 'mob_celestial_revenant.png', cat: 'boss',
    hp: 8000, dmg: '125（对玩家）/ 166.66（触手翻滚）、50 / 66.66（范围）', atk: 7.5, range: 4.25, sanity: '-400（战斗）/ +100（平时）', saneFight: -400,
    where: '隐士岛：集齐 6 个「相位封装器」之后被召唤出来的天体造物',
    drops: ['天体系材料 ×3-5（月亮碎片 / 灌注月亮碎片一类）', '纯净系材料 ×2-5（纯粹辉煌等）', '月亮碎片 ×2-5', '齿轮 ×2'],
    note: '8000 血、攻击间隔 7.5 秒所以节奏偏慢，但单次 125 伤害很痛，还有会翻滚追击的触手。注意它的范围攻击会连带打到建筑。' },
  { id: 'ancient_guard_tower', cn: '远古守卫塔', en: 'Ancient Guard Tower', img: 'mob_ancient_guard_tower.png', cat: 'boss',
    hp: 6000, dmg: '75（对玩家）/ 150（对生物）', atk: 3, range: 5, sanity: -400, saneFight: -400,
    where: '圣所（Sanctum）的钥匙房：四座休眠的远古塔，等四个「脉冲摇篮」全部充能后一起苏醒',
    drops: ['远古材料 ×2-4（每座）', '四部件各一（合成用）'],
    note: '四座塔同时开火，站桩必被集火。打法核心是用柱子卡视线、逐座拆——注意每座都是独立的 6000 血。' }
];
