/* ============================================================
   饥荒联机版 · 初级食材库 数据 (js/ingredients.js)
   每个条目 = 一种可入锅的食材（生鲜 / 火烤 / 晾晒 / 特殊）
   字段说明：
     cat     分类（raw 生鲜 / roast 火烤 / dry 晾晒 / misc 不可食用与调味）
     tags    食物度（决定能做出什么料理）
     hg/hp/sa 直接吃下去的三维恢复（null = 资料未明确）
     perish  保质期（天，null = 不腐烂或资料未明确）
     pair    生 ↔ 熟 对应条目 id
     source  获取途径
     tip     小提示
   ============================================================ */

const LIB_CATS = {
  raw:   { cn: '生鲜',            color: '#7fc08a' },
  roast: { cn: '火烤 · 轻加工',    color: '#e8a33d' },
  dry:   { cn: '晾晒 · 晾肉架',    color: '#b98f5c' },
  misc:  { cn: '不可食用 / 调味',  color: '#a08fd0' }
};

const LIB_ITEMS = [
  /* ==================== 蔬菜类 ==================== */
  { id: 'carrot', cn: '胡萝卜', en: 'Carrot', img: 'ing_carrot.png', cat: 'raw', tags: { veggie: 1 },
    hg: 12.5, hp: 1, sa: 0, perish: 10, pair: 'carrot_cooked',
    source: '地表自然生成，可采摘；种植普通种子或椭圆种子获得；兔人有几率掉落，洞穴兔人小屋可拆出胡萝卜。野外胡萝卜在春季再生。',
    tip: '生熟饱食一样，但烤过之后回血从 1 点变 3 点，是前期最稳的口粮。' },
  { id: 'corn', cn: '玉米', en: 'Corn', img: 'ing_corn.png', cat: 'raw', tags: { veggie: 1 },
    hg: 25, hp: 3, sa: 0, perish: 10, pair: 'corn_cooked',
    source: '农场种植（需要种子）',
    tip: '饥饿 25 很高，但烤成爆米花反而掉到 12.5——想吃饱就别烤。' },
  { id: 'pumpkin', cn: '南瓜', en: 'Pumpkin', img: 'ing_pumpkin.png', cat: 'raw', tags: { veggie: 1 },
    hg: 37.5, hp: 3, sa: 0, perish: 10, pair: 'pumpkin_cooked',
    source: '农场种植',
    tip: '素食里饱食第一，配 2 个蜂蜜就是南瓜饼干。' },
  { id: 'eggplant', cn: '茄子', en: 'Eggplant', img: 'ing_eggplant.png', cat: 'raw', tags: { veggie: 1 },
    hg: 25, hp: 8, sa: 0, perish: 10, pair: 'eggplant_cooked',
    source: '农场种植',
    tip: '烤茄子的回血从 8 涨到 20，升级明显（酿茄子还能取暖）。' },
  { id: 'asparagus', cn: '芦笋', en: 'Asparagus', img: 'ing_asparagus.png', cat: 'raw', tags: { veggie: 1 },
    hg: 12.5, hp: 3, sa: 0, perish: 6, pair: 'asparagus_cooked',
    source: '农场种植 / 野生芦笋丛',
    tip: '烤过饱食翻倍到 25，是蔬菜鸡尾酒、芦笋汤的核心材料。' },
  { id: 'onion', cn: '洋葱', en: 'Onion', img: 'ing_onion.png', cat: 'raw', tags: { veggie: 1 },
    hg: 9.375, hp: 0, sa: -10, perish: 15, pair: 'onion_cooked',
    source: '农场种植',
    tip: '生吃扣 10 理智，烤过只扣 5。莎莎酱、素食汉堡、海鲜杂烩都要它。' },
  { id: 'garlic', cn: '大蒜', en: 'Garlic', img: 'ing_garlic.png', cat: 'raw', tags: { veggie: 1 },
    hg: 9.375, hp: 0, sa: -10, perish: 15, pair: 'garlic_cooked',
    source: '农场种植',
    tip: '奶油土豆泥的指定材料；生吃同样扣理智。' },
  { id: 'tomato', cn: '番茄（番茄根）', en: 'Toma Root', img: 'ing_tomato.png', cat: 'raw', tags: { veggie: 1 },
    hg: 12.5, hp: 3, sa: 0, perish: 6, pair: 'tomato_cooked',
    source: '农场种植',
    tip: '游戏里的英文名是 Toma Root。海鲜杂烩、莎莎酱、蔬菜鸡尾酒都会用到。' },
  { id: 'potato', cn: '土豆', en: 'Potato', img: 'ing_potato.png', cat: 'raw', tags: { veggie: 1 },
    hg: 12.5, hp: -3, sa: -5, perish: 10, pair: 'potato_cooked',
    source: '农场种植',
    tip: '生吃是负面效果，烤过后变成 20 血 / 25 饥饿的优质口粮，也是沃尔夫冈的喜爱食物。' },
  { id: 'pepper', cn: '辣椒', en: 'Pepper', img: 'ing_pepper.png', cat: 'raw', tags: { veggie: 1 },
    hg: 9.375, hp: -20, sa: -15, perish: 15, pair: 'pepper_cooked',
    source: '农场种植',
    tip: '生吃扣 20 血，烤过只扣 3 血。爆炒填馅辣椒、辣龙椒沙拉都需要它。' },
  { id: 'cactus_flesh', cn: '仙人掌肉', en: 'Cactus Flesh', img: 'ing_cactus_flesh.png', cat: 'raw', tags: { veggie: 1 },
    hg: 12.5, hp: -3, sa: -5, perish: 10, pair: 'cactus_flesh_cooked',
    source: '沙漠仙人掌上采集（需要穿戴护具或手套）',
    tip: '必须烤过再吃：熟仙人掌肉会变成 +1 血 / +15 理智的「反负面」食物。' },
  { id: 'cactus_flower', cn: '仙人掌花', en: 'Cactus Flower', img: 'ing_cactus_flower.png', cat: 'raw', tags: { veggie: 0.5 },
    hg: 12.5, hp: 8, sa: 5, perish: 3,
    source: '沙漠仙人掌开花时采集',
    tip: '花沙拉（回血 40）的指定材料，而且自带回血回理智。' },
  { id: 'kelp', cn: '海带叶', en: 'Kelp Fronds', img: 'ing_kelp.png', cat: 'raw', tags: { veggie: 0.5 },
    hg: 9.375, hp: -1, sa: -10, perish: 10, pair: 'kelp_cooked',
    source: '海面上的海带丛采集',
    tip: '0.5 蔬菜度，是加州卷、藤壶握寿司的常用配料，也能给牛当饲料。' },
  { id: 'stone_fruit_ripe', cn: '成熟石果', en: 'Ripe Stone Fruit', img: 'ing_stone_fruit_ripe.png', cat: 'raw', tags: { veggie: 1 },
    hg: 12.5, hp: 1, sa: 0, perish: 3, pair: 'stone_fruit_cooked',
    source: '挖取石果丛后获得的成熟石果',
    tip: '1 点蔬菜度，鳄梨酱可以用它替代仙人掌肉。' },
  { id: 'mandrake', cn: '曼德拉草', en: 'Mandrake', img: 'ing_mandrake.png', cat: 'raw', tags: { veggie: 1, magic: 1 },
    hg: 75, hp: 60, sa: 0, perish: null, pair: 'mandrake_cooked',
    source: '地表草地与洞穴中稀有生成（黄昏或夜晚采摘会变成跟随玩家的活体）',
    tip: '生曼德拉草可恢复 75 饥饿 / 60 生命，并使附近生物及玩家昏睡约 10 秒；烤熟后恢复 150 饥饿 / 100 生命，同样会触发昏睡。曼德拉草很稀有，使用前请留意范围效果。' },

  /* ==================== 四种蘑菇 ==================== */
  { id: 'mushroom_red', cn: '红蘑菇', en: 'Red Cap', img: 'ing_mushroom_red.png', cat: 'raw', tags: { veggie: 0.5 },
    hg: 12.5, hp: -20, sa: 0, perish: 10, pair: 'mushroom_red_cooked',
    source: '白天在地面出现（挖出来能得 2 个）',
    tip: '生吃扣 20 血的「毒蘑菇」；烤过后 0 饥饿但 +1 血 / -10 理智。' },
  { id: 'mushroom_green', cn: '绿蘑菇', en: 'Green Cap', img: 'ing_mushroom_green.png', cat: 'raw', tags: { veggie: 0.5 },
    hg: 12.5, hp: 0, sa: -50, perish: 10, pair: 'mushroom_green_cooked',
    source: '黄昏时出现（沼泽一带较多）',
    tip: '生吃 −50 理智，烤过却变成 +15 理智的「回理智神器」。' },
  { id: 'mushroom_blue', cn: '蓝蘑菇', en: 'Blue Cap', img: 'ing_mushroom_blue.png', cat: 'raw', tags: { veggie: 0.5 },
    hg: 12.5, hp: 20, sa: -15, perish: 10, pair: 'mushroom_blue_cooked',
    source: '夜晚出现（桦树林、洞穴较多）',
    tip: '生吃 +20 血 −15 理智，是前期的「血包」；烤过反而 −3 血。' },
  { id: 'mushroom_lunar', cn: '月亮蘑菇', en: 'Moon Shroom', img: 'ing_mushroom_lunar.png', cat: 'raw', tags: { veggie: 0.5 },
    hg: null, hp: null, sa: null, perish: null, pair: 'mushroom_lunar_cooked',
    source: '月亮树林 / 月亮裂缝周边采集',
    tip: '蘑菇蛋糕与酿蘑菇盖的指定材料；生熟数值各版本有差异，以游戏内为准。' },

  /* ==================== 水果类 ==================== */
  { id: 'berries', cn: '浆果', en: 'Berries', img: 'ing_berries.png', cat: 'raw', tags: { fruit: 0.5 },
    hg: 9.375, hp: 0, sa: 0, perish: 6, pair: 'berries_cooked',
    source: '浆果丛采集（草原 / 森林随处可见）',
    tip: '最便宜的填充物：0.5 水果度，肉丸、果酱、肉串全靠它凑数。' },
  { id: 'berries_juicy', cn: '多汁浆果', en: 'Juicy Berries', img: 'ing_berries_juicy.png', cat: 'raw', tags: { fruit: 0.5 },
    hg: 12.5, hp: 1, sa: 0, perish: 2, pair: 'berries_juicy_cooked',
    source: '多汁浆果丛采集（一次能摘 3 个）',
    tip: '比普通浆果更顶饱，但只有 2 天保质期，烂得快也适合做肥料。' },
  { id: 'pomegranate', cn: '石榴', en: 'Pomegranate', img: 'ing_pomegranate.png', cat: 'raw', tags: { fruit: 1 },
    hg: 9.375, hp: 3, sa: 0, perish: 6, pair: 'pomegranate_cooked',
    source: '农场种植',
    tip: '1 点水果度；沃拓克斯的喜爱食物（×2.6），切片熟石榴回血 20。' },
  { id: 'dragonfruit', cn: '火龙果', en: 'Dragon Fruit', img: 'ing_dragonfruit.png', cat: 'raw', tags: { fruit: 1 },
    hg: 9.375, hp: 3, sa: 0, perish: 6, pair: 'dragonfruit_cooked',
    source: '农场种植',
    tip: '火龙果派（75 饥饿 / 40 血）的指定材料，也是辣龙椒沙拉的原料。' },
  { id: 'watermelon', cn: '西瓜', en: 'Watermelon', img: 'ing_watermelon.png', cat: 'raw', tags: { fruit: 1 },
    hg: 12.5, hp: 3, sa: 5, perish: 6, pair: 'watermelon_cooked',
    source: '农场种植',
    tip: '少见的「回理智水果」；做成西瓜冰棍还能降温。' },
  { id: 'durian', cn: '榴莲', en: 'Durian', img: 'ing_durian.png', cat: 'raw', tags: { fruit: 1, monster: 1 },
    hg: 25, hp: -3, sa: -5, perish: 10, pair: 'durian_cooked',
    source: '农场种植',
    tip: '唯一自带 1 点怪物度的水果——放多了会做出怪物千层饼。沃特的喜爱食物。' },
  { id: 'banana', cn: '香蕉（洞穴香蕉）', en: 'Banana', img: 'ing_banana.png', cat: 'raw', tags: { fruit: 1 },
    hg: 12.5, hp: 1, sa: 0, perish: 10, pair: 'banana_cooked',
    source: '洞穴 / 月岛的香蕉树采集，或击败猴子类生物掉落',
    tip: '香蕉冻、冰香蕉冻唇蜜、香蕉奶昔全靠它，是回理智的好材料。' },
  { id: 'fig', cn: '无花果', en: 'Fig', img: 'ing_fig.png', cat: 'raw', tags: { fruit: 0.5 },
    hg: 12.5, hp: 0, sa: 0, perish: 6, pair: 'fig_cooked',
    source: '海上无花果树采集',
    tip: '0.5 水果度，但熟无花果会翻到 18.75 饥饿，是无花果系列料理的起点。' },
  { id: 'glow_berry_small', cn: '小发光浆果', en: 'Lesser Glow Berry', img: 'ing_glow_berry_small.png', cat: 'raw', tags: { fruit: 0.5 },
    hg: 12.5, hp: 3, sa: -10, perish: 10,
    source: '月亮树林的发光浆果丛',
    tip: '生吃扣 10 理智；发光浆果慕斯的替代材料。' },
  { id: 'glow_berry', cn: '发光浆果', en: 'Glow Berry', img: 'ing_glow_berry.png', cat: 'raw', tags: { fruit: 1 },
    hg: 25, hp: 11, sa: -10, perish: 10,
    source: '月亮树林采集',
    tip: '1 点水果度，发光浆果慕斯的指定材料。' },

  /* ==================== 肉类 / 水产 ==================== */
  { id: 'meat_big', cn: '大肉', en: 'Meat', img: 'Meat.png', cat: 'raw', tags: { meat: 1 },
    hg: 25, hp: 1, sa: -10, perish: 6, pair: 'meat_big_cooked',
    source: '击杀牦牛、猪人、高鸟、麋鹿鹅等大型生物掉落',
    tip: '生吃扣 10 理智；烤过立刻变成 25 饥饿 / 3 血。1 点肉度，是肉丸、肉汤的底料。' },
  { id: 'meat_small', cn: '小肉', en: 'Morsel', img: 'Morsel.png', cat: 'raw', tags: { meat: 0.5 },
    hg: 12.5, hp: 0, sa: -10, perish: 6, pair: 'meat_small_cooked',
    source: '击杀兔子、鸟、企鹅、火鸡等小型生物掉落',
    tip: '0.5 肉度，恢复量和胡萝卜一样；烤熟后不再扣理智。' },
  { id: 'monster_meat', cn: '怪物肉', en: 'Monster Meat', img: 'ing_monster_meat.png', cat: 'raw', tags: { meat: 1, monster: 1 },
    hg: 18.75, hp: -20, sa: -15, perish: 6, pair: 'monster_meat_cooked',
    source: '击杀蜘蛛、猎犬、触手等怪物掉落',
    tip: '生吃 −20 血 / −15 理智，别直接啃。放 2 块就会强制变成怪物千层饼，做菜时一次只放 1 块最稳。' },
  { id: 'drumstick', cn: '鸡腿', en: 'Drumstick', img: 'ing_drumstick.png', cat: 'raw', tags: { meat: 0.5 },
    hg: 12.5, hp: 0, sa: -10, perish: 6, pair: 'drumstick_cooked',
    source: '击杀火鸡掉落（把浆果 / 蘑菇放地上可以引诱）',
    tip: '火鸡正餐需要 2 个鸡腿，是薇格弗德的喜爱料理材料。' },
  { id: 'frog_leg', cn: '蛙腿', en: 'Frog Leg', img: 'ing_frog_leg.png', cat: 'raw', tags: { meat: 0.5 },
    hg: 12.5, hp: 0, sa: -10, perish: 6, pair: 'frog_leg_cooked',
    source: '击杀青蛙掉落（池塘 / 沼泽一带）',
    tip: '0.5 肉度，蛙腿三明治、无花果蛙腿三明治的指定材料。' },
  { id: 'bat_wing', cn: '蝙蝠翅膀', en: 'Batilisk Wing', img: 'ing_bat_wing.png', cat: 'raw', tags: { meat: 0.5 },
    hg: 12.5, hp: 3, sa: -10, perish: 6, pair: 'bat_wing_cooked',
    source: '击杀洞穴蝙蝠掉落',
    tip: '烤过变 18.75 饥饿 / 8 血，是肉类的补充来源。' },
  { id: 'moleworm', cn: '鼹鼠', en: 'Moleworm', img: 'ing_moleworm.png', cat: 'raw', tags: { meat: 0.5 },
    hg: null, hp: null, sa: null, perish: null,
    source: '用锤子 / 陷阱捕捉地里钻出来的鼹鼠',
    tip: '0.5 肉度，也是鳄梨酱的指定材料；会偷地上的矿物，别让它进基地。' },
  { id: 'leafy_meat', cn: '叶肉', en: 'Leafy Meat', img: 'ing_leafy_meat.png', cat: 'raw', tags: { meat: 1 },
    hg: 12.5, hp: 0, sa: -10, perish: 6, pair: 'leafy_meat_cooked',
    source: '击杀吞噬植物的叶肉生物掉落',
    tip: '叶肉糕、素食汉堡、牛肉绿叶菜的指定材料，1 点肉度。' },
  { id: 'koalefant_trunk', cn: '考拉象鼻', en: 'Koalefant Trunk', alias: ['冬象鼻', '象鼻'], img: 'ing_koalefant_trunk.png', cat: 'raw', tags: { meat: 1 },
    hg: 37.5, hp: 30, sa: 0, perish: 6, pair: 'koalefant_trunk_cooked',
    source: '击杀考拉象掉落',
    tip: '不要直接吃！做成烤象鼻是 75 饥饿 / 40 血，做成无花果酿象鼻是 150 饥饿 / 60 血。' },
  { id: 'fish', cn: '鱼 / 生鱼肉', en: 'Fish', img: 'ing_fish.png', cat: 'raw', tags: { meat: 0.5, fish: 0.5 }, alias: ['鱼', '生鱼', '淡水鱼'],
    hg: 12.5, hp: 1, sa: 0, perish: 3, pair: 'fish_cooked',
    source: '钓鱼、海钓或击杀鱼人掉落',
    tip: '联机版的淡水鱼：0.5 肉度 + 0.5 鱼度（单机版是 1 肉度）。海鲜牛排要凑满 2.5 肉度 + 1.5 鱼度，光靠它得放好几条。' },
  { id: 'small_fish', cn: '小鱼块', en: 'Fish Morsel', img: 'ing_small_fish.png', cat: 'raw', tags: { meat: 0.5, fish: 0.5 },
    hg: 12.5, hp: 1, sa: 0, perish: 3, pair: 'small_fish_cooked',
    source: '海钓 / 钓小鱼的常见收获',
    tip: '0.5 肉 + 0.5 鱼，海鲜浓汤、鱼塔可的常用料。' },
  { id: 'eel', cn: '鳗鱼', en: 'Eel', img: 'ing_eel.png', cat: 'raw', tags: { meat: 0.5, fish: 1 },
    hg: 9.375, hp: 3, sa: 0, perish: 6, pair: 'eel_cooked',
    source: '洞穴泥潭 / 鳗鱼池钓鱼获得',
    tip: '1 点鱼度 + 0.5 肉度，鳗鱼饭（+20 血）的指定材料；也是凑鱼度的效率之选。' },
  { id: 'lobster', cn: '龙虾（活体）', en: 'Wobster', img: 'ing_lobster.png', cat: 'raw', tags: { meat: 1, fish: 1 },
    hg: null, hp: null, sa: null, perish: null, pair: 'lobster_cooked',
    source: '海上钓鱼 / 龙虾陷阱捕获',
    tip: '活龙虾不能直接吃：进烹饪锅（龙虾浓汤 / 龙虾正餐 / 海鲜牛排）或直接烤成「美味龙虾」。' },
  { id: 'barnacle', cn: '藤壶', en: 'Barnacles', img: 'ing_barnacle.png', cat: 'raw', tags: { meat: 0.25, fish: 0.25 },
    hg: 12.5, hp: 0, sa: -5, perish: 6, pair: 'barnacle_cooked',
    source: '海面礁石上敲取',
    tip: '各 0.25 肉度 / 鱼度，量小但好拿；藤壶意面、藤壶握寿司都靠它。' },

  /* ==================== 蛋 / 甜 / 乳 / 冰 ==================== */
  { id: 'egg', cn: '鸟蛋', en: 'Egg', img: 'ing_egg.png', cat: 'raw', tags: { egg: 1 }, alias: ['蛋'],
    hg: 9.375, hp: 0, sa: 0, perish: 10, pair: 'egg_cooked',
    source: '鸟笼里喂鸟食物换取，或击杀鸟类',
    tip: '1 点蛋度；培根煎蛋、波兰水饺的常客。' },
  { id: 'tallbird_egg', cn: '高脚鸟蛋', en: 'Tallbird Egg', img: 'ing_tallbird_egg.png', cat: 'raw', tags: { egg: 4 },
    hg: 25, hp: 3, sa: 0, perish: null, pair: 'tallbird_egg_cooked',
    source: '从高脚鸟巢里偷（小心大鸟追你）',
    tip: '1 个顶 4 点蛋度，苏格兰蛋（150 饥饿 / 60 血）就靠它。' },
  { id: 'honey', cn: '蜂蜜', en: 'Honey', img: 'ing_honey.png', cat: 'raw', tags: { sweet: 1 },
    hg: 9.375, hp: 3, sa: 0, perish: 40,
    source: '野外蜂巢 / 自家蜂箱采集',
    tip: '1 点甜度、保质期长达 40 天，是太妃糖、蜜汁火腿、南瓜饼干的核心。' },
  { id: 'royal_jelly', cn: '蜂王浆', en: 'Royal Jelly', img: 'Royal_Jelly.png', cat: 'raw', tags: { sweet: 3 },
    hg: null, hp: null, sa: null, perish: null,
    source: '击败蜂王（Bee Queen）掉落',
    tip: '3 点甜度，是彩虹糖豆（2 分钟持续回血 120）的唯一材料。' },
  { id: 'butter', cn: '黄油', en: 'Butter', img: 'ing_butter.png', cat: 'raw', tags: { dairy: 1, fat: 1 },
    hg: 25, hp: 40, sa: 0, perish: 40,
    source: '击杀蝴蝶 / 蜜蜂的极小概率掉落',
    tip: '1 点乳制品度 + 1 点油脂度；华夫饼、冰淇淋、龙虾正餐都要它，稀有物。' },
  { id: 'electric_milk', cn: '带电的羊奶', en: 'Electric Milk', img: 'Electric_Milk.png', cat: 'raw', tags: { dairy: 1 },
    hg: 12.5, hp: 3, sa: 10, perish: 6,
    source: '给伏特山羊挤奶（先喂它吃东西）',
    tip: '1 点乳制品度，可替代黄油做冰淇淋类料理。' },
  { id: 'ice', cn: '冰块', en: 'Ice', img: 'Ice.png', cat: 'raw', tags: { frozen: 1 },
    hg: 2.34375, hp: 0.5, sa: 0, perish: 3,
    source: '冬季结冰的水面 / 冰矿敲取',
    tip: '1 点冰度：既是冰淇淋、香蕉冻的材料，也是夏天降温料理的关键，还能当冰箱外的填充物。' },

  /* ==================== 不可食用 / 调味 / 装饰 ==================== */
  { id: 'twigs', cn: '树枝', en: 'Twigs', img: 'Twigs.png', cat: 'misc', tags: { inedible: 1 },
    hg: 9.375, hp: 0.5, sa: 0, perish: null, restricted: true,
    source: '树苗采集',
    tip: '1 点不可食用度：玩家自己不能吃（牛和饼干切割机可以）。炸鱼排、肉串、精致螺旋土豆都要它。' },
  { id: 'forget_me_not', cn: '勿忘我', en: 'Forget-Me-Lots', img: 'ing_forget_me_not.png', cat: 'misc', tags: { decoration: 1 },
    hg: null, hp: null, sa: null, perish: null,
    source: '野外花丛区域采集',
    tip: '1 点装饰度，舒缓茶与皮弗娄牛零食的指定材料。' },
  { id: 'butterfly_wing', cn: '蝴蝶翅膀', en: 'Butterfly Wings', img: 'ing_butterfly_wing.png', cat: 'misc', tags: { decoration: 2 },
    hg: 9.375, hp: 8, sa: 0, perish: 6,
    source: '击杀蝴蝶掉落',
    tip: '2 点装饰度；蝴蝶松饼的指定材料，生吃也能回 8 血，开局几天的救命食品。' },
  { id: 'moon_moth_wing', cn: '月蛾翅膀', en: 'Moon Moth Wings', img: 'Moon_Moth_Wings.png', cat: 'misc', tags: { decoration: 2 },
    hg: 9.375, hp: 8, sa: 15, perish: 6,
    source: '击杀月蛾掉落',
    tip: '可以替代蝴蝶翅膀做蝴蝶松饼；生吃还额外回 15 理智。' },
  { id: 'birchnut', cn: '桦栗果', en: 'Birchnut', img: 'Birchnut.png', cat: 'misc', tags: { seed: 1 },
    hg: null, hp: null, sa: null, perish: null, pair: 'birchnut_cooked',
    source: '砍伐桦树（桦栗树）掉落',
    tip: '生果玩家不能吃；烤过是 9.375 饥饿的小零食，什锦干果、皮弗娄牛零食的指定材料。' },
  { id: 'bone_shard', cn: '骨头碎片', en: 'Bone Shards', img: 'Bone_Shards.png', cat: 'misc', tags: { inedible: 1 }, perish: null,
    source: '敲碎骸骨 / 骷髅残骸获得',
    tip: '1 点不可食用度，骨头汤（沃利专属，150 饥饿）的核心材料。' },
  { id: 'nightmare_fuel', cn: '噩梦燃料', en: 'Nightmare Fuel', img: 'Nightmare_Fuel.png', cat: 'misc', tags: { inedible: 1, magic: 1 }, perish: null,
    source: '击杀暗影生物掉落',
    tip: '1 点不可食用度 + 1 点魔法度，恐怖国王饼（交换生命与理智）的指定材料。' },
  { id: 'volt_goat_horn', cn: '伏特羊角', en: 'Volt Goat Horn', img: 'Volt_Goat_Horn.png', cat: 'misc', tags: { inedible: 1 }, perish: null,
    source: '击杀伏特山羊掉落',
    tip: '1 点不可食用度，伏特羊肉冻（攻击附带电击）的指定材料。' },

  /* ==================== 火烤 / 轻加工 ==================== */
  { id: 'carrot_cooked', cn: '烤胡萝卜', en: 'Roasted Carrot', img: 'ing_carrot_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 12.5, hp: 3, sa: 0, perish: 6, pair: 'carrot',
    source: '胡萝卜在营火 / 火坑上烤制', tip: '回血从 1 变 3，但保质期从 10 天缩短到 6 天。' },
  { id: 'corn_cooked', cn: '爆米花', en: 'Popcorn', img: 'Popcorn.png', cat: 'roast', tags: { veggie: 1 },
    hg: 12.5, hp: 3, sa: 0, perish: 15, pair: 'corn',
    source: '玉米烤制', tip: '饱食掉了，但保质期反而变长（15 天），适合囤。' },
  { id: 'pumpkin_cooked', cn: '烤南瓜', en: 'Hot Pumpkin', img: 'ing_pumpkin_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 37.5, hp: 8, sa: 0, perish: 6, pair: 'pumpkin',
    source: '南瓜烤制', tip: '回血翻倍到 8，是素食里饱食最高的加热版本。' },
  { id: 'eggplant_cooked', cn: '烤茄子', en: 'Braised Eggplant', img: 'ing_eggplant_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 25, hp: 20, sa: 0, perish: 6, pair: 'eggplant',
    source: '茄子烤制', tip: '回血从 8 直接跳到 20，性价比很高。' },
  { id: 'asparagus_cooked', cn: '烤芦笋', en: 'Roasted Asparagus', img: 'ing_asparagus_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 25, hp: 3, sa: 0, perish: 3, pair: 'asparagus',
    source: '芦笋烤制', tip: '饱食 12.5 → 25，翻倍。' },
  { id: 'onion_cooked', cn: '烤洋葱', en: 'Roasted Onion', img: 'ing_onion_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 9.375, hp: 1, sa: -5, perish: 10, pair: 'onion',
    source: '洋葱烤制', tip: '理智惩罚从 −10 减到 −5，还能回 1 血。' },
  { id: 'garlic_cooked', cn: '烤大蒜', en: 'Roast Garlic', img: 'ing_garlic_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 9.375, hp: 1, sa: -5, perish: 10, pair: 'garlic',
    source: '大蒜烤制', tip: '同上：理智惩罚减半。' },
  { id: 'tomato_cooked', cn: '烤番茄', en: 'Roasted Toma Root', img: 'ing_tomato_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 12.5, hp: 20, sa: 0, perish: 10, pair: 'tomato',
    source: '番茄烤制', tip: '饱食不变，主要是可以顺手加热。' },
  { id: 'potato_cooked', cn: '烤土豆', en: 'Roasted Potato', img: 'ing_potato_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 25, hp: 20, sa: 0, perish: 6, pair: 'potato',
    source: '土豆烤制', tip: '从「生吃扣血」变成 20 血 / 25 饥饿的优质食物，也是沃尔夫冈的喜爱料理（×1.6）。' },
  { id: 'pepper_cooked', cn: '烤辣椒', en: 'Roasted Pepper', img: 'ing_pepper_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 9.375, hp: -3, sa: -10, perish: 15, pair: 'pepper',
    source: '辣椒烤制', tip: '血量惩罚从 −20 减到 −3。' },
  { id: 'cactus_flesh_cooked', cn: '熟仙人掌肉', en: 'Cooked Cactus Flesh', img: 'ing_cactus_flesh_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 12.5, hp: 1, sa: 15, perish: 10, pair: 'cactus_flesh',
    source: '仙人掌肉烤制', tip: '从 −5 理智变成 +15 理智，沙漠流必备。' },
  { id: 'kelp_cooked', cn: '熟海带叶', en: 'Cooked Kelp Fronds', img: 'ing_kelp_cooked.png', cat: 'roast', tags: { veggie: 0.5 },
    hg: 9.375, hp: 0, sa: -5, perish: 10, pair: 'kelp',
    source: '海带叶烤制', tip: '食物度不变，主要是给牛当饲料或做料理。' },
  { id: 'stone_fruit_cooked', cn: '熟石果', en: 'Cooked Stone Fruit', img: 'ing_stone_fruit_cooked.png', cat: 'roast', tags: { veggie: 1 },
    hg: 12.5, hp: 3, sa: 0, perish: 2, pair: 'stone_fruit_ripe',
    source: '成熟石果烤制', tip: '鳄梨酱可以用它替代仙人掌肉。' },
  { id: 'mandrake_cooked', cn: '熟曼德拉草', en: 'Cooked Mandrake', img: 'ing_mandrake_cooked.png', cat: 'roast', tags: { veggie: 1, magic: 1 },
    hg: 150, hp: 100, sa: 0, perish: null, pair: 'mandrake',
    source: '曼德拉草烤制', tip: '全游戏最强的直接恢复食物：150 饥饿 / 100 血。' },
  { id: 'mushroom_red_cooked', cn: '烤红蘑菇', en: 'Roasted Red Cap', img: 'ing_mushroom_red_cooked.png', cat: 'roast', tags: { veggie: 0.5 },
    hg: 0, hp: 1, sa: -10, perish: 10, pair: 'mushroom_red',
    source: '红蘑菇烤制', tip: '不再扣血，但也不顶饱，还扣 10 理智。' },
  { id: 'mushroom_green_cooked', cn: '烤绿蘑菇', en: 'Roasted Green Cap', img: 'ing_mushroom_green_cooked.png', cat: 'roast', tags: { veggie: 0.5 },
    hg: 0, hp: -1, sa: 15, perish: 10, pair: 'mushroom_green',
    source: '绿蘑菇烤制', tip: '著名的「回理智神器」：+15 理智。' },
  { id: 'mushroom_blue_cooked', cn: '烤蓝蘑菇', en: 'Roasted Blue Cap', img: 'ing_mushroom_blue_cooked.png', cat: 'roast', tags: { veggie: 0.5 },
    hg: 0, hp: -3, sa: 10, perish: 10, pair: 'mushroom_blue',
    source: '蓝蘑菇烤制', tip: '变成 +10 理智，代价是扣 3 血。' },
  { id: 'mushroom_lunar_cooked', cn: '熟月亮蘑菇', en: 'Cooked Moon Shroom', img: 'ing_mushroom_lunar_cooked.png', cat: 'roast', tags: { veggie: 0.5 },
    hg: null, hp: null, sa: null, perish: null, pair: 'mushroom_lunar',
    source: '月亮蘑菇烤制', tip: '数值各版本有差异，蘑菇蛋糕 / 酿蘑菇盖用它。' },
  { id: 'berries_cooked', cn: '烤浆果', en: 'Roasted Berries', img: 'ing_berries_cooked.png', cat: 'roast', tags: { fruit: 0.5 },
    hg: 12.5, hp: 1, sa: 0, perish: 3, pair: 'berries',
    source: '浆果烤制', tip: '12.5 饥饿 + 1 血，但只有 3 天保质期，现烤现吃。' },
  { id: 'berries_juicy_cooked', cn: '烤多汁浆果', en: 'Roasted Juicy Berries', img: 'ing_berries_juicy_cooked.png', cat: 'roast', tags: { fruit: 0.5 },
    hg: 18.75, hp: 3, sa: 0, perish: 1, pair: 'berries_juicy',
    source: '多汁浆果烤制', tip: '18.75 饥饿，是水果里最高的生熟对比之一，但只能放 1 天。' },
  { id: 'pomegranate_cooked', cn: '切片熟石榴', en: 'Sliced Pomegranate', img: 'ing_pomegranate_cooked.png', cat: 'roast', tags: { fruit: 1 },
    hg: 12.5, hp: 20, sa: 0, perish: 3, pair: 'pomegranate',
    source: '石榴烤制', tip: '回血从 3 变 20，是水果里最好的「血包」。' },
  { id: 'dragonfruit_cooked', cn: '火龙果切片', en: 'Prepared Dragon Fruit', img: 'ing_dragonfruit_cooked.png', cat: 'roast', tags: { fruit: 1 },
    hg: 12.5, hp: 20, sa: 0, perish: 3, pair: 'dragonfruit',
    source: '火龙果烤制', tip: '回血 20；不过做火龙果派更划算。' },
  { id: 'watermelon_cooked', cn: '烤西瓜', en: 'Roasted Watermelon', img: null, cat: 'roast', tags: { fruit: 1 },
    hg: 12.5, hp: 1, sa: 7.5, perish: 3, pair: 'watermelon',
    source: '西瓜烤制', tip: '理智收益更高，但西瓜通常直接吃或做成西瓜冰棍。' },
  { id: 'durian_cooked', cn: '超臭榴莲', en: 'Extra Smelly Durian', img: 'ing_durian_cooked.png', cat: 'roast', tags: { fruit: 1, monster: 1 },
    hg: 25, hp: 0, sa: -5, perish: 6, pair: 'durian',
    source: '榴莲烤制', tip: '不再扣血，但还是 −5 理智，怪物度依然存在。' },
  { id: 'banana_cooked', cn: '熟香蕉', en: 'Cooked Banana', img: 'ing_banana_cooked.png', cat: 'roast', tags: { fruit: 1 },
    hg: 12.5, hp: 3, sa: 0, perish: 6, pair: 'banana',
    source: '香蕉烤制', tip: '回血 3 点；沃姆伍德的喜爱食物（×2.2）。' },
  { id: 'fig_cooked', cn: '熟无花果', en: 'Cooked Fig', img: 'ing_fig_cooked.png', cat: 'roast', tags: { fruit: 0.5 },
    hg: 18.75, hp: 1, sa: 0, perish: 3, pair: 'fig',
    source: '无花果烤制', tip: '0.5 水果度但饱食 18.75，效率很高。' },
  { id: 'meat_big_cooked', cn: '烤大肉', en: 'Cooked Meat', img: 'ing_meat_big_cooked.png', cat: 'roast', tags: { meat: 1 },
    hg: 25, hp: 3, sa: 0, perish: 10, pair: 'meat_big',
    source: '大肉在营火 / 火坑上烤制',
    tip: '不再扣理智，保质期从 6 天翻到 10 天，是「大肉的正确吃法」。' },
  { id: 'meat_small_cooked', cn: '烤小肉', en: 'Cooked Morsel', img: 'ing_meat_small_cooked.png', cat: 'roast', tags: { meat: 0.5 },
    hg: 12.5, hp: 1, sa: 0, perish: 10, pair: 'meat_small',
    source: '小肉烤制', tip: '回 1 血、不扣理智，保质期 10 天。' },
  { id: 'monster_meat_cooked', cn: '烤怪物肉', en: 'Cooked Monster Meat', img: 'ing_monster_meat_cooked.png', cat: 'roast', tags: { meat: 1, monster: 1 },
    hg: 18.75, hp: -3, sa: -10, perish: 15, pair: 'monster_meat',
    source: '怪物肉烤制', tip: '惩罚从 −20 血 / −15 理智降到 −3 血 / −10 理智，保质期 15 天。' },
  { id: 'drumstick_cooked', cn: '烤鸡腿', en: 'Fried Drumstick', img: 'ing_drumstick_cooked.png', cat: 'roast', tags: { meat: 0.5 },
    hg: 12.5, hp: 1, sa: 0, perish: 10, pair: 'drumstick',
    source: '鸡腿烤制', tip: '不扣理智，回 1 血。' },
  { id: 'frog_leg_cooked', cn: '烤蛙腿', en: 'Cooked Frog Leg', img: 'ing_frog_leg_cooked.png', cat: 'roast', tags: { meat: 0.5 },
    hg: 12.5, hp: 1, sa: 0, perish: 10, pair: 'frog_leg',
    source: '蛙腿烤制', tip: '和小肉一样：12.5 饥饿 / 1 血 / 10 天。' },
  { id: 'bat_wing_cooked', cn: '烤蝙蝠翅膀', en: 'Cooked Batilisk Wing', img: 'ing_bat_wing_cooked.png', cat: 'roast', tags: { meat: 0.5 },
    hg: 18.75, hp: 8, sa: 0, perish: 10, pair: 'bat_wing',
    source: '蝙蝠翅膀烤制', tip: '18.75 饥饿 + 8 血，比生吃好太多。' },
  { id: 'leafy_meat_cooked', cn: '熟叶肉', en: 'Cooked Leafy Meat', img: 'ing_leafy_meat_cooked.png', cat: 'roast', tags: { meat: 1 },
    hg: 18.75, hp: 1, sa: 0, perish: 10, pair: 'leafy_meat',
    source: '叶肉烤制', tip: '饱食升到 18.75、不扣理智。' },
  { id: 'koalefant_trunk_cooked', cn: '烤象鼻（象鼻排）', en: 'Roasted Koalefant Trunk', img: 'ing_koalefant_trunk_cooked.png', cat: 'roast', tags: { meat: 1 },
    hg: 75, hp: 40, sa: 0, perish: 15, pair: 'koalefant_trunk',
    source: '考拉象鼻烤制', tip: '75 饥饿 / 40 血 / 15 天，象鼻最省事的用法。' },
  { id: 'fish_cooked', cn: '烤鱼', en: 'Cooked Fish', img: 'ing_fish_cooked.png', cat: 'roast', tags: { meat: 1, fish: 1 },
    hg: 12.5, hp: 1, sa: 0, perish: 6, pair: 'fish',
    source: '鱼烤制', tip: '保质期从 3 天延长到 6 天。' },
  { id: 'small_fish_cooked', cn: '熟小鱼块', en: 'Cooked Fish Morsel', img: 'ing_small_fish_cooked.png', cat: 'roast', tags: { meat: 0.5, fish: 0.5 },
    hg: 12.5, hp: 1, sa: 0, perish: 6, pair: 'small_fish',
    source: '小鱼块烤制', tip: '保质期翻倍，适合临时保存。' },
  { id: 'eel_cooked', cn: '熟鳗鱼', en: 'Cooked Eel', img: 'ing_eel_cooked.png', cat: 'roast', tags: { meat: 0.5, fish: 1 },
    hg: 12.5, hp: 8, sa: 0, perish: 10, pair: 'eel',
    source: '鳗鱼烤制', tip: '饱食 9.375 → 12.5。' },
  { id: 'lobster_cooked', cn: '美味龙虾（烤熟）', en: 'Delicious Wobster', img: 'ing_lobster_cooked.png', cat: 'roast', tags: { meat: 1, fish: 1 },
    hg: 12.5, hp: 1, sa: 0, perish: 6, pair: 'lobster',
    source: '龙虾烤制', tip: '活龙虾烤熟后的样子。杀死活龙虾会先得到「死龙虾」（同样 12.5 饥 / 1 血，但只保 3 天、不能进锅），烤熟后保质 6 天。' },
  { id: 'barnacle_cooked', cn: '熟藤壶', en: 'Cooked Barnacles', img: 'ing_barnacle_cooked.png', cat: 'roast', tags: { meat: 0.25, fish: 0.25 },
    hg: 12.5, hp: 1, sa: 0, perish: 15, pair: 'barnacle',
    source: '藤壶烤制', tip: '食物度不变（各 0.25），但保质期从 6 天翻到 15 天，还回 1 血。' },
  { id: 'egg_cooked', cn: '煎蛋（熟鸟蛋）', en: 'Cooked Egg', img: 'ing_egg_cooked.png', cat: 'roast', tags: { egg: 1 },
    hg: 12.5, hp: 0, sa: 0, perish: 6, pair: 'egg',
    source: '鸟蛋烤制', tip: '饱食 9.375 → 12.5，但保质期从 10 天缩到 6 天。' },
  { id: 'tallbird_egg_cooked', cn: '煎高脚鸟蛋', en: 'Fried Tallbird Egg', img: 'ing_tallbird_egg_cooked.png', cat: 'roast', tags: { egg: 4 },
    hg: 37.5, hp: 0, sa: 0, perish: 6, pair: 'tallbird_egg',
    source: '高脚鸟蛋烤制', tip: '37.5 饥饿 / 4 蛋度，但保质期只有 6 天。' },
  { id: 'birchnut_cooked', cn: '烤桦栗果', en: 'Roasted Birchnut', img: 'ing_birchnut_cooked.png', cat: 'roast', tags: { seed: 1 },
    hg: 9.375, hp: 1, sa: 0, perish: 6, pair: 'birchnut',
    source: '桦栗果烤制', tip: '生果不能吃，烤过才能吃；什锦干果的指定材料。' },

  /* ==================== 晾晒（晾肉架） ==================== */
  { id: 'meat_big_dry', cn: '大肉干', en: 'Jerky', img: 'ing_meat_big_dry.png', cat: 'dry', tags: { meat: 1 },
    hg: 25, hp: 20, sa: 15, perish: 20,
    source: '大肉放在晾肉架上晾晒',
    tip: '保质期 20 天，还是唯一「同时回血又回理智」的肉类，长途探索必备。' },
  { id: 'meat_small_dry', cn: '小肉干', en: 'Small Jerky', img: 'ing_meat_small_dry.png', cat: 'dry', tags: { meat: 0.5 },
    hg: 12.5, hp: 8, sa: 10, perish: 20,
    source: '小肉 / 鸡腿 / 蛙腿等放在晾肉架上晾晒',
    tip: '0.5 肉度、20 天保质期，回理智的好零食。' },
  { id: 'monster_meat_dry', cn: '怪物肉干', en: 'Monster Jerky', img: 'ing_monster_meat_dry.png', cat: 'dry', tags: { meat: 1, monster: 1 },
    hg: 18.75, hp: -3, sa: -5, perish: 20,
    source: '怪物肉放在晾肉架上晾晒',
    tip: '负惩罚最小的怪物肉形态，也是唯一能跟猪王换金块的形式。' },
  { id: 'small_fish_dry', cn: '小鱼干', en: 'Small Fishy Jerky', img: 'ing_small_fish_dry.png', cat: 'dry', tags: { meat: 0.5, fish: 0.5 },
    hg: 12.5, hp: 15, sa: 20, perish: 15,
    source: '小鱼块放在晾肉架上晾晒',
    tip: '回血 15 + 回理智 20，是实惠的「心情血包」。' }
];
