/* ============================================================
   饥荒联机版百科 · 资源数据 (js/materials.js)
   收录从世界里获得的材料，以及生物、植物、地段、矿物和岛屿资源。
   能制作的东西在 js/items.js（「制作」页）。
   src / note 文案按官方维基的联机版词条整理（2026-09）；
   alias 用于让「制作」页配方里的旧写法也能链到这里。
   ============================================================ */
const MAT_CATS = {
  plant: { cn: '植物 · 木材' },
  ore:   { cn: '矿石 · 宝石' },
  mob:   { cn: '生物掉落' },
  boss:  { cn: '巨兽掉落' },
  magic: { cn: '魔法 · 远古' },
  misc:  { cn: '其他资源' },
  biome: { cn: '群系' },
  mineral: { cn: '矿脉 · 矿物点' },
  island: { cn: '岛屿' },
  structure: { cn: '建筑' }
};

const MATERIALS = [
  /* ---------------- 植物 · 木材 ---------------- */
  { id: 'log', cn: '木头', en: 'Log', img: 'Log.png', cat: 'plant', alias: ['原木'],
    src: '用斧头砍倒常青树、桦栗树、多枝树等各类树木获得；也能用威尔逊的炼金「转化」把 3 个树枝变成 1 个木头。',
    note: '精炼成木板（4 个木头）后能做家具、地板和大量建筑，是最基础的材料。' },
  { id: 'twigs', cn: '树枝', en: 'Twigs', img: 'Twigs.png', cat: 'plant', alias: ['树枝'],
    src: '砍伐地上的树苗（Sapling）或直接捡拾；桦栗树、多枝树、洞穴香蕉树也会掉。威尔逊可用 1 个木头换 2 个树枝。',
    note: '造工具、火堆、陷阱都要它；当燃料也行，但很浪费。' },
  { id: 'cut_grass', cn: '草', en: 'Cut Grass', img: 'Cut_Grass.png', cat: 'plant', alias: ['割下的草', '采下的草'],
    src: '采摘草地上的草丛（Grass Tuft）获得；草丛会被采秃，用铲子连根挖走就能移植到基地旁边。',
    note: '做绳子、火把、草席、蜂箱都靠它，后期建议在基地旁种一片草丛。' },
  { id: 'cut_reeds', cn: '芦苇', en: 'Cut Reeds', img: 'Cut_Reeds.png', cat: 'plant', alias: ['割下的芦苇', '切割芦苇'],
    src: '在沼泽里采摘芦苇获得；同样能用铲子连根挖走移植。',
    note: '莎草纸、吹箭、乐器等都要用芦苇。' },
  { id: 'living_log', cn: '活木', en: 'Living Log', img: 'Living_Log.png', cat: 'plant', alias: ['活木头'],
    src: '砍伐「完全正常的树」获得，击杀树精守卫也会掉；多枝树与蘑菇地精同样会产出。',
    note: '种「完全正常的树」需要吃下它的种子，属于比较耗资源的可再生方式。' },
  { id: 'charcoal', cn: '木炭', en: 'Charcoal', img: 'Charcoal.png', cat: 'plant',
    src: '把树烧掉后捡拾地上留下的焦木；烧掉的猪火炬、火坑等可燃结构也会留下木炭。',
    note: '火药、吹箭、羽毛笔等都要它；下雨天烧树比较安全。' },
  { id: 'petals', cn: '花瓣', en: 'Petals', img: 'Petals.png', cat: 'plant',
    src: '采摘野花获得；花朵会随季节在空地上重新长出。',
    note: '可以做花环提理智，也能当燃料，但腐坏得很快（3 天）。' },
  { id: 'dark_petals', cn: '恶魔花瓣', en: 'Dark Petals', img: 'Dark_Petals.png', cat: 'plant', alias: ['深色花瓣', '暗色花瓣'],
    src: '采摘邪恶花（Evil Flower）获得；也可能从风滚草、沉船交易获得。',
    note: '4 个恶魔花瓣能在灵子分解器或暗影操纵者旁合成 1 个噩梦燃料。' },
  { id: 'light_bulb', cn: '荧光果', en: 'Light Bulb', img: 'Light_Bulb.png', cat: 'plant',
    src: '在洞穴里采摘荧光花（Light Flower）获得。',
    note: '矿工帽、荧光灯一类照明装备的常用材料，也能吃（回一点饥饿）。' },
  { id: 'foliage', cn: '蕨叶', en: 'Foliage', img: 'Foliage.png', cat: 'plant', alias: ['叶片'],
    src: '采摘蕨类植物（Fern）获得，地表与洞穴都有。',
    note: '属于蔬菜，可以吃也能当肥料；一些装饰类制作会用到。' },
  { id: 'pine_cone', cn: '松果', en: 'Pine Cone', img: 'Pine_Cone.png', cat: 'plant',
    src: '砍伐常青树获得，森林地表上也常能捡到。',
    note: '种回土里能长成新的常青树，是木材的主要再生手段；也能当燃料。' },
  { id: 'birchnut', cn: '桦栗果', en: 'Birchnut', img: 'Birchnut.png', cat: 'plant',
    src: '砍伐桦栗树获得。',
    note: '烤熟后可以吃，也能种回土里长出新的桦栗树。' },
  { id: 'driftwood', cn: '浮木', en: 'Driftwood Piece', img: 'Driftwood_Piece.png', cat: 'plant', alias: ['浮木块'],
    src: '海面漂浮的浮木可用船撞开收集；月岛岩石海滩也有漂浮木资源。砍倒漂浮木树并挖树桩可获得浮木块与树枝。',
    note: '联机版海洋与月岛的重要材料，可制作浮木桨、钓具容器等；月岛的漂浮木树不会再生。' },
  { id: 'kelp_fronds', cn: '海带叶', en: 'Kelp Fronds', img: 'ing_kelp.png', cat: 'plant', alias: ['海带'],
    src: '采摘海洋中的海带或岩石海滩上搁浅的海带获得；海洋漂浮物也可能开出海带叶。',
    note: '可生吃、烤制或晒成干海带；是加州卷等料理和多种海洋制作的材料。查看「海带」条目可了解生长地点。' },
  { id: 'barnacle', cn: '藤壶', en: 'Barnacles', img: 'ing_barnacle.png', cat: 'plant', alias: ['藤壶肉'],
    src: '在岩石海滩、海带区等海岸的藤壶岩上采集；使用镐子开采藤壶岩也能获得。',
    note: '生藤壶既是料理食材，也是海洋制作材料；烤熟后称为熟藤壶。' },
  { id: 'broken_shell', cn: '破碎贝壳', en: 'Broken Shell', img: 'mat_broken_shell.png', cat: 'misc', alias: ['贝壳碎片', '破碎壳'],
    src: '击杀蛞蝓龟、蜗牛龟、蟹晶（Crustashine），或摧毁蛞蝓龟巢获得；用锤子敲碎贝壳钟也会掉落。',
    note: '用于制作贝壳保险杠、贝壳沙滩地皮、种子包和装饰物；条目图标暂缺，页面会显示文字占位。' },
  { id: 'cookie_cutter_shell', cn: '饼干切割机壳', en: 'Cookie Cutter Shell', img: 'mat_cookie_cutter_shell.png', cat: 'mob', alias: ['饼干壳'],
    src: '饼干切割机必定掉落 1 个怪物肉；饼干切割机壳有 50% 概率掉落 1 个，并有额外 25% 概率再掉落 1 个。它们在海洋盐岩层附近出没。',
    note: '用于制作饼干切割机头盔、隐士搬迁器及多种鱼饵。击杀来源见「饼干切割机」详情。' },
  { id: 'lune_tree_blossom', cn: '月亮树花', en: 'Lune Tree Blossom', img: 'Lune_Tree_Blossom.png', cat: 'plant',
    src: '砍伐月树（Lune Tree）获得，月之森林的地上也能捡到。',
    note: '可以吃掉回一点饥饿，也是月亮相关制作的原料。' },

  /* ---------------- 矿石 · 宝石 ---------------- */
  { id: 'rocks', cn: '石头', en: 'Rocks', img: 'Rocks.png', cat: 'ore',
    src: '挖开地表与洞穴里的岩石（Boulder）获得，遗迹里敲碎石制结构也会掉；威尔逊能用 2 个燧石「转化」出 1 个石头。',
    note: '精炼成石砖（3 个石头）后能造石墙、熔炉等大量结构。' },
  { id: 'flint', cn: '燧石', en: 'Flint', img: 'Flint.png', cat: 'ore',
    src: '开局在地面上就能捡到，挖岩石时也会掉落；威尔逊能用 3 个石头「转化」出 1 个燧石。',
    note: '前期做斧头、镐子、长矛的基本材料。' },
  { id: 'gold_nugget', cn: '金块', en: 'Gold Nugget', img: 'Gold_Nugget.png', cat: 'ore',
    src: '挖开带金纹的岩石获得；也能用饰品和猪王交换、在远古废墟里捡到。',
    note: '科学机器、炼金引擎等科技建筑都要用；威尔逊能把 3 个硝石「转化」成 1 个金块。' },
  { id: 'nitre', cn: '硝石', en: 'Nitre', img: 'Nitre.png', cat: 'ore',
    src: '挖开光滑岩石（Smooth Boulder）获得，洞穴里也有硝石矿。',
    note: '做火药、冰帽、温度药膏等；威尔逊可以把 2 个金块「转化」回硝石。' },
  { id: 'marble', cn: '大理石', en: 'Marble', img: 'Marble.png', cat: 'ore',
    src: '挖开大理石柱、大理石雕像获得；也能用威尔逊的「转化矿石 III」把 2 个石砖变成 1 个大理石。',
    note: '大理石甲、大理石豌豆、土地庙一类制作的原料。' },
  { id: 'moon_rock', cn: '月岩', en: 'Moon Rock', img: 'Moon_Rock.png', cat: 'ore', alias: ['月亮石', '月亮岩石'],
    src: '在月岛、陨石坠落点（月坑）周围挖开月岩获得；也能用「转化矿石 III」把 2 个大理石变成 1 个月岩。',
    note: '月岩墙、月石神像等月之系列制作的材料。' },
  { id: 'thulecite', cn: '铥矿', en: 'Thulecite', img: 'Thulecite.png', cat: 'ore',
    src: '在远古伪科学站旁用 6 个铥矿碎片合成（远古类物品无法用原型解锁，必须站在站旁制作）。',
    note: '可以用来修复破损的远古伪科学站，打开更多远古配方。' },
  { id: 'thulecite_fragments', cn: '铥矿碎片', en: 'Thulecite Fragments', img: 'Thulecite_Fragments.png', cat: 'ore',
    src: '在远古废墟里敲碎铥矿相关的结构获得，破损发条生物与华丽箱子也会掉落。',
    note: '6 个碎片 = 1 个铥矿，所以进废墟前记得带镐子和锤子。' },
  { id: 'moon_shard', cn: '月亮碎片', en: 'Moon Shard', img: 'Moon_Shard.png', cat: 'ore', alias: ['月光'],
    src: '在月岛上开采天然的月亮玻璃矿石（挖一次得 2 个月亮碎片，25% 多 1 个）；击杀天体英雄、被附身座狼、水晶冠秃鹫、月光龙虾等也会掉落，神秘商人可用灰烬交换。满月时玻璃绿洲会再生。',
    note: '月光玻璃斧、月面地皮、星象护目镜等一批月之制作的材料，也是月亮虹吸器等建筑的基础材料。' },
  { id: 'salt_crystals', cn: '盐晶', en: 'Salt Crystals', img: 'Salt_Crystals.png', cat: 'ore',
    src: '在海洋里挖开 / 打碎盐层（Salt Formation）获得。',
    note: '做盐盒保鲜；直接对食材用能恢复最多 50% 的新鲜度（熟食和料理不行）。' },
  { id: 'desert_stone', cn: '沙漠石', en: 'Desert Stone', img: 'Desert_Stone.png', cat: 'ore',
    src: '用饰品、鸟蛋和蚁狮交换获得。',
    note: '自己拿着沙漠石右键可传送到正在使用「懒惰沙漠人」的队友身边，传送会消耗 50 理智。' },
  { id: 'red_gem', cn: '红宝石', en: 'Red Gem', img: 'Red_Gem.png', cat: 'ore',
    src: '挖坟墓、击杀火猎犬，洞穴的地震与石笋、遗迹里的远古雕像 / 破损发条生物 / 华丽箱子都会产出。',
    note: '火焰法杖、生命护符、噩梦夜灯等魔法制作的原料；威尔逊能用 2 个蓝宝石转化出 1 个红宝石。' },
  { id: 'blue_gem', cn: '蓝宝石', en: 'Blue Gem', img: 'Blue_Gem.png', cat: 'ore',
    src: '击杀冰猎犬，洞穴地震与石笋、遗迹里的远古雕像 / 破损发条生物 / 华丽箱子会产出。',
    note: '冰冻法杖、冰冷护符的原料；月圆时把蓝宝石放进切斯特的每个格子能把它变成雪切斯特。' },
  { id: 'purple_gem', cn: '紫宝石', en: 'Purple Gem', img: 'Purple_Gem.png', cat: 'ore',
    src: '由 1 个红宝石 + 1 个蓝宝石在灵子分解器旁合成；遗迹里也能捡到。',
    note: '暗影操纵者、传送核心等高级魔法制作的原料。' },
  { id: 'orange_gem', cn: '橙宝石', en: 'Orange Gem', img: 'Orange_Gem.png', cat: 'ore',
    src: '在遗迹里开采远古雕像、破坏破损发条生物与遗物、开启华丽箱子，或锤击远古伪科学站获得。',
    note: '懒惰采集者、懒惰探险家都要用它。' },
  { id: 'yellow_gem', cn: '黄宝石', en: 'Yellow Gem', img: 'Yellow_Gem.png', cat: 'ore',
    src: '来源同橙宝石：遗迹里开采远古雕像、破损发条生物、遗物与华丽箱子。',
    note: '魔光护符、唤星法杖的原料。' },
  { id: 'green_gem', cn: '绿宝石', en: 'Green Gem', img: 'Green_Gem.png', cat: 'ore',
    src: '来源同橙宝石 / 黄宝石：从遗迹的远古雕像、破损发条生物、遗物与华丽箱子里挖出。',
    note: '建造护符、拆解魔杖都要它。' },
  { id: 'iridescent_gem', cn: '彩虹宝石', en: 'Iridescent Gem', img: 'Iridescent_Gem.png', cat: 'ore',
    src: '用拆解魔杖拆解月亮使者之杖、在远古档案的华丽基座上拾取，或让威尔逊用六色宝石各 1 个转化而成。',
    note: '可以启动远古档案；喂给岩石龙虾 / 蛞蝓龟会直接吃掉，别乱放。' },

  /* ---------------- 生物掉落 ---------------- */
  { id: 'pig_skin', cn: '猪皮', en: 'Pig Skin', img: 'Pig_Skin.png', cat: 'mob',
    src: '击杀猪人、疯猪、猪人守卫掉落；用锤子敲猪人房、猪头，或用拆解魔杖拆掉它们也能拿到。',
    note: '小猪包、夏季背心、弹药袋等一批装备的原料，猪人房是稳定刷法。' },
  { id: 'tentacle_spots', cn: '触手皮', en: 'Tentacle Spots', img: 'Tentacle_Spots.png', cat: 'mob',
    src: '击杀触手有 20% 掉落，击杀大触手（触虫）有 40% 掉落。',
    note: '羽毛帽、触手相关的书籍与装备要用；本身不会腐坏，也能当燃料。' },
  { id: 'silk', cn: '蜘蛛丝', en: 'Silk', img: 'Silk.png', cat: 'mob', alias: ['丝', '蛛丝', '蜘蛛网'],
    src: '击杀各类蜘蛛、摧毁蜘蛛巢掉落，是最常见的可再生素材之一。',
    note: '高礼帽、回旋镖、冬帽、捕虫网、捕鸟陷阱等都要丝。' },
  { id: 'spider_gland', cn: '蜘蛛腺体', en: 'Spider Gland', img: 'Spider_Gland.png', cat: 'mob',
    src: '击杀各类蜘蛛掉落。',
    note: '做成治疗药膏回血；也能当燃料，紧急时直接吃可以回一点血但会掉理智。' },
  { id: 'beefalo_wool', cn: '野牛毛', en: 'Beefalo Wool', img: 'Beefalo_Wool.png', cat: 'mob', alias: ['牛毛'],
    src: '击杀野牛 / 小野牛掉落；更划算的做法是等野牛睡着后用剃刀剃毛。',
    note: '冬帽、野牛帽、马鞍、羽绒背心、地毯地板都要它，剃毛是可持续来源。' },
  { id: 'beefalo_horn', cn: '皮弗娄牛角', en: 'Beefalo Horn', img: 'Beefalo_Horn.png', cat: 'mob', alias: ['牛角'],
    src: '击杀野牛有 33% 掉落。',
    note: '吹响后当天最多能让 5 头成年野牛跟着你走，方便把牛群赶进围栏。' },
  { id: 'hound_s_tooth', cn: '犬牙', en: "Hound's Tooth", img: "Hound's_Tooth.png", cat: 'mob', alias: ['猎犬牙'],
    src: '击杀猎犬、火猎犬、冰猎犬、座狼等掉落。',
    note: '缝纫包、火焰吹箭、格纹背心的原料；威尔逊能把 2 个骨头碎片「转化」成 1 个犬牙。' },
  { id: 'bone_shards', cn: '骨头碎片', en: 'Bone Shards', img: 'Bone_Shards.png', cat: 'mob', alias: ['骨片', '碎骨'],
    src: '用锤子敲击地上的骷髅骨架获得；也能用威尔逊的「转化秽物 III」把 2 个犬牙变成 1 个骨头碎片。',
    note: '马鞍角等配方的原料；骸骨堆和猎犬丘陵附近很多，顺手就攒够了。' },
  { id: 'beard_hair', cn: '胡须', en: 'Beard Hair', img: 'Beard_Hair.png', cat: 'mob', alias: ['胡须毛发'],
    src: '用剃刀剃威尔逊的胡子（胡子越长给得越多）；理智低于 40% 时击杀胡须兔、胡须领主也会掉。',
    note: '复活雕像、伯尼、胡子地毯都要它；也能当燃料。' },
  { id: 'beeswax', cn: '蜂蜡', en: 'Beeswax', img: 'Beeswax.png', cat: 'mob',
    src: '用 1 个蜂窝在炼金引擎旁加工而成（蜂蜡本身不是掉落物）。',
    note: '蜡纸、防腐喷雾、战斗号角罐等要它。' },
  { id: 'honeycomb', cn: '蜂窝', en: 'Honeycomb', img: 'Honeycomb.png', cat: 'mob',
    src: '打碎蜂巢、杀人蜂巢获得（把蜂窝烧掉只会得到灰烬，别用火烧）。',
    note: '造蜂箱、加工蜂蜡的主要材料；本身不能吃，但进锅可以当甜味 / 填充。' },
  { id: 'stinger', cn: '螫针', en: 'Stinger', img: 'Stinger.png', cat: 'mob', alias: ['蜂刺'],
    src: '击杀蜜蜂、杀人蜂掉落（用捕虫网抓住后在背包里杀掉也算）。',
    note: '睡眠吹箭、强心针等要它。' },
  { id: 'mosquito_sack', cn: '蚊子血囊', en: 'Mosquito Sack', img: 'Mosquito_Sack.png', cat: 'mob', alias: ['蚊子血袋', '血囊'],
    src: '击杀蚊子有 50% 掉落。',
    note: '可以给自己或生物输血回血，效果和蜘蛛腺体类似；易燃。' },
  { id: 'gears', cn: '齿轮', en: 'Gears', img: 'Gears.png', cat: 'mob',
    src: '击杀破损发条生物（骑士 / 主教 / 战车）掉落，挖坟墓也有小概率挖到。',
    note: '冰箱、留声机、雪球发射机都要它；WX-78 可以直接吃齿轮提升属性上限。' },
  { id: 'thick_fur', cn: '厚皮毛', en: 'Thick Fur', img: 'Thick_Fur.png', cat: 'mob', alias: ['薄皮毛'],
    src: '击杀熊獾（秋季巨兽）掉落；也能用拆解魔杖拆掉冬熊背心回收。',
    note: '冬熊背心、冬眠背心等保暖装备的材料。' },
  { id: 'volt_goat_horn', cn: '伏特羊角', en: 'Volt Goat Horn', img: 'Volt_Goat_Horn.png', cat: 'mob',
    src: '击杀伏特羊有 25% 掉落。',
    note: '晨星棒、天气棒都要它，所以伏特羊值得专门养一群。' },
  { id: 'scales', cn: '鳞片', en: 'Scales', img: 'Scales.png', cat: 'mob', alias: ['龙鳞'],
    src: '击杀龙蝇（夏季巨兽）掉落。',
    note: '鳞甲（免疫火焰伤害）与鳞片箱（防火容器）都要它。' },
  { id: 'jet_feather', cn: '漆黑羽毛', en: 'Jet Feather', img: 'Jet_Feather.png', cat: 'mob', alias: ['黑色羽毛', '乌鸦羽毛'],
    src: '乌鸦有 50% 概率掉落；企鹅有 20% 概率掉落；秃鹫有 33% 概率掉落。',
    note: '羽毛笔、火焰吹箭、羽毛帽等制作会用到漆黑羽毛。' },
  { id: 'crimson_feather', cn: '深红羽毛', en: 'Crimson Feather', img: 'Crimson_Feather.png', cat: 'mob', alias: ['红色羽毛', '红鸟羽毛', '深红色羽毛'],
    src: '红鸟有 50% 概率掉落；也可从风滚草、浣猫等少见来源取得。',
    note: '用于羽毛帽、深红羽毛浮标及其他配方；红鸟只对应深红羽毛，不会掉天蓝或漆黑羽毛。' },
  { id: 'azure_feather', cn: '天蓝羽毛', en: 'Azure Feather', img: 'Azure_Feather.png', cat: 'mob', alias: ['蓝色羽毛', '雪雀羽毛', '雪鸟羽毛'],
    src: '雪雀有 50% 概率掉落；也可从风滚草等少见来源取得。',
    note: '用于天蓝羽毛浮标、吹箭等制作；雪雀只对应天蓝羽毛。' },
  { id: 'saffron_feather', cn: '藏红花羽毛', en: 'Saffron Feather', img: 'Saffron_Feather.png', cat: 'mob', alias: ['黄色羽毛', '藏红羽毛', '金丝雀羽毛'],
    src: '普通金丝雀有 9% 概率掉落；洞穴中毒的金丝雀在地表放生掉 5–6 根，在洞穴放生爆炸掉 1–2 根。',
    note: '用于电击吹箭及藏红羽毛浮标等制作。中毒金丝雀若被谋杀只掉腐烂物，不会掉羽毛。' },
  { id: 'glommer_wings', cn: '格罗姆之翼', en: "Glommer's Wings", img: 'mat_glommer_wings.png', cat: 'mob', alias: ['格罗姆翅膀'],
    src: '击杀格罗姆必定掉落 1 个。',
    note: '在联机版中主要用作燃料；格罗姆每次满月会重新出现。' },
  { id: 'glommer_goop', cn: '格罗姆黏液', en: "Glommer's Goop", img: "Glommer's_Goop.png", cat: 'mob', alias: ['格罗姆的黏液', '格罗姆黏液'],
    src: '格罗姆每 2–4 天定期掉落 1 个；击杀时另掉落 2 个。',
    note: '可作燃料及肥料，也用于多种制作配方；击杀格罗姆会立刻召来坎普斯。' },
  { id: 'moon_moth_wings', cn: '月蛾翅膀', en: 'Moon Moth Wings', img: 'Moon_Moth_Wings.png', cat: 'mob', alias: ['月蛾翅膀'],
    src: '击杀月蛾必定掉落 1 个。',
    note: '属于食材，可用于蝴蝶松饼等料理；与蝴蝶翅膀等价。' },
  { id: 'malbatross_feather', cn: '邪天翁羽毛', en: 'Malbatross Feather', img: 'Malbatross_Feather.png', cat: 'mob', alias: ['邪天翁羽毛'],
    src: '邪天翁战斗中受击时每次最多额外掉落 4 根（每根 5%）；死亡时掉 3–5 根，并补足到本次战斗累计 24 根。',
    note: '可制作航海装备和羽毛帆布；与漆黑、深红、天蓝等普通羽毛分属不同材料。' },
  { id: 'down_feather', cn: '麋鹿鹅羽毛', en: 'Down Feather', img: 'Down_Feather.png', cat: 'mob', alias: ['绒羽', '羽绒'],
    src: '击杀麋鹿鹅（3–5 根）或麋鹿鹅宝宝（每只 1 根）获得。',
    note: '用于豪华风扇、天气风向标等制作，不等同于乌鸦、红鸟或雪雀的普通羽毛。' },

  /* ---------------- 生物掉落 · 补充（普通生物身上拿到的物件） ----------------
     这一组是打怪 / 驱赶后掉落的实体物件，掉落文本在「生物」页，两边通过名字互相跳转。 */
  { id: 'spiderhat', cn: '蜘蛛帽', en: 'Spiderhat', img: 'Spiderhat.png', cat: 'mob', alias: ['蜘蛛帽子'],
    src: '击杀蜘蛛女王掉落 1 个。',
    note: '戴在头上的伪装：戴上后附近最多 10 只普通蜘蛛会把你当同类并跟随作战，摘下立刻翻脸；蜘蛛女王能看穿伪装。耐久只有 2 分钟，戴着时会被猪人、兔人敌视，也不能睡觉。用拆解魔杖拆掉可回收 4 个蜘蛛丝 + 2 个蜘蛛腺体 + 1 个怪物肉。' },
  { id: 'spider_eggs', cn: '蜘蛛卵', en: 'Spider Eggs', img: 'Spider_Eggs.png', cat: 'mob', alias: ['蜘蛛蛋'],
    src: '击杀蜘蛛女王掉落 1 个。',
    note: '可以种回地上长成新的蜘蛛巢，是「搬家蜘蛛」与刷蜘蛛丝的正规手段。' },
  { id: 'cat_tail', cn: '猫尾', en: 'Cat Tail', img: 'Cat_Tail.png', cat: 'mob', alias: ['猫咪尾巴', '猫尾草'],
    src: '击杀浣熊猫有 33% 概率掉落。',
    note: '用来制作猫帽、三猫尾等物品；在岩石巢穴旁给浣熊猫一份鱼肉条，还能换养一只小浣熊猫。' },
  { id: 'tam_o_shanter', cn: '苏格兰帽', en: "Tam o' Shanter", img: "Tam_o'_Shanter.png", cat: 'mob', alias: ['苏格兰圆帽'],
    src: '击杀海象（海象爸爸）有 25% 概率掉落。',
    note: '二级保暖（120 保暖值）+ 每分钟回 6.7 理智，保暖和回理智兼顾，是冬天最好用的头部装备之一；耐久 25 天，可用针线包修补。' },
  { id: 'walrus_tusk', cn: '海象牙', en: 'Walrus Tusk', img: 'Walrus_Tusk.png', cat: 'mob', alias: ['海象獠牙'],
    src: '击杀海象有 50% 概率掉落。',
    note: '做「布布棒」等武器 / 工具的材料；海象营每 2.5 天可刷一次，冬天记得常去打。' },
  { id: 'tentacle_spike', cn: '触手尖刺', en: 'Tentacle Spike', img: 'Tentacle_Spike.png', cat: 'mob', alias: ['触手钉'],
    src: '击杀触手有 50% 概率掉落；击杀大触手（触虫）也有较高概率掉落。',
    note: '前中期最强的手持武器之一（51 伤害），不能制作、只能靠打触手获得。' },
  { id: 'steel_wool', cn: '钢丝绵', en: 'Steel Wool', img: 'Steel_Wool.png', cat: 'mob', alias: ['钢丝绒'],
    src: '击杀毛怪（Ewecus）掉落 2-3 个。',
    note: '做钢丝绒枕头等物件的材料；毛怪会喷黏液把你黏住，打之前最好带远程武器。' },
  { id: 'phlegm', cn: '痰液', en: 'Phlegm', img: 'Phlegm.png', cat: 'mob', alias: ['痰', '口水', '黏液团'],
    src: '击杀毛怪（Ewecus）掉落 1-2 个。',
    note: '毛怪掉落的黏液状战利品，可以当燃料；具体数值与用途以游戏内为准。' },
  { id: 'electric_milk', cn: '电牛奶', en: 'Electric Milk', img: 'Electric_Milk.png', cat: 'mob', alias: ['带电的羊奶', '活力牛奶'],
    src: '击杀「带电状态」的伏特羊（被闪电劈中，或被晨星锤 / 电击吹箭打中）掉落 1 个。',
    note: '乳制品食材，是做冰淇淋等料理的关键材料；直接喝能回理智。想刷就养一群伏特羊，用晨星锤把它们打带电再杀。' },
  { id: 'bunny_puff', cn: '兔毛球', en: 'Bunny Puff', img: 'Bunny_Puff.png', cat: 'mob', alias: ['兔毛', '兔绒'],
    src: '击杀兔人（正常击杀）有 25% 概率掉落；理智低于 40% 时打胡须兔、胡须领主也会掉。',
    note: '毛绒类材料，可用于相关保暖与装饰制作。' },
  { id: 'shelmet', cn: '甲壳头盔', en: 'Shelmet', img: 'Shelmet.png', cat: 'mob', alias: ['蜗牛头盔'],
    src: '击杀蜗龟有 10% 概率掉落；击杀蜗牛龟也有 25% 概率掉落。',
    note: '头部护甲：525 点耐久、吸收 90% 物理伤害、20% 防潮，是吸收率最高的头部装备之一，而且可以反复刷。' },
  { id: 'snurtle_shell_armor', cn: '蜗牛壳铠甲', en: 'Snurtle Shell Armor', img: 'Snurtle_Shell_Armor.png', cat: 'mob', alias: ['蜗牛壳甲'],
    src: '击杀蜗牛龟有 75% 概率掉落。',
    note: '身体护甲：平时只吸收 60% 伤害，但右键可以缩进壳里隐藏，隐藏时完全免疫物理伤害，约 5 秒后敌人会失去兴趣——躲猎犬、躲巨兽的救命装备。' },
  { id: 'krampus_sack', cn: '坎普斯背包', en: 'Krampus Sack', img: 'Krampus_Sack.png', cat: 'mob', alias: ['克劳斯背包', '坎普斯袋子'],
    src: '击杀坎普斯有 1% 概率掉落（非常稀有）。',
    note: '容量 14 格、减速 10% 的背包，是游戏里最好用的背包；想刷就靠不断累积「罪恶值」引出坎普斯。' },
  { id: 'mourning_glory', cn: '哀悼花', en: 'Mourning Glory', img: 'Mourning_Glory.png', cat: 'mob', alias: ['悼念花', '哀悼之花'],
    src: '击杀啜泣幽魂掉落。',
    note: '幽魂系的战利品，可用于女武神 / 幽魂相关的制作与料理；具体配方以游戏内为准。' },
  { id: 'fleshy_bulb', cn: '肉球', en: 'Fleshy Bulb', img: 'Fleshy_Bulb.png', cat: 'mob', alias: ['食人花种子', '食人花的肉球'],
    src: '击杀食人花掉落 1 个（被它吞掉的东西也会一起吐出来）。',
    note: '可以重新种回地上长出一株新的食人花；也能当肥料使用。食人花会吃掉附近地上的掉落物，所以收完再打。' },
  { id: 'message_in_a_bottle', cn: '瓶中信', en: 'Message in a Bottle', img: 'Message_in_a_Bottle.png', cat: 'mob', alias: ['漂流瓶', '瓶子里的信'],
    src: '击杀海獭有 5% 概率掉落；击杀帝王蟹会掉 2-4 个。',
    note: '打开后会给出寻宝 / 沉船位置的提示，是海上探索的引导道具。' },
  { id: 'ornate_chest', cn: '华丽大箱子', en: 'Ornate Chest', img: 'Large_Ornate_Chest.png', cat: 'mob', alias: ['华丽箱子', '华丽宝箱'],
    src: '击杀远古守护者掉落（迷宫死胡同里的华丽宝箱也是同款）。',
    note: '打开能拿到铥矿装备、宝石等远古战利品；它本身也能被锤子敲掉回收。' },
  { id: 'deer_antler', cn: '鹿角', en: 'Deer Antler', img: 'mat_deer_antler.png', cat: 'boss', alias: ['无眼鹿鹿角'],
    src: '击杀有角的无眼鹿掉落，无眼鹿撞树时也可能撞下一根（A / B / C 三种形态随机）。',
    note: '用来做「透明角」相关道具；和克劳斯掉的麋鹿茸不是同一样东西。条目图标暂缺，页面显示文字占位。' },
  { id: 'gnarwail_horn', cn: '一角鲸角', en: 'Gnarwail Horn', img: 'Gnarwail_Horn.png', cat: 'mob', alias: ['一角鲸长角'],
    src: '击杀一角鲸掉落。',
    note: '海洋系制作材料，可做一角鲸相关的武器与船只配件。' },
  { id: 'lunar_spore', cn: '月亮孢子', en: 'Lunar Spore', img: 'Lunar_Spore.png', cat: 'mob', alias: ['月光孢子', '月孢子'],
    src: '击杀蘑菇地精掉落 3-5 个（月亮蘑菇树与戴月亮蘑菇帽的人也会散发）。',
    note: '会在地上待 7.5 秒后自爆并造成 10 点伤害，靠近也会提前引爆；捕虫网一捞就炸。别在没护甲时贴着捡。' },
  { id: 'sea_sprout_starter', cn: '海芽插穗', en: 'Sea Sprout Starter', img: 'Sea_Sprout_Starter.png', cat: 'mob', alias: ['海苗种', '海芽种苗'],
    src: '击杀海草（含黄色品种）掉落 1 个。',
    note: '种在近海的海蚀柱上就能长出新的海草，是人工养殖藤壶的起点；植株长满 3 个藤壶后，月圆夜会再长成成熟海草。' },
  { id: 'seed_shell', cn: '种壳', en: 'Seed Shell', img: 'Seedshell.png', cat: 'mob', alias: ['种子壳'],
    src: '击杀海草掉落 2-3 个（黄色品种 3-5 个）。',
    note: '就是海草扔你的那颗硬壳：拿在手里可以当投掷武器用，单发 60 点伤害，也是海草相关制作的原料。' },
  { id: 'cookie_crumbs', cn: '饼干碎屑', en: 'Cookie Crumbs', img: '', cat: 'mob', alias: ['饼干屑'],
    src: '追赶姜饼猪时它会一路掉；击杀姜饼座狼、敲毁姜饼猪屋也会掉。',
    note: '顺着碎屑走能一路找到姜饼猪窝（80% 概率）或姜饼座狼（20%）；碎屑也能当浣熊猫的礼物。条目图标暂缺，页面显示文字占位。' },
  { id: 'festive_joy', cn: '节日欢愉', en: 'Festive Joy', img: '', cat: 'mob', alias: ['节日欢乐'],
    src: '击杀姜饼座狼掉落 5-7 个；敲毁姜饼猪屋固定掉 1 个。',
    note: '冬季盛宴活动的关键材料：站在砖砌烤炉旁用它解锁 18 道节日料理，配合盛宴餐桌吃还能拿到持续的三维增益。只能在活动期间获得。条目图标暂缺，页面显示文字占位。' },
  { id: 'red_pouch', cn: '红包', en: 'Red Pouch', img: 'Red_Pouch.png', cat: 'mob', alias: ['红包袋'],
    src: '击杀黏土猎犬有 20% 概率掉落；击杀黏土座狼掉落 4-6 个。',
    note: '座狼年活动里黏土生物的掉落物，属于节日收集品。' },
  { id: 'naked_nostrils', cn: '裸露的鼻孔', en: 'Naked Nostrils', img: 'Naked_Nostrils.png', cat: 'mob', alias: ['裸鼻孔', '鼻孔'],
    src: '击杀裸鼹蝠有 33% 概率掉落。',
    note: '食材：和 1 份海带叶、1 份乳制品一起下锅可以做出牛奶帽，戴上是持续回饥饿的帽子（沃特戴还能回理智）。' },
  { id: 'mask_sage', cn: '贤者面具', en: 'Sage Mask', img: '', cat: 'mob', alias: ['智者面具'],
    src: '击杀被「虚空面具」附身的生物，有 30% 概率掉落三种面具中的一种。',
    note: '属于收集类掉落物，三种面具（贤者 / 马屁精 / 蠢人）随机其一；戴上面具时会变成被附身的形态，谨慎使用。条目图标暂缺，页面显示文字占位。' },
  { id: 'mask_sycophant', cn: '马屁精面具', en: 'Sycophant Mask', img: '', cat: 'mob', alias: ['谄媚者面具', '马屁精头套'],
    src: '击杀被「虚空面具」附身的生物，有 30% 概率掉落三种面具中的一种。',
    note: '收集类掉落物，与贤者面具、蠢人面具同为虚空面具掉落的三件套。条目图标暂缺，页面显示文字占位。' },
  { id: 'mask_fool', cn: '蠢人面具', en: 'Fool Mask', img: 'Fool_Mask.png', cat: 'mob', alias: ['愚人面具'],
    src: '击杀被「虚空面具」附身的生物，有 30% 概率掉落三种面具中的一种。',
    note: '收集类掉落物，与贤者面具、马屁精面具同为虚空面具掉落的三件套。' },
  { id: 'frog_legs', cn: '青蛙腿', en: 'Frog Legs', img: 'Frog_Legs.png', cat: 'mob', alias: ['蛙腿'],
    src: '击杀青蛙、雨蛙掉落（用捕虫网抓住再在背包里处理也算）。',
    note: '食材：可烤熟吃，也是蛙腿三明治等料理的材料；下雨天青蛙会从天上掉下来，别把重要物品放地上。' },
  { id: 'seeds', cn: '种子', en: 'Seeds', img: 'Seeds.png', cat: 'plant', alias: ['植物种子', '普通种子'],
    src: '拔草、采摘浆果丛、收割农场作物时常见掉落，翻风滚草也能找到。',
    note: '最基本的种植与喂鸟材料：种下去能长出随机作物，喂鸟笼里的鸟可以换成特定种子；很多配方也拿它当填充料。' },
  { id: 'blow_dart', cn: '吹箭', en: 'Blow Dart', img: 'Blow_Dart.png', cat: 'mob', alias: ['布洛吹箭', '普通吹箭'],
    src: '击杀海象（海象爸爸）掉落 1 个；学会蓝图后也可自制。',
    note: '远程武器：单发 100 伤害，是前期少见的远程输出手段；打完可以捡回来重复使用。' },
  { id: 'mushroom_spore', cn: '蘑菇孢子', en: 'Mushroom Spore', img: 'Blue_Spore.png', cat: 'mob', alias: ['孢子', '红孢子', '绿孢子', '蓝孢子', '雨孢子', '旱孢子', '雾孢子'],
    src: '击杀毒菌蟾蜍掉落约 2.5 个；砍倒蘑菇树、蘑菇农场长满时也会释放，可用捕虫网捕捉。',
    note: '在地上的孢子只会短暂漂浮并发光，之后自行消失；放进蘑菇灯里可以改变灯光颜色，也能种到蘑菇播种木里种出蘑菇。' },
  { id: 'trinket', cn: '小玩意', en: 'Trinket', img: 'Beach_Toy.png', cat: 'mob', alias: ['盗墓者玩具', '小饰品', '破烂小玩意'],
    src: '击杀蚁狮掉落 2 个；挖坟墓、翻风滚草、开海边漂流物也会拿到。',
    note: '各种小玩具（融化弹珠、沙滩玩具等），可以拿去和猪王换金块、送给浣熊猫刷好感，纯粹是交易用的收藏品。' },
  { id: 'gold_belt', cn: '金腰带', en: 'Gold Belt', img: 'mat_gold_belt.png', cat: 'mob', alias: ['黄金腰带'],
    src: '约 1% 的猪人生成时会佩戴金腰带，击杀这样的猪人就会额外掉落。',
    note: '活动（猪王之年）相关的装饰 / 收藏品；平时见到戴腰带的猪人别错过。条目图标暂缺，页面显示文字占位。' },
  { id: 'dark_tatters', cn: '暗影碎布', en: 'Dark Tatters', img: 'Dark_Tatters.png', cat: 'misc', alias: ['暗影破布', '暗影布'],
    src: '击杀墨荒（影缝开启后出现的暗影仆从）掉落。',
    note: '暗影阵营的高阶材料：虚空长袍、阴郁武器等暗影装备都要用它，也是暗影裂隙阶段才有的资源。' },
  { id: 'lucky_horseshoe', cn: '幸运马蹄铁', en: 'Lucky Horseshoe', img: 'Lucky_Horseshoe.png', cat: 'mob', alias: ['马蹄铁'],
    src: '击杀镀金骑士有 10% 概率掉落（开启「发条骑士之年」时获取）。',
    note: '随身携带可以提升隐藏的「幸运值」：每 1 个约 +0.05，穿戴镀金骑士套装时加成翻倍，活动期间还会再变三倍——影响海象掉率等随机结果。' },
  { id: 'gilded_helmet', cn: '镀金骑士头盔', en: 'Gilded Helmet', img: 'mat_gilded_helmet.png', cat: 'mob', alias: ['镀金头盔', '骑士头盔'],
    src: '击杀最后一名镀金骑士时掉落（发条骑士之年活动）。',
    note: '头部护甲：90% 减伤、20% 防潮，属性对标铥矿装备，缺点是耐久偏低。条目图标暂缺，页面显示文字占位。' },
  { id: 'gilded_armor', cn: '镀金骑士胸甲', en: 'Gilded Armor', img: '', cat: 'mob', alias: ['胸甲', '镀金胸甲'],
    src: '击杀最后一名镀金骑士时掉落（发条骑士之年活动）。',
    note: '身体护甲：90% 减伤、840 点耐久；和头盔一起穿上还能提升幸运值。条目图标暂缺，页面显示文字占位。' },
  { id: 'jousting_lance', cn: '冲锋骑枪', en: 'Jousting Lance', img: '', cat: 'mob', alias: ['马上比武', '骑枪'],
    src: '击杀镀金骑士有 25% 概率掉落。',
    note: '长兵器：51 伤害、200 点耐久，攻击距离比一般武器远；右键还能像骑士一样冲刺，沿途撞到的生物都会受伤。条目图标暂缺，页面显示文字占位。' },
  { id: 'accursed_trinket', cn: '诅咒饰品', en: 'Accursed Trinket', img: 'Accursed_Trinket.png', cat: 'mob', alias: ['被诅咒的小玩意', '诅咒小玩意'],
    src: '火药猴（以及海盗大副）死亡时会掉出 1 个，并会自动飞进最近玩家的背包。',
    note: '丢不掉、塞不进箱子：攒到 10 个角色会被强制变成芜猴。想解除就给月亮码头女王送香蕉，每个香蕉清掉 4 个。' },

  /* ---------------- 巨兽掉落 ----------------
     各个巨兽 / Boss 专属的掉落物（普通肉、宝石、蘑菇等通用材料不在这里重复收录）。
     每条都对应「生物」页里对应 Boss 的掉落表，两边可以互相跳转。 */
  { id: 'deerclops_eyeball', cn: '独眼巨鹿眼球', en: 'Deerclops Eyeball', img: 'Deerclops_Eyeball.png', cat: 'boss', alias: ['巨鹿眼球', '鹿角怪眼球'],
    src: '击杀独眼巨鹿（冬季巨兽）必定掉落 1 个。',
    note: '眼球伞（雨雪双防）与眼球镭射塔（守护者之角 + 独眼巨鹿眼球 + 5 个铥矿）的核心材料；本身不会腐坏，也能直接吃，回大量饥饿与生命但会掉理智。烧死的巨鹿只掉熟肉、不掉眼球。' },
  { id: 'fur_tuft', cn: '毛簇', en: 'Fur Tuft', img: 'Fur_Tuft.png', cat: 'boss', alias: ['熊毛', '熊獾毛簇'],
    src: '熊獾每 45 秒在原地掉 1 个；它的拍地震击另有 20% 概率一次掉 3 个。冬季与春季熊獾冬眠期间不再掉毛。',
    note: '3 个毛簇可在炼金引擎旁合成 1 个厚皮毛；用拆解魔杖拆 1 个厚皮毛可回收到 30 个毛簇。也能当燃料，但掉在地上会被风吹走（和灰烬一样）。' },
  { id: 'royal_jelly', cn: '蜂王浆', en: 'Royal Jelly', img: 'Royal_Jelly.png', cat: 'boss', alias: ['蜂王浆液', '蜂皇浆'],
    src: '击杀蜂王掉落 6-7 个。',
    note: '彩虹糖豆的唯一材料，全队回血都靠它；本身也能吃。熊獾带甜味的物品时会被它激怒（蜂王浆算「甜食」之一），别在熊獾面前乱拿。' },
  { id: 'bee_queen_crown', cn: '女王蜂帽', en: 'Bee Queen Crown', img: 'Bee_Queen_Crown.png', cat: 'boss', alias: ['蜂后王冠', '蜂王王冠', '蜂后皇冠'],
    src: '击杀蜂王必定掉落 1 个（克劳斯的赃物袋里也可能开出）。',
    note: '头部护甲：945 点耐久、吸收 70% 物理伤害、20% 防潮。戴上后会把「疯狂光环」转成一半数值的理智增益（例如 -400/分 变成 +200/分），所以站在树精守卫、恶魔花、眼球镭射塔旁边反而能回理智。空手站立时会让附近队友行鞠躬礼。' },
  { id: 'stag_antler', cn: '麋鹿茸', en: 'Stag Antler', img: 'Stag_Antler.png', cat: 'boss', alias: ['鹿角钥匙', '克劳斯鹿角'],
    src: '击败克劳斯后掉落（打败他两次、解链之后再击杀才掉）。',
    note: '赃物袋（Loot Stash）的唯一正确钥匙：把麋鹿茸放进赃物袋就能打开它，拿到一堆稀有蓝图、宝石与战利品。普通的无眼鹿角只是错误钥匙，会直接召唤克劳斯。' },
  { id: 'lavae_egg', cn: '岩浆虫卵', en: 'Lavae Egg', img: 'Lavae_Egg.png', cat: 'boss', alias: ['岩浆虫蛋'],
    src: '击杀龙蝇有 33% 概率掉落 1 个。',
    note: '龙蝇的稀有掉落，属于收藏 / 纪念性质的战利品；具体数值与后续用途以游戏内为准。' },
  { id: 'scaled_furnace_blueprint', cn: '鳞片熔炉蓝图', en: 'Blueprint (Scaled Furnace)', img: 'Scaled_Furnace.png', cat: 'boss', alias: ['龙蝇熔炉蓝图', '鳞片火炉蓝图'],
    src: '击杀龙蝇必定掉落（和鳞片一起掉）。',
    note: '学会后可在炼金引擎旁建造「鳞片熔炉」——不会熄灭、能烤肉的火炉，是后期最省心的热源与照明。' },
  { id: 'bundling_wrap_blueprint', cn: '打包带蓝图', en: 'Blueprint (Bundling Wrap)', img: 'Blueprint.png', cat: 'boss', alias: ['捆扎带蓝图', '打包纸蓝图'],
    src: '击杀蜂王有概率掉落（稀有）。',
    note: '学会后可以用莎草纸 + 绳子制作打包带，把一堆食物捆成一包，既不腐坏也不占背包格子，搬家与长途远征必备。' },
  { id: 'guardian_s_horn', cn: '守护者之角', en: "Guardian's Horn", img: "Guardian's_Horn.png", cat: 'boss', alias: ['守护者号角', '远古守护者之角'],
    src: '击杀远古守护者必定掉落 1 个。',
    note: '眼球镭射塔（Houndius Shootius）的指定材料之一：1 个守护者之角 + 1 个独眼巨鹿眼球 + 5 个铥矿，只能在远古伪科学站旁制作。' },
  { id: 'shadow_thurible', cn: '暗影香炉', en: 'Shadow Thurible', img: 'Shadow_Thurible.png', cat: 'boss', alias: ['暗影香炉器'],
    src: '击杀远古织影者必定掉落 1 个。',
    note: '对「怪异骸骨」使用可以召唤复活的骨架——召唤地点不同会分别出现森林 / 洞穴 / 远古三种形态，是通往远古织影者流程的钥匙道具。' },
  { id: 'bone_helm', cn: '骨盔', en: 'Bone Helm', img: 'Bone_Helm.png', cat: 'boss', alias: ['骨制头盔'],
    src: '击杀远古织影者必定掉落 1 个。',
    note: '头部护甲：945 点耐久、吸收 70% 物理伤害、20% 防潮；戴上后暗影生物与梦魇生物会把你当成同类（不再主动攻击），代价是持续掉理智（约 -20/分），是挖矿、跑遗迹时很好用的「和平通行证」。' },
  { id: 'bone_armor', cn: '骨甲', en: 'Bone Armor', img: 'Bone_Armor.png', cat: 'boss', alias: ['骨制护甲'],
    src: '击杀远古织影者必定掉落 1 个（无法制作，只能靠掉落）。',
    note: '身体护甲：每 5 秒完全格挡一次伤害，共 16 次。用来扛巨兽的大招最划算，但注意对持续伤害（火、毒）没有额外帮助。' },
  { id: 'rose', cn: '玫瑰', en: 'Rose', img: 'Rose.png', cat: 'boss', alias: ['玫瑰花', '玫瑰花朵'],
    src: '击杀远古织影者必定掉落 1 个（上古织影者离开战斗时也会留下）。',
    note: '来自中庭的纪念性战利品，可当燃料；和普通花朵一样会随时间腐坏。' },
  { id: 'shadow_atrium', cn: '暗影中庭', en: 'Shadow Atrium', img: 'Shadow_Atrium.png', cat: 'boss', alias: ['暗影心房', '暗影之心', '附身暗影中庭'],
    src: '击杀 Lv3 的暗影棋子（棋盘中第三级形态）掉落；远古织影者在玩家脱离战斗分解时也会留下 1 个。',
    note: '打最终 Boss 的门票：把它插入完整的怪异骸骨就能召唤远古织影者。想拿它必须先让棋子升到 Lv3——骑士 / 主教 / 战车三种各杀一只同级的才会升级。' },
  { id: 'fossils', cn: '化石', en: 'Fossils', img: 'Fossils.png', cat: 'boss', alias: ['骨化石', '化石碎片', '奇异的骨架'],
    src: '击杀远古织影者必定掉落 8 个；复活的骨架被击败后也会留下 8 个（远古织影者中途分解时同样掉 8 个）。',
    note: '用来把「怪异骸骨」一块块拼回完整——这是召唤远古织影者（或复活的骨架）的必要步骤，也能在远古伪科学站旁用来制作化石类结构。' },
  { id: 'enlightened_shard', cn: '启迪之冠碎片', en: 'Enlightened Crown Shard', img: 'Enlightened_Shard.png', cat: 'boss', alias: ['启迪碎片', '启迪之冠碎屑'],
    src: '击杀天体英雄（第三形态）必定掉落 1 个。',
    note: '用来制作「启迪之冠」——戴上后能在月缝附近获得启迪值并强化月系武器，是月后流派的标志性装备。' },
  { id: 'shroom_skin', cn: '蘑菇皮', en: 'Shroom Skin', img: 'Shroom_Skin.png', cat: 'boss', alias: ['毒菌皮', '阴暗蘑菇皮'],
    src: '击杀毒菌蟾蜍必定掉落 1 个（苦难形态 2 个），并且它的血量每掉到 70% / 40%（苦难形态还有 20%）时会额外掉 1 个。',
    note: '蘑菇灯、蘑菇帽与树人陷阱的指定材料，只能靠打毒菌蟾蜍获得，所以想要农场照明就得先打赢它。' },
  { id: 'mushroom_light_blueprint', cn: '蘑菇灯蓝图', en: 'Blueprint (Mushlight / Glowcap)', img: 'Mushlight.png', cat: 'boss', alias: ['蘑菇灯图纸', '发光菌蓝图'],
    src: '击杀毒菌蟾蜍随机掉落 1 个（67% 是蘑菇灯 Mushlight，33% 是发光菌 Glowcap）；苦难形态另有蘑菇帽与睡袋蓝图。',
    note: '学会后可建造蘑菇灯 / 发光菌——不耗燃料的永久光源，而且能用孢子调整颜色，是基地照明最省事的方案。' },
  { id: 'lazy_deserter_blueprint', cn: '懒惰的沙漠人蓝图', en: 'Blueprint (Lazy Deserter)', img: 'Blueprint.png', cat: 'boss', alias: ['怠惰逃亡者蓝图', '懒惰的沙漠旅者蓝图'],
    src: '击杀蚁狮必定掉落 1 个；给蚁狮一个沙滩玩具也会送你这张蓝图。',
    note: '学会后可建造「懒惰的沙漠人」：两台之间配合使用可以把队友传送到另一台旁边，是后期跨地图集合的常用建筑。' },
  { id: 'malbatross_beak', cn: '邪天翁喙', en: 'Malbatross Bill', img: 'Malbatross_Bill.png', cat: 'boss', alias: ['邪天翁喙', '邪天翁大喙'],
    src: '击杀邪天翁（邪天翁）必定掉落 1 个。',
    note: '海上航行装备的指定材料（如船帆与相关海洋制作），只有打邪天翁才能稳定获得。' },
  { id: 'strident_trident_blueprint', cn: '魔音三叉戟蓝图', en: 'Blueprint (Strident Trident)', img: 'Strident_Trident.png', cat: 'boss', alias: ['三叉戟蓝图'],
    src: '击杀帝王蟹必定掉落 1 个。',
    note: '学会后可制作「魔音三叉戟」——能在船上使用的长柄武器，挥动时会召唤海浪。' },
  { id: 'crab_king_bumper_kit', cn: '帝王蟹船撞垫套装', en: 'Crab King Bumper Kit', img: 'Crab_King_Bumper_Kit.png', cat: 'boss', alias: ['螃蟹跳板', '帝王蟹船垫', '帝王蟹保险杠套装'],
    src: '击杀帝王蟹掉落 8 个（一整叠）。',
    note: '给船只加装撞垫，撞到礁石或海怪时能减少船体损伤；和其他撞垫套装（海带 20 耐久 / 贝壳 40 / 尖牙 40）可以混用。它是四种里最结实的（耐久 150），撞到陆地也不掉耐久，可以用石头、切石或石墙修复。' },
  { id: 'shell_bell', cn: '贝壳钟', en: 'Shell Bell', img: 'Baritone_Shell_Bell.png', cat: 'boss', alias: ['低音贝壳钟', '中音贝壳钟', '高音贝壳钟', '歌贝壳钟'],
    src: '击杀帝王蟹掉落：低音 1-3 个、中音 2-4 个、高音 3-5 个。',
    note: '三种音高的贝壳钟，是海洋制作（沉船宝箱、航海装饰与乐器类物品）的材料；用锤子敲碎也能回收贝壳碎片。' },
  { id: 'cracked_pearl', cn: '裂开的珍珠', en: 'Cracked Pearl', img: 'Cracked_Pearl.png', cat: 'boss', alias: ['破碎的珍珠'],
    src: '给帝王蟹嵌上「珍珠的珍珠」后再击杀它，会掉落裂开的珍珠（替代原来的珍珠）。',
    note: '属于剧情道具：拿到它意味着珍珠的故事线推进了一步，可以交回给隐士做后续互动。' },
  { id: 'inactive_celestial_tribute', cn: '未启动的天体贡品', en: 'Inactive Celestial Tribute', img: 'Inactive_Celestial_Tribute.png', cat: 'boss', alias: ['天体贡品'],
    src: '嵌有「珍珠的珍珠」的帝王蟹死亡时会从空中抛落，掉进海里后变成可打捞的水下打捞物，需要自己捞上来。',
    note: '天体祭坛相关流程的关键组件，也是「天体英雄」召唤链的一环；捞取时要小心海上的其他威胁。' },
  { id: 'milky_whites', cn: '乳白蛋白', en: 'Milky Whites', img: 'Milky_Whites.png', cat: 'boss',
    alias: ['蛋白液', '乳白质', '乳白物'],
    src: '击杀恐惧之眼（Eye of Terror）掉落 3-5 个。',
    note: '来自恐惧之眼的黏稠战利品。除了用于相关食谱与制作，它还是小动物「小窥视者」（Friendly Peeper）的领养材料之一（需要 1 个乳白蛋白 + 1 份培根煎蛋）。' },
  { id: 'eye_mask', cn: '眼罩', en: 'Eye Mask', img: 'Eye_Mask.png', cat: 'boss', alias: ['恐惧之眼面罩'],
    src: '击杀恐惧之眼必定掉落 1 个。',
    note: '头部护甲：315 点耐久、吸收 80% 物理伤害、20% 防潮；可以「吃」食物来修复自己的耐久，是很好保养的实用头甲。' },
  { id: 'shield_of_terror', cn: '恐惧之盾', en: 'Shield of Terror', img: 'Shield_of_Terror.png', cat: 'boss', alias: ['恐惧盾'],
    src: '在同一场战斗中把恐惧双子（视网膜与散光）全部击杀后掉落。',
    note: '手部装备，兼当武器（每次挥击 51 伤害）：315 点耐久、吸收 80% 物理伤害，而且可以吃食物修复；攻守两用是它最大的价值。' },
  { id: 'frazzled_wires', cn: '焦电线', en: 'Frazzled Wires', img: 'Frazzled_Wires.png', cat: 'boss', alias: ['焦线', '烧焦电线'],
    src: '击杀恐惧双子（视网膜 / 散光）各掉 1-2 个；天体后继者也会掉 2-3 个。',
    note: '机械类制作的常见材料（W.A.R.B.I.S. 与废料系装备都会用到），拆解地平线扩张器也能回收 1 个。' },
  { id: 'celestial_jewel', cn: '天体宝石', en: 'Celestial Jewel', img: 'Celestial_Jewel.png', cat: 'boss', alias: ['天体宝珠'],
    src: '击杀天体后继者（月后主线最终 Boss）掉落 5 个。',
    note: '月后终局的稀有材料，天体类装备与终局制作会用到；只有打赢天体后继者才能获得。' },
  { id: 'nucleation_fluid', cn: '成核液', en: 'Nucleation Fluid', img: 'Nucleation_Fluid.png', cat: 'boss', alias: ['成核液体'],
    src: '在已经击败天体后继者的世界里，击杀月亮变异 Boss（晶体独眼巨鹿 / 装甲熊獾 / 被附身座狼）会掉落它，取代原来的星火方舟。',
    note: '剧情后期才出现的特殊掉落，用于月后主线的后续内容；前期击杀变异 Boss 拿到的是星火方舟。' },
  { id: 'scrap', cn: '废料', en: 'Scrap', img: 'Scrap.png', cat: 'boss', alias: ['废铁', '金属废料'],
    src: '击杀拾荒疯猪掉落 4 个；破损的垃圾堆、废料架与海边垃圾也能敲出废料。',
    note: '废料系装备 / 建筑（废料墙、W.A.R.B.I.S. 相关制作、修理台等）的基础材料，拆解地平线扩张器可回收 2 个。' },
  { id: 'horizon_expandinator', cn: '地平线扩张器', en: 'Horizon Expandinator', img: 'Horizon_Expandinator.png', cat: 'boss', alias: ['地平线扩张仪', '废料单片镜'],
    src: '击杀拾荒疯猪必定掉落 1 个。',
    note: '头部装备：大幅扩大视野范围（镜头可以拉得更远），白天还回一点理智，夜晚反而掉理智；用拆解魔杖拆掉可得 2 个废料 + 1 个电子零件 + 1 个焦电线。' },
  { id: 'auto_mat_o_chanic', cn: '自动机械臂', en: 'Auto-Mat-O-Chanic', img: 'Auto-Mat-O-Chanic.png', cat: 'boss', alias: ['自动修理臂', '机械修理工'],
    src: '击杀拾荒疯猪掉落 1 个（也见于废弃垃圾堆中的稀有蓝图）。',
    note: '一次性修理道具：能把 W.A.R.B.I.S. 护甲 / 头盔以及 W.O.B.O.T. 直接修到满耐久（哪怕已经耐久归零），用完即消耗。' },
  { id: 'scrappy_chapauldron', cn: '废料头盔', en: 'Scrappy Chapauldron', img: 'Scrappy_Chapauldron.png', cat: 'boss', alias: ['废料盔', '破烂头盔'],
    src: '在拾荒疯猪仍然戴着护甲（没被打破）时击杀它，就会掉落这顶头盔。',
    note: '头部护甲，属于废料系装备；想让拾荒疯猪掉它，就别急着破甲——先打死它才能拿到。' },
  { id: 'spark_ark', cn: '星火方舟', en: 'Spark Ark', img: 'Spark_Ark.png', cat: 'boss',
    alias: ['星火方舟（空）', '空星火方舟', '星火方舟零件', '火花柜', '火花方舟'],
    src: '完成「雪花屏传输（Grainy Transmission）」任务——把晶体独眼巨鹿、装甲熊獾、被附身座狼三个月亮变异 Boss 各击杀一次——雪花屏会交给你一个空的星火方舟。击败天体后继者后，改由「概念制造机」用 1 个成核液 + 2 个铥矿 + 1 个受控静电制作。使用前要在已激活的远古档案馆用安保脉冲充能。',
    note: '月后主线（从彼岸）的核心道具：到手时是空壳，充能后才能用。用途是——在亮茂锻炉制作北极熊獾箱、冰晶眼套件与嚎叫者，也能激活休眠的守卫塔。注意它和「火花插槽」是两件不同的东西。' },
  { id: 'friendly_fruit_fly_fruit', cn: '友好果蝇果实', en: 'Friendly Fruit Fly Fruit', img: 'Friendly_Fruit_Fly_Fruit.png', cat: 'boss', alias: ['友好果蝇果'],
    src: '击杀果蝇王掉落 1 个（世界里只能同时存在一个）。',
    note: '种下去会孵出「友好果蝇」，它会帮你照料农田（给作物浇水、除草、催熟）；农场流必打的 Boss 奖励。' },
  { id: 'dreadstone_gear_blueprint', cn: '恐惧石装备蓝图', en: 'Blueprint (Dreadstone Helm / Armor / Wall)', img: 'Dreadstone_Helm.png', cat: 'boss', alias: ['恐惧石头盔蓝图', '恐惧石护甲蓝图'],
    src: '击败梦魇疯猪掉落：恐惧石头盔、恐惧石护甲、恐惧石墙三张蓝图；把战场上所有碎裂石柱都砸掉，还会额外获得恐惧石柱脚手架蓝图。',
    note: '学会后就能在暗影类制作站打造恐惧石系列装备（绝望石 + 纯粹恐惧）：头盔 / 护甲都是 840 点耐久、90% 减伤并且带域面防御，会靠消耗佩戴者理智自我修复，属于月后主线的高端装备。' },

  /* ---- 巨兽雕像手稿（Sketch）：交给陶轮解锁对应巨兽雕像 ----
     每个巨兽掉自己的那一张；手稿本身造型相同，交给陶轮（Potter\'s Wheel）后即可制作对应雕塑。 */
  { id: 'sketch_deerclops', cn: '独眼巨鹿手稿', en: 'Deerclops Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['独眼巨鹿雕塑草图', '独眼巨鹿手办图样'],
    src: '击杀独眼巨鹿必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮即可解锁独眼巨鹿雕塑。雕塑用大理石 / 石砖 / 月亮碎片做出白、黑、玻璃蓝三种颜色，纯装饰；手稿本身也能当燃料（15 秒）。' },
  { id: 'sketch_bearger', cn: '熊獾手稿', en: 'Bearger Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['熊獾雕塑草图', '熊獾手办图样'],
    src: '击杀熊獾必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁熊獾雕塑；也可以交给制图台换 1 张莎草纸。' },
  { id: 'sketch_moose', cn: '麋鹿鹅手稿', en: 'Moose/Goose Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['麋鹿鹅雕塑草图', '麋鹿鹅手办图样'],
    src: '击杀麋鹿鹅必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁麋鹿鹅雕塑，是春季巨兽唯一的纪念品。' },
  { id: 'sketch_dragonfly', cn: '龙蝇手稿', en: 'Dragonfly Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['龙蝇雕塑草图', '龙蝇手办图样'],
    src: '击杀龙蝇必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁龙蝇雕塑。' },
  { id: 'sketch_bee_queen', cn: '蜂王手稿', en: 'Bee Queen Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['蜂王雕塑草图', '蜂王手办图样'],
    src: '击杀蜂王必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁蜂王雕塑。' },
  { id: 'sketch_klaus', cn: '克劳斯手稿', en: 'Klaus Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['克劳斯雕塑草图', '克劳斯手办图样'],
    src: '击败克劳斯后掉落（冬季盛宴期间还会额外掉拐杖糖）。',
    note: '巨兽雕塑手稿：交给陶轮解锁克劳斯雕塑。' },
  { id: 'sketch_crab_king', cn: '帝王蟹手稿', en: 'Crab King Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['帝王蟹雕塑草图', '帝王蟹手办图样'],
    src: '击杀帝王蟹必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁帝王蟹雕塑。' },
  { id: 'sketch_toadstool', cn: '毒菌蟾蜍手稿', en: 'Toadstool Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['毒菌蟾蜍雕塑草图', '毒菌蟾蜍手稿'],
    src: '击杀毒菌蟾蜍（含苦难形态）必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁毒菌蟾蜍雕塑。' },
  { id: 'sketch_antlion', cn: '蚁狮手稿', en: 'Antlion Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['蚁狮雕塑草图', '蚁狮手办图样'],
    src: '击杀蚁狮必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁蚁狮雕塑。' },
  { id: 'sketch_malbatross', cn: '邪天翁手稿', en: 'Malbatross Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['邪天翁手稿', '邪天翁雕塑草图'],
    src: '击杀邪天翁（邪天翁）必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁邪天翁雕塑。' },
  { id: 'sketch_ancient_guardian', cn: '远古守护者手稿', en: 'Ancient Guardian Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['远古守护者雕塑草图', '守护者手办图样'],
    src: '击杀远古守护者掉落。',
    note: '巨兽雕塑手稿：交给陶轮解锁远古守护者雕塑。' },
  { id: 'sketch_celestial_champion', cn: '天体英雄手稿', en: 'Celestial Champion Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['天体英雄雕塑草图', '天体冠军手稿'],
    src: '击杀天体英雄（第三形态）掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁天体英雄雕塑。' },
  { id: 'sketch_fuelweaver', cn: '远古织影者手稿', en: 'Ancient Fuelweaver Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['远古织影者雕塑草图', '上古织影者手稿'],
    src: '击杀远古织影者（由玩家击杀，而不是让它分解）掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁远古织影者雕塑。' },
  { id: 'sketch_eye_of_terror', cn: '恐惧之眼手稿', en: 'Eye of Terror Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['恐惧之眼雕塑草图', '恐惧之眼手办图样'],
    src: '击杀恐惧之眼必定掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁恐惧之眼雕塑。' },
  { id: 'sketch_twins_of_terror', cn: '恐惧双子手稿', en: 'Twins of Terror Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['恐惧双子雕塑草图', '双子手稿'],
    src: '把恐惧双子（视网膜与散光）全部击杀后掉落。',
    note: '巨兽雕塑手稿：交给陶轮解锁恐惧双子雕塑。' },
  { id: 'sketch_nightmare_werepig', cn: '梦魇疯猪手稿', en: 'Nightmare Werepig Sketch', img: 'Sketch.png', cat: 'boss', alias: ['梦魇疯猪雕塑草图', '梦魇疯猪手办图样'],
    src: '击败梦魇疯猪掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁梦魇疯猪雕塑。' },
  { id: 'sketch_frostjaw', cn: '霜牙手稿', en: 'Frostjaw Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['霜牙雕塑草图', '霜牙手办图样'],
    src: '不是击杀掉落：霜牙打不死，它会投降并和你交易，第一次用重型海鱼换东西时会额外送你这张手稿（冬季盛宴期间改为装在大礼物里）。',
    note: '巨兽雕塑手稿：交给陶轮解锁霜牙雕塑。平时可以用海鱼找它换「走私箱」（Bootleg Getaway）。' },
  { id: 'sketch_scrappy_werepig', cn: '拾荒疯猪手稿', en: 'Scrappy Werepig Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['拾荒疯猪雕塑草图', '拾荒疯猪手办图样'],
    src: '击杀拾荒疯猪掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁拾荒疯猪雕塑。' },
  { id: 'sketch_crystal_deerclops', cn: '晶体独眼巨鹿手稿', en: 'Crystal Deerclops Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['晶体独眼巨鹿雕塑草图', '水晶巨鹿手稿'],
    src: '击杀晶体独眼巨鹿（月缝附近的鹿角怪尸体被附身后出现）掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁晶体独眼巨鹿雕塑。想跳过这场战斗可以在附身之前用火把把尸体烧掉。' },
  { id: 'sketch_armored_bearger', cn: '装甲熊獾手稿', en: 'Armored Bearger Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['装甲熊獾雕塑草图', '附身熊獾手稿'],
    src: '击杀装甲熊獾（月缝附近的熊獾尸体被附身后出现）掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁装甲熊獾雕塑。' },
  { id: 'sketch_possessed_varg', cn: '被附身座狼手稿', en: 'Possessed Varg Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['被附身座狼雕塑草图', '附身座狼手稿'],
    src: '击杀被附身座狼（月缝附近的座狼尸体被附身后出现）掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁被附身座狼雕塑。' },
  { id: 'sketch_great_depths_worm', cn: '巨大洞穴蠕虫手稿', en: 'Great Depths Worm Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['巨大洞穴蠕虫雕塑草图', '深渊蠕虫手稿'],
    src: '击杀巨大洞穴蠕虫（洞穴蠕虫袭击中出现的首领）掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁巨大洞穴蠕虫雕塑。' },
  { id: 'sketch_warbot', cn: 'W.A.R.B.O.T. 手稿', en: 'W.A.R.B.O.T. Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['W.A.R.B.O.T. 雕塑草图', '战争机器手稿'],
    src: '击败 W.A.R.B.O.T.（战争机器）掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁 W.A.R.B.O.T. 雕塑。' },
  { id: 'sketch_celestial_scion', cn: '天体后继者手稿', en: 'Celestial Scion Figure Sketch', img: 'Sketch.png', cat: 'boss', alias: ['天体后继者雕塑草图', '天体双子手稿'],
    src: '击杀天体后继者（月后主线最终 Boss）掉落 1 个。',
    note: '巨兽雕塑手稿：交给陶轮解锁天体后继者雕塑。' },

  /* ---------------- 魔法 · 远古 ---------------- */
  { id: 'nightmare_fuel', cn: '噩梦燃料', en: 'Nightmare Fuel', img: 'Nightmare_Fuel.png', cat: 'magic',
    src: '击杀爬行梦魇、尖牙梦魇等暗影生物，或捡拾梦魇灯 / 梦魇裂隙熄灭后掉落的燃料；也能用 4 个恶魔花瓣在灵子分解器旁合成。',
    note: '暗影类魔法的基础材料；威尔逊「暗影侍臣」技能可以用 1 个纯粹恐惧转化出 2 个噩梦燃料。' },
  { id: 'dreadstone', cn: '绝望石', en: 'Dreadstone', img: 'Dreadstone.png', cat: 'magic', alias: ['恐惧石'],
    src: '挖掉困住「梦魇疯猪」的裂柱外层大理石后，靠它的砸击打碎柱子获得；也可由威尔逊用 3 个纯粹恐惧转化。',
    note: '绝望石盔甲、绝望石头盔等暗影裂隙装备要用它。' },
  { id: 'pure_horror', cn: '纯粹恐惧', en: 'Pure Horror', img: 'Pure_Horror.png', cat: 'magic', alias: ['纯净恐惧', '纯噩梦'],
    src: '击杀梦魇疯猪（掉 4-5 个）、熔合暗影怪，或在暗影裂隙开启后击杀相关生物获得。',
    note: '暗影裂隙装备的材料；给任何用噩梦燃料充能的物品充能时效率是它的两倍。' },
  { id: 'pure_brilliance', cn: '纯粹辉煌', en: 'Pure Brilliance', img: 'Pure_Brilliance.png', cat: 'magic', alias: ['纯净光辉'],
    src: '开采月亮裂隙里长出的亮晶簇（Ryftstal）获得。',
    note: '亮茂锻炉及其全部配方的材料。' },
  { id: 'infused_moon_shard', cn: '灌注月亮碎片', en: 'Infused Moon Shard', img: 'Infused_Moon_Shard.png', cat: 'magic',
    src: '在月雹（Moonstorm）里开采带电的玻璃岩获得；击杀天体英雄会掉 6-12 个。',
    note: '月之系列与亮茂锻炉装备的原料；威尔逊「月之革新者」技能可以让 1 个纯粹辉煌换 2 个灌注月亮碎片。' },

  /* ---------------- 其他资源 ---------------- */
  { id: 'ice', cn: '冰', en: 'Ice', img: 'Ice.png', cat: 'misc',
    src: '挖开小冰川（Mini Glacier）获得，冬天海边也能捡到，冬天以外会重新长出来。',
    note: '离开冰箱 3 天会融化；能做冰帽、冰淇淋、冰块，也能灭火。' },
  { id: 'ashes', cn: '灰烬', en: 'Ashes', img: 'Ashes.png', cat: 'misc',
    src: '烧掉可燃物后捡拾留下的灰烬：篝火残骸、猪火炬、火坑、树木被烧毁后的地面，被火烧死的生物也会掉。',
    note: '灰烬在地上 20 秒会被风吹走，捡起来再丢可以重置计时；和神秘商人换东西很好用。' },
  { id: 'rot', cn: '腐烂物', en: 'Rot', img: 'Rot.png', cat: 'misc',
    src: '食物（蛋类除外）腐坏后变成腐烂物。',
    note: '可以施肥、当燃料；威尔逊能拿 6 个腐烂物「转化」成 1 个粪肥。' },
  { id: 'manure', cn: '粪肥', en: 'Manure', img: 'Manure.png', cat: 'misc', alias: ['粪便', '便便', '肥料'],
    src: '野牛、猪人、考拉象、穴居猴等动物产生，其中野牛群是最好收集的；威尔逊也能用 6 个腐烂物转化。',
    note: '施肥让作物和移植的草丛 / 浆果丛长得更快，也是堆肥、农田相关制作的原料。' },
  { id: 'guano', cn: '蝙蝠粪', en: 'Guano', img: 'Guano.png', cat: 'misc', alias: ['鸟粪', '蝙蝠屎'],
    src: '击杀蝙蝠（Batilisk）掉落；蝙蝠常出没的洞里和石笋地形上也能捡到。',
    note: '施肥效果比粪肥高 50%，但不能用来做农田；当燃料会冒一团臭气。' },
  { id: 'slurtle_slime', cn: '蛞蝓龟黏液', en: 'Slurtle Slime', img: 'Slurtle_Slime.png', cat: 'misc', alias: ['蜗牛黏液', '蛞蝓黏液'],
    src: '蛞蝓龟、蜗牛龟吃下矿物后会产生，击杀它们也会掉落。',
    note: '点燃会爆炸（每份 50 伤害，可引发地震）；也能当燃料。' },

  /* ---------------- 月后（彼岸）材料 ---------------- */
  { id: 'brightshade_husk', cn: '亮壳', en: 'Brightshade Husk', img: 'Brightshade_Husk_Dropped.png', cat: 'mob',
    alias: ['亮茄外壳', '亮壳外壳'],
    src: '击杀「致命亮茄」（Deadly Brightshade）掉落 ×2，属于月缝（Lunar Rift）开启后的「来自彼岸」内容。',
    note: '亮茂锻炉（Brightsmithy）整套装备的核心材料：配合纯粹辉煌可以打造亮茄护甲、头盔、剑、法杖、炸弹、锄铲与修复套装。' },
  { id: 'lucky_gold_nugget', cn: '幸运金块', en: 'Lucky Gold Nugget', img: 'Lucky_Gold_Nugget_Dropped.png', cat: 'ore',
    src: '农历新年活动专属：从红包中开出（来源按年份不同——猪王摔跤赛、胡萝卜鼠赛跑、枕头大战、划船赛等），也可以钓到「花锦鲤 / 金锦鲤」获得。',
    note: '在新年神龛的供奉栏兑换该届活动的专属物品（红鞭炮、红灯笼、浮灯、幸运兽套装等）。注意它和普通金块不同，不会吸引鼹鼠。' },
  { id: 'bio_data', cn: '生物数据', en: 'Bio Data', img: 'Bio_Data_Dropped.png', cat: 'misc',
    src: '用「生物扫描仪」扫描生物后掉落；同一只生物需要冷却 1 天才能再扫。掉落量按生物体型递增（蝴蝶 / 月蛾 1，蜘蛛 / 兔子 / 猎犬 2，鼹鼠 4，伏特羊 5，熊獾 6，帝王蟹 8，龙蝇 / 蜂王 / 独眼巨鹿 10）。',
    note: 'WX-78 专属，用来在生物扫描仪制作各种「电路」（加速电路、活力电路、热能电路等）。' },
  { id: 'prize_ticket', cn: '奖券', en: 'Prize Tickets', img: 'Prize_Ticket.png', cat: 'misc',
    src: '参加「仲夏嘉年华」的小游戏后按表现发放；给乌鸦小孩喂爆米花或玉米冰沙也能换到 1 张。乌鸦小孩看你玩游戏，结束时还会再给 1 张。',
    note: '在奖品亭附近兑换嘉年华奖励，堆叠上限 60。注意它和「嘉年华奖券」是两种东西：奖券用来**兑换奖品**，嘉年华奖券用来**开始游戏**。' },
  { id: 'cawnival_token', cn: '嘉年华奖券', en: 'Cawnival Token', img: 'Cawnival_Token.png', cat: 'misc',
    alias: ['嘉年华代币'],
    src: '可以制作：1 张 = 1 个种子；1 张 = 1 个金块（一次做 3 张）。也可以给乌鸦小孩喂爆米花或玉米冰沙，一次换到 1 张奖券 + 1 张嘉年华奖券。',
    note: '它是「玩游戏的门票」而不是兑换券——**每玩一次小游戏消耗 1 张**，游戏结束后再按表现发奖券，用奖券去奖品亭换东西。同一个乌鸦小孩有喂食冷却（爆米花 1 小时、玉米冰沙 12 分钟）。嘉年华共 6 个小游戏：篮中蛋、鸟鸟吃虫虫、追蛋、保卫鸟巢、布谷鸟转盘、鸟房落球。' },
  { id: 'dry_petals', cn: '干花瓣', en: 'Dried Petals', img: 'Petals_Dropped.png', cat: 'plant', alias: ['干燥花瓣'],
    src: '把普通花瓣放到晾肉架上晾 1 天即可。',
    note: '珍珠茶馆里用 8 / 6 / 4 个干花瓣加 1 个空瓶煮花瓣茶；也能和花瓣一起做荨麻药膏。' },
  { id: 'slurper_pelt', cn: '啜食者皮毛', en: 'Slurper Pelt', img: 'Slurper_Pelt_Dropped.png', cat: 'mob', alias: ['啜食者皮'],
    src: '击杀「啜食者」（Slurper）有 50% 概率掉落。',
    note: '6 张皮加 2 根绳、2 个噩梦燃料，在暗影操纵者旁制作「饥饿腰带」。可以当肉喂猪结交（兔人不认）。' },
  { id: 'palmcone_scale', cn: '棕榈松果鳞片', en: 'Palmcone Scale', img: 'Palmcone_Scale_Dropped.png', cat: 'plant',
    src: '用斧头砍伐成年的棕榈松果树，每棵掉 2 个；也能从海盗藏匿处获得。',
    note: '「月之码头的诅咒」更新内容，用来做码头套件与火炮套件。' },
  { id: 'restrained_static', cn: '受控静电', en: 'Restrained Static', img: 'Restrained_Static.png', cat: 'magic',
    src: '在月亮风暴（Moonstorm）中协助并保护瓦格斯塔夫（Wagstaff），击退畸形鸟与月盲乌鸦后获得。',
    note: '建造月亮虹吸器的最终阶段必需 1 个；也用于灌注雷电长矛、在概念制造机做火花柜。' },
  { id: 'collected_dust', cn: '尘土块', en: 'Collected Dust', img: 'Collected_Dust.png', cat: 'magic', alias: ['收集的尘土'],
    src: '需先用红色「知识之泉」的蒸馏知识解锁蓝图，然后用 1 个盐晶 + 2 个石头 + 1 个硝石制作；远古档案馆的每个远古窑炉也自带 1 个。',
    note: '在烹饪锅煮「琥珀蜜」，也能做铥矿捕虫网。' },
  { id: 'guard_tower_core', cn: '守卫塔核心', en: 'Guard Tower Core', img: 'Guard_Tower_Core_Dropped.png', cat: 'boss',
    src: '击败圣所钥匙房中的「远古守卫塔」，4 座塔各掉 1 个部件——1 个守卫塔核心、1 个火花插槽、2 个暴躁发音器。',
    note: '与火花插槽 ×1、暴躁发音器 ×2 在圣所锻炉制作「守卫塔套件」；也能和猪王换 15 个金块，或献给蚁狮延后 6 天。' },
  { id: 'spark_socket', cn: '火花插槽', en: 'Spark Socket', img: 'Guard_Tower_Core_Dropped.png', cat: 'boss',
    src: '击败圣所钥匙房中的「远古守卫塔」掉落（4 座塔中的 1 座）。',
    note: '守卫塔套件的部件之一。注意它和「火花柜」（Spark Ark）不是同一样东西。' },
  { id: 'cranky_articulator', cn: '暴躁发音器', en: 'Cranky Articulator', img: 'Guard_Tower_Core_Dropped.png', cat: 'boss',
    src: '击败圣所钥匙房中的「远古守卫塔」掉落，4 座塔中有 2 座各掉 1 个。',
    note: '制作守卫塔套件需要 2 个；也能和猪王换 15 个金块。' },
  { id: 'thermal_goo', cn: '热能腺体', en: 'Thermal Goo', img: 'Thermal_Balm_Dropped.png', cat: 'mob', alias: ['热能粘液'],
    src: '击杀「地热螨」（Geothermite）等喷气孔地形的生物掉落。',
    note: '用于炼金引擎制作热能药膏等防寒装备；也是火系工具（炽焰斧、加热园艺锄）的材料。' },
  { id: 'bramble_husk', cn: '荆棘外壳', en: 'Bramble Husk', img: 'Bramble_Husk.png', cat: 'mob', alias: ['荆棘壳'],
    src: '沃姆伍德（Wormwood）角色专属，在「绿拇指」标签页用 2 个活木 + 4 个骨头碎片制作。',
    note: '450 耐久、吸收 80% 物理伤害的护甲；被攻击时对周围 1 格内生物造成约 22.6 点伤害，并完全免疫尖刺灌木、荆棘与仙人掌的伤害（且不掉耐久）。' },
  { id: 'compost_wrap', cn: '堆肥包', en: 'Compost Wrap', img: 'Compost_Wrap.png', cat: 'misc', alias: ['肥料包'],
    src: '沃姆伍德（Wormwood）专属，在「绿拇指」标签页用 5 个粪肥 + 2 个腐烂物 + 1 个硝石制作。',
    note: '一次性恢复 30 点生命，也能用来治疗大多数生物（切斯特和多数怪物除外）。' },
  { id: 'tillweed', cn: '荨麻', en: 'Tillweeds', img: 'Tillweeds.png', cat: 'plant',
    src: '在农田里拔除杂草「荨麻」（Tillweed）获得，属于「种瓜得瓜」更新的杂草系统。',
    note: '和花瓣、木炭一起做荨麻药膏；晾干后可在珍珠茶馆做荨麻茶。' },
  { id: 'succulent', cn: '多肉植物', en: 'Succulent', img: 'Succulent_Build.png', cat: 'plant',
    src: '夏天在沙漠绿洲的湖边生成，采摘获得。',
    note: '可直接吃（回 1 点生命）；2 个多肉加 1 个切石能做盆栽多肉，晾干后可在珍珠茶馆做多肉茶。' },
  { id: 'cave_banana', cn: '洞穴香蕉', en: 'Cave Banana', img: 'Banana_Dropped.png', cat: 'plant',
    src: '从洞穴 / 遗迹村庄群系的洞穴香蕉树上采摘，约 4 天重新结果；洞穴猴也会掉落。',
    note: '可以生吃或烤熟；带在身上会让洞穴猴更爱跟着你（也更容易被偷）。' },
  { id: 'wet_goop', cn: '湿糊糊', en: 'Wet Goop', img: 'Wet_Goop.png', cat: 'misc', alias: ['湿糯糊糊', '糊糊'],
    src: '烹饪锅里放进任何不构成有效配方的组合，就会产出湿糊糊；孵化中的高脚鸟蛋放置过久也会变成它。',
    note: '吃掉没有任何收益（沃利除外）。可以用来引诱饥饿的猪、当陷阱诱饵，或者等它腐烂后回收成腐烂物。' },
  { id: 'black_flag', cn: '黑色海盗旗', en: 'Black Flag', img: 'Black_Flag_Dropped.png', cat: 'misc',
    src: '用锤子砸毁「月之码头海盗旗」后掉落。',
    note: '用 1 面旗加 2 个原木可以重建月之码头海盗旗；和船长三角帽、藏红花羽毛一起做「波莉罗杰的帽子」。' },
  { id: 'captains_tricorn', cn: '船长三角帽', en: "Captain's Tricorn", img: "Captain's_Tricorn_Dropped.png", cat: 'mob',
    alias: ['船长帽'],
    src: '「海盗突袭」事件中击杀海盗大副（Prime Mate）掉落。',
    note: '戴上后所在船只的耐久损耗减半、碰撞伤害减半；也是制作「波莉罗杰的帽子」的必需材料。' },
  { id: 'portation_orb', cn: '传送宝珠', en: 'Portation Orb', img: 'Sanctum_Waymark.png', cat: 'magic',
    src: '在圣所内「破损的圣所路标」附近拾取。',
    note: '用于修复破损的圣所路标；也能在圣所锻炉拆解成 3 个传送宝珠碎片。' },
  { id: 'lucy_the_axe', cn: '露西斧', en: 'Lucy the Axe', img: 'Lucy_the_Axe_Dropped.png', cat: 'misc',
    src: '伍迪（Woodie）开局自带，无法制作。',
    note: '无限耐久，一次挥砍等于普通斧头砍两下；露西是有自我意识的，会说话、也会在伍迪快变海狸时警告他。不能被打劫或吃掉。' },
  { id: 'luxury_axe', cn: '华丽斧', en: 'Luxury Axe', img: 'Luxury_Axe.png', cat: 'misc',
    src: '用 2 个金块 + 4 个树枝在科学机器解锁后制作。',
    note: '砍树比普通斧头快，耐久也更高；属于「金工具」系列。' },
  { id: 'opulent_pickaxe', cn: '华丽镐', en: 'Opulent Pickaxe', img: 'Opulent_Pickaxe.png', cat: 'misc',
    src: '用 2 个金块 + 4 个树枝在科学机器解锁后制作。',
    note: '挖矿比普通镐快，耐久也更高；属于「金工具」系列。' },
  { id: 'volatile_canary', cn: '金丝雀（易挥发）', en: 'Volatile Canary', img: 'Canary_Build.png', cat: 'mob',
    alias: ['易挥发金丝雀'],
    src: '把金丝雀放进洞穴的鸟笼，在毒菌蟾蜍存活期间等 6-12 分钟，鸟就会中毒变成易挥发金丝雀。',
    note: '带到地面放生可掉 5-6 根藏红花羽毛；在洞穴放出会爆炸并掉 1-2 根，爆炸还能把附近的毒菌蟾蜍变成「悲惨蟾蜍」。也能做午睡袋。' },
  { id: 'moss', cn: '苔藓', en: 'Mossy Turf', img: 'Mossy_Turf.png', cat: 'plant', alias: ['苔藓地皮'],
    src: '在蘑菇森林等洞穴 / 遗迹地形采集，也可用草叉挖取苔藓地皮。',
    note: '用于铺设苔藓类地皮与相关装饰制作。' },

  /* ---------------- 其他：配方里会引用到的杂项 ---------------- */
  { id: 'log_suit', cn: '木甲', en: 'Log Suit', img: 'Log_Suit.png', cat: 'misc', alias: ['木制护甲'],
    src: '用 8 个木头 + 2 根绳子在科学机器解锁后制作，属于基础护甲。',
    note: '吸收 80% 物理伤害；是鳞片护甲等进阶护甲的合成材料之一。' },
  { id: 'gadget', cn: '小装置', en: 'Gadget', img: '', cat: 'misc', alias: ['小配件'],
    src: '在「废料」相关的制作线中产出，属于瓦格斯塔夫（Wagstaff）科技体系的部件。',
    note: '便携聚光灯、传送站等瓦格斯塔夫装置的共用部件。官方图库暂无独立图标，本页用文字占位。' },
  { id: 'bucket_o_poop', cn: '便便桶', en: 'Bucket-o-poop', img: 'Bucket-o-poop.png', cat: 'misc', alias: ['粪桶'],
    src: '用 1 个粪肥 + 3 个种子 + 1 个电子零件在科学机器解锁后制作。',
    note: '可以给作物施肥、也能给蘑菇灯等照明结构补充燃料，是农业流常用的工具。' },
  { id: 'rotten_egg', cn: '腐烂的蛋', en: 'Rotten Egg', img: 'Rotten_Egg_Dropped.png', cat: 'misc', alias: ['坏蛋'],
    src: '鸟蛋放置过久腐坏后变成；也能从风滚草或企鹅的巢边捡到。',
    note: '火药的必要材料；也能当肥料，或用来做硫磺实验。' },
  { id: 'soul', cn: '灵魂', en: 'Soul', img: 'Soul_Dropped.png', cat: 'magic',
    src: '「亡者复苏」（Reap What You Sow）等召唤系内容中，由被击败的生物留下。',
    note: '召唤与复活类配方的消耗品，例如顺手背包、双尾之心。' },
  { id: 'moonlens', cn: '月眼', en: 'Moonlens', img: 'Blue_Moonlens_Dropped.png', cat: 'magic', alias: ['月之透镜', '蓝色月眼', '紫色月眼', '橙色月眼'],
    src: '在月岛与月亮洞穴中开采 / 拾取，共有蓝、紫、橙等不同颜色。',
    note: '月相盘与月眼守卫的核心部件；不同颜色的月眼对应不同的建造配方。' },
  { id: 'gentleman_vest', cn: '绅士背心', en: "Gentleman's Vest", img: '', cat: 'misc',
    src: '《泰拉瑞亚》联动内容中的致敬时装（致敬威尔逊的背心），并非 DST 本体物品。',
    note: '在 DST 的「泰拉瑞亚联动」活动期间可以获得对应外观；冬熊背心等配方会引用它。官方图库暂无独立图标，本页用文字占位。' },
  { id: 'chilled_lavae', cn: '冰冻岩浆虫', en: 'Chilled Lavae', img: 'Chilled_Lavae_Dropped.png', cat: 'mob',
    src: '用冰杖冻结岩浆虫后击杀获得，或由龙蝇巢穴相关内容产出。',
    note: '小动物「小龙」（Broodling）的领养材料之一。' }
];
